ComPlat/chemotion_ELN

- Gemfile
- Gemfile.lock
- lib/report/image.rb
- lib/report/rtf_report.rb
- lib/svg/reaction_composer.rb
after generating reaction reports, you should find correct and well-fit image in rtf reports.
> fix reaction image in rtf report

- app/assets/javascripts/components/CollectionTree.js
- app/assets/javascripts/components/ElementAllCheckbox.js
- app/assets/javascripts/components/ElementsSvgCheckbox.js
- app/assets/javascripts/components/ElementsTable.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/SampleDetailsAnalyses.js
- app/assets/javascripts/components/SampleForm.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/stores/ElementStore.js
The Analysis Header will now show its type and status. Also suppress the warning related to uncontrolled input
> Add analyze tab header detail

- app/api/chemotion/report_api.rb
- app/assets/javascripts/components/ElementAllCheckbox.js
- app/assets/javascripts/components/ElementDetails.js
- app/assets/javascripts/components/Elements.js
- app/assets/javascripts/components/ElementsTable.js
- app/assets/javascripts/components/List.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/actions/ReportActions.js
- app/assets/javascripts/components/contextActions/ContextActions.js
- app/assets/javascripts/components/contextActions/CreateButton.js
- app/assets/javascripts/components/contextActions/ReportButton.js
- app/assets/javascripts/components/models/Report.js
- app/assets/javascripts/components/report/ReactElements.js
- app/assets/javascripts/components/report/ReportContainer.js
- app/assets/javascripts/components/report/Reports.js
- app/assets/javascripts/components/report/Settings.js
- app/assets/javascripts/components/routes.js
- app/assets/javascripts/components/stores/ElementStore.js
- app/assets/javascripts/components/stores/ReportStore.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/report.scss
- lib/template/reaction_content.rb
- lib/template/reaction_report.rb
- lib/template/reactions_report.rb
I disable checkedAll checkBox at Element List under report-view.
This is due to current data structure when check checkedAll.
__Future work:__
1. improve report format
2. add sample analysis
3. re-open reactions list checkedAll box
4. a list let user to determine reactions order
5. user customised default setting
6. page break between each reactions in the RTF report.
7. comment function
> generate multi-reactions report

- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/structure_editor/StructureEditorModal.js
- app/serializers/detail_levels/sample.rb
- app/serializers/sample_serializer.rb
Sample editor will show warning message if the sample has parents or children.
> sample editor warning for descendents resolve #301

- app/api/chemotion/sample_api.rb
- app/models/sample.rb
Make reactant samples invisible in the sample list.
> hide reactants in List resolve #302

- Gemfile
- Gemfile.lock
- db/schema.rb
Reference to Ketcherails changeset
https://github.com/ComPlat/ketcher-rails/commit/e9895f0108b000d652c1bd0bfd2b26d505940a5b
> Use new Ketcher-Rails version 0.1.2 with user templates

- app/assets/javascripts/components/CollectionManagement.js
- app/assets/javascripts/components/NumeralInputWithUnitsCompo.js
- app/assets/javascripts/components/collection_management/MyCollections.js
- app/assets/javascripts/components/collection_management/MySharedCollections.js
Suppress the 'key' field relate warning
> Fix 'key' field warning

- app/api/chemotion/search_api.rb
- app/models/molecule.rb
- db/migrate/20160719130259_add_num_set_bits_to_molecule.rb
Sort the structure search result by Tanimoto. Besides, we have a threshold for the search, only show results with the Tanimoto coefficient > 0.5.
Resolve for this issue #352
> Sort structure search result by Tanimoto

- app/models/molecule.rb
- db/migrate/20160722111824_update_molecule_num_set_bits.rb
- Calculate Tanimoto as float, more accurate sort
- Re-calcuate the num_set_bits after changing polymer molecule
> Update polymer search

- app/api/chemotion/molecule_api.rb
- app/assets/javascripts/components/ElementsTableSampleEntries.js
- app/assets/javascripts/components/SampleDetails.js
- app/models/sample.rb
> Use SVG from editor as sample preview in all cases resolve #368

- app/api/chemotion/reaction_api.rb
- app/api/chemotion/sample_api.rb
- app/api/chemotion/screen_api.rb
- app/api/chemotion/wellplate_api.rb
- app/assets/javascripts/components/CollectionTree.js
- app/serializers/collection_remote_serializer.rb
- app/serializers/collection_serializer.rb
- app/serializers/user_serializer.rb
- spec/api/collection_api_spec.rb
- spec/api/sample_api_spec.rb
correct labels of root remote collections (root shared with me collection)
add user info (name and user type) w BS OverlayTrigger
fix recordnotfound on collection when fetching elements on root remote collections
resolve #373 #386
> Shared collection label

- app/assets/javascripts/components/App.js
- app/assets/stylesheets/navigation.scss
> responsive fixedTop navbar w dynamic top padding using css

- app/assets/javascripts/components/ElementCollectionLabels.js
- app/assets/javascripts/components/ElementReactionLabels.js
- app/assets/javascripts/components/report/ReportElements.js
+ Prevent old onClick while clicking on this icon
+ Fix typo error 'Sarting Material' in report panel
+ Change the 'succeed' icon to white on blue background
> Prevent onClick on 'link-to-collection' icon

- .travis.yml
- app/models/user.rb
- spec/factories/groups.rb
- spec/factories/persons.rb
- spec/models/user_spec.rb
> fix broken validation  for name_abbreviation

- .gitignore
- app/assets/javascripts/components/PolymerSection.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/SampleForm.js
1. add footer(with cancal/save button) to SampleDetail
2. add /coverage to ```.gitignore```
> SampleDetail footer with cancal/save button

- app/api/chemotion/collection_api.rb
- app/assets/javascripts/components/collection_management/MySharedCollections.js
- app/assets/javascripts/components/managing_actions/AssignButton.js
- app/assets/javascripts/components/managing_actions/ManagingActions.js
- app/assets/javascripts/components/managing_actions/ManagingModal.js
- app/assets/javascripts/components/managing_actions/ManagingModalCollectionActions.js
- app/assets/javascripts/components/managing_actions/ManagingModalSharing.js
- app/assets/javascripts/components/stores/CollectionStore.js
- app/models/fingerprint.rb
> Fix assign sample, upd shared coll permissions

- app/api/api.rb
- app/api/chemotion/collection_api.rb
- app/api/chemotion/reaction_api.rb
- app/api/chemotion/sample_api.rb
- app/api/chemotion/screen_api.rb
- app/api/chemotion/wellplate_api.rb
- app/assets/javascripts/components/ElementReactionLabels.js
- app/proxies/element_permission_proxy.rb
- spec/proxies/element_permission_proxy_spec.rb
lessen requests to db (eg bypass ElementPermissionProxy if own collection)
limit elements per page to 100 /50
> Opt element serialization

- lib/really_destroy_task.rb
- spec/lib/really_destroy_task_spec.rb
> add 8d grace time to really_destroy_task

- app/models/fingerprint.rb
- db/migrate/20160719130259_add_num_set_bits_to_molecule.rb
- spec/factories/fingerprints.rb
- spec/models/fingerprint_spec.rb
- Refactor fingerprint model
- Add rspec for fingerprint
- Edit an old migrate to stop populate a deleted column (molecule.num_set_bits), so that it does not take much time if migrate from the beginning
> RSpec fingerprint

- app/models/fingerprint.rb
- spec/models/fingerprint_spec.rb
> Fingerprint RSpec

- app/assets/javascripts/components/Dataset.js
- app/assets/stylesheets/structur_editor.css
- Analysis dataset name will be automatically set based on the last attachment name
- Change CSS bug for Dataset Modal to fit with StructurEditorModal
- Resolve #454, #451
> Automatically set Dataset name based on attachment

- Gemfile
- Gemfile.lock
- app/api/chemotion/collection_api.rb
- app/api/chemotion/permission_api.rb
- app/api/chemotion/sample_api.rb
- app/models/concerns/collectable.rb
- app/policies/element_policy.rb
- app/policies/elements_policy.rb
- spec/api/collection_api_spec.rb
- spec/fixtures/body_TXWRERCHRDBNLG-UHFFFAOYSA-N.json
- spec/fixtures/body_XLYOFNOQVPJJNP-UHFFFAOYSA-N.json
- spec/policies/elements_policy_spec.rb
- spec/spec_helper.rb
- optimize ElementsPolicy (resolve #436)
- add spec/policy/elements_policy_spec
- install webmock (isolate all request to pubchem in test)
> Elem policy opt

- app/assets/javascripts/components/App.js
- app/assets/javascripts/components/CollectionManagement.js
- app/assets/stylesheets/application.scss
- Add a button a hide colelctionTree, so that we have more space for ElementsDetails table
- Fix a warning to unknown "inverse" props in CollectionManagement
> Add button to hide CollectionTree

- app/assets/javascripts/components/App.js
Temporary disable the keyboard navigation until we figure out a way to combine it with input field
> Temporary disable the keyboard navigation

- Gemfile.lock
- app/assets/javascripts/components/structure_editor/StructureEditorModal.js
- app/assets/stylesheets/structur_editor.css
* Use 90vw CSS option
* Keep small windows size when warning is shown
* Update Ketcherails revision
> Change editor window size to 90% of screen width

- app/assets/javascripts/components/ElementDetails.js
- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/MaterialCalculations.js
- app/assets/javascripts/components/MaterialGroup.js
- app/assets/javascripts/components/MaterialGroupContainer.js
- app/assets/javascripts/components/NumeralInputWithUnitsCompo.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/stylesheets/reaction.scss
> Compact scheme

- .travis.yml
- Gemfile.lock
- config/deploy.rb
- config/environments/production.rb
* fix linked dirs for backups
* server static assets for mounted engines
* create public/stylesheets empty dir
* update Travis.yml config to cache node modules
> Deploy fixes and dependencies update

- app/assets/javascripts/components/App.js
> fix Dom element error when not on pages/welcome

- lib/tasks/rake_routes.rake
with this, you can run ```rake grape:routes``` on command line and get routes.
> fix rake grape:routes

- app/assets/javascripts/components/Material.js
> resolve dual export in Material.js

- app/api/chemotion/search_api.rb
- fix duplicate result in reaction, wellplates, screens
- fix a bug break substring search
- resolve #477
> String search fix resolve #477

- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/stylesheets/elements_table.css
- Change Sample, Wellplate, Screen title to header
- Add pointer cursor to ElemenetAnalysisLabel and ElementCollectionLabel
- Keep ElementLabel in SampleDetail, move label to header in Wellplate and Screen
> Change element title to header

- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/MaterialGroup.js
- app/assets/javascripts/components/ReactionDetailsMainProperties.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
- lib/svg/reaction_composer.rb
display multiple solvents @ reactions detail
> display multiple solvents resolve #502

- spec/fixtures/images/reaction.svg
resolve the rspec failure for #152
> update spec/fixtures base on multiple solvents

- app/helpers/application_helper.rb
- app/views/pages/settings.haml
> render plugin settings if exist

- app/assets/javascripts/components/ReactionDetailsProperties.js
- app/assets/stylesheets/reaction.scss
> Reaction duration one line

- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- Add icon to header of SampleDetail, WellplateDetail, and ScreenDetail
- Resolve #463
> Add Element icon to ElementDetail header

- app/assets/javascripts/components/models/Sample.js
- Fix polymer display bug while dragging polymer into reaction Product
- Resolve #441
> Display Polymer in Reaction Product

- app/assets/javascripts/components/Material.js
> Reaction IUPAC

- app/assets/javascripts/components/contextActions/CreateButton.js
- Switch to SplitButton on the old create element button 
- Resolve #494
> Use SplitButton on old createElementButton

- app/assets/javascripts/components/Navigation.js
- app/assets/javascripts/libHome/NavHead.js
> mv navigation header to a new comp

- app/assets/javascripts/components/ReactionDetails.js
- package.json
Now, you can zoom & pan reaction svg.
> reaction svg file with zoom-pan functions

- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/javascripts/components/WellplateList.js
- app/assets/stylesheets/elements_details.css
- Fix the close button on CreateWellplate and CreateScreen
- Suppress warning in WellplateDetail
> Fix close button on Header

- app/api/chemotion/reaction_api.rb
- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
- app/assets/javascripts/components/models/Reaction.js
- app/assets/javascripts/components/models/Sample.js
- app/models/reaction.rb
- app/models/sample.rb
- db/migrate/20160920091519_add_short_label_to_reactions.rb
- db/migrate/20160920105050_add_creatd_by_to_reactions.rb
- spec/api/reaction_api_spec.rb
- spec/factories/reactions.rb
- Add short_label and created_by to Reactions table
- Automatically increase reaction counter on create a new one
- Reactions will now have owner/creator
- Change ReactionDetails title to use short_label as in SampleDetails
- Resolve #507
> Add Reaction counter

- app/assets/javascripts/components/ReactionDetailsProperties.js
- If start time > stop time, display a message, and disable copy clipboard button
- Resolve #482
> No negative duration

- app/api/chemotion/reaction_api.rb
- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
- app/assets/javascripts/components/models/Reaction.js
- app/assets/javascripts/components/models/Sample.js
- app/models/sample.rb
- app/serializers/detail_levels/reaction.rb
- Add some missed changes that are removed from last merge
- Auto naming the reaction products: {reaction_short_label}-{A..z}
- Resolves #508
> Auto naming Reaction Products

- Gemfile.lock
- app/api/chemotion/reaction_api.rb
- app/api/chemotion/sample_api.rb
- app/api/chemotion/screen_api.rb
- app/api/chemotion/wellplate_api.rb
- app/assets/javascripts/components/fetchers/ReactionsFetcher.js
- app/assets/javascripts/components/fetchers/SamplesFetcher.js
- app/assets/javascripts/components/fetchers/ScreensFetcher.js
- app/assets/javascripts/components/fetchers/WellplatesFetcher.js
- Fix a bug when deleting all elements in current collection but accidentaly remove every element in other collection
- Resolves #552
> Fix DeleteAll

- lib/tasks/reactions.rake
Populate all reactions short_label
> Populate reactions short_label

- app/assets/javascripts/components/ReactionDetailsMainProperties.js
- Expand the reaction description text area to be at lease 10 lines
- Resolves 545
> Reaction description at lease 10 lines

- app/assets/javascripts/components/ElementCollectionLabels.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/stylesheets/elements_details.css
- Refactor ElementDetails header (CSS and JS)
- Fix the UI bug in create Wellplate/Screen
- Add a tooltip on every button in the header (save, close, generateReport)
- Resolve #554
> ElementDetails header refactor

- app/assets/javascripts/components/contextActions/ContextActions.js
- app/assets/javascripts/components/contextActions/CreateButton.js
- app/assets/javascripts/components/contextActions/ExportImportButton.js
- app/assets/javascripts/components/managing_actions/ManagingActions.js
- app/assets/javascripts/components/managing_actions/MoveOrAssignButton.js
- app/assets/javascripts/components/managing_actions/RemoveOrDeleteButton.js
- app/assets/javascripts/components/managing_actions/ShareButton.js
- Disabled navigation button instead of hiding them
- Resolves #563
> Navigation Button revised

- Gemfile
- Gemfile.lock
- app/api/chemotion/molecule_api.rb
- app/assets/stylesheets/molecules.css
- app/assets/stylesheets/reaction.scss
- lib/svg/reaction_composer.rb
- spec/fixtures/images/compose_reaction_svg.svg
- spec/fixtures/images/molecule.svg
- spec/fixtures/images/reaction.svg
- spec/modules/svg_reaction_composer_spec.rb
chemical bond with uniform scaling for  all samples of the reaction svg 
resolve #519
> Fix svg size

- app/proxies/element_permission_proxy.rb
> upd permission_proxy for wellplate in a syn coll

- app/assets/javascripts/components/ElementsTable.js
- app/assets/javascripts/components/ElementsTableSampleEntries.js
- Add a checkbox to show/hide sample svg
- Resolves #573
> Show/Hide sample SVG

- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/stylesheets/elements_details.css
- Add a new button to strecht ElementDetails Panel to full screen
- Resoves #572
> Add FullScreen button to ElementDetails

- app/assets/javascripts/components/Well.js
- app/assets/javascripts/components/WellOverlay.js
* always take SVG from sample for wellplates
* typo fix for UIState call
> Fix samples SVG for wellplates resolve #605

- app/api/chemotion/reaction_api.rb
- app/usecases/wellplates/wellplate_updater.rb
- spec/controllers/pages_controller_spec.rb
- spec/models/molecule_spec.rb
- spec/models/sample_spec.rb
- spec/models/user_spec.rb
- Update to use with `!`
- Resolves #555
> Use ActiveRecord exclamation mark

- app/assets/javascripts/components/Analysis.js
- app/assets/javascripts/components/SampleDetailsAnalyses.js
fix missing Labels for input forms of analyses
> relocate 'remove' btn to analysis header resolve #593

- app/assets/javascripts/components/SampleDetailsAnalyses.js
> relocate add analysis button

- app/assets/javascripts/components/SampleDetailsAnalyses.js
- lib/svg/reaction_composer.rb
- spec/fixtures/images/reaction.svg
fix wrong proptype in sampledetailsanalyse
> relocate yield to below mid-sample resolve #609

- app/assets/javascripts/components/ElementCollectionLabels.js
- app/assets/javascripts/components/ElementReactionLabels.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/fetchers/ReactionsFetcher.js
- app/assets/javascripts/components/stores/ElementStore.js
- app/assets/stylesheets/elements_details.css
- app/assets/stylesheets/elements_table.css
- Fix a bug while sample is shared, but associated reaction is not shared: display a modal to inform the user about permission.
- Add placement to CollectionLabel custom overlay
- Resolves #578
> Fix ReactionLabel navigation

- app/assets/javascripts/components/ReactionDetailsScheme.js
> Autonaming to product name

- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/stylesheets/elements_table.css
- Re-position CollectionLabel in SampleDetail, WellplateDetail, ScreenDetail
- Resolves #608
> CollectionLabel positioning

- app/assets/javascripts/components/ElementsTable.js
- app/assets/javascripts/components/ElementsTableSampleEntries.js
- Add a checkbox to collapse: check to collapse, un-check to back to the previous state
- Resolves #590
> Collapse all Molecule in Sample list

- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/WellOverlay.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/routes.js
- app/assets/javascripts/components/stores/ElementStore.js
- We can edit sample, close it then back to wellplate
- Resolves #603
> Edit/Close Sample with WellplateDetail

- app/assets/javascripts/components/WellplateDetails.js
- Fix Wellplate floppy save button
- Resolve #617
> Wellplate floppy save button

- app/assets/javascripts/components/AnalysisDatasets.js
- app/assets/javascripts/components/SampleDetailsAnalyses.js
- Update analysis while editing
- Resolves #607
> Analysis update while editing

- app/api/chemotion/sample_api.rb
- app/assets/javascripts/components/stores/NotificationStore.js
- lib/import/import_samples.rb
1. import excel must have smiles or molfile.
2. If there is any file during saving new samples, return failure rows and all data will not be saved.
> import is atmoic & use smile or molfile

- app/api/chemotion/report_api.rb
export columns:
1.  remove sample_svg_file
2.  add inchistring
> refine export columns resolve #584 #594

- app/assets/javascripts/components/stores/ElementStore.js
- app/models/sample.rb
After updating sample SVG, the reaction SVG will also be updated.
> update corresponding reactions for an updated sample. resolve #623

- app/api/chemotion/search_api.rb
- app/api/chemotion/suggestion_api.rb
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/fetchers/SearchFetcher.js
- app/assets/javascripts/components/routes.js
- app/assets/javascripts/components/search/AutoCompleteInput.js
- app/assets/javascripts/components/search/Search.js
- app/assets/javascripts/components/stores/ElementStore.js
- app/assets/javascripts/components/stores/UIStore.js
- app/models/sample.rb
- app/search/all_element_search.rb
- config/initializers/pg_search.rb
- spec/search/all_element_search_spec.rb
- Reduce number search results by increase the threshold
- Add external_label for searching
- Fix substring search
- Resolves #596 #597
> Revise Search

- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/WellOverlay.js
- app/assets/javascripts/components/Wellplate.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/stylesheets/application.scss.erb
- app/assets/stylesheets/reaction.scss
1. make the well popover always points to the corresponding well after scrolling.
2. css update for panel-detail.
> Well popover stays in a correct position after scrolling. resolve #616

- Gemfile.lock
- app/assets/javascripts/components/App.js
- app/assets/javascripts/components/CollectionSubtree.js
- app/assets/javascripts/components/CollectionTree.js
- app/assets/javascripts/components/Elements.js
- app/assets/javascripts/components/actions/CollectionActions.js
- app/assets/javascripts/components/stores/CollectionStore.js
- Toggle collection tree by clicking on the collection categories title
- Fix expand button width, so that the text is fixed when clicking on it
- Resolves #624
> Toggle collection tree

- app/assets/javascripts/components/managing_actions/ShareButton.js
- Change text: "Share/Split sample" to "Share element"
- Resolves #629
> Share button

- app/api/api.rb
- app/api/chemotion/sample_api.rb
- app/assets/javascripts/components/fetchers/ReactionsFetcher.js
- app/assets/javascripts/components/fetchers/SamplesFetcher.js
- app/assets/javascripts/components/fetchers/ScreensFetcher.js
- app/assets/javascripts/components/fetchers/WellplatesFetcher.js
- All Element using the same default paging number
- Resolves #637
> Reaction paging

- app/assets/javascripts/components/Material.js
- Reactant display order: iupac-name > name > sum_formular
- Resolves #650
> Display reactant name

- app/assets/javascripts/components/ElementAnalysesLabels.js
- app/assets/javascripts/components/ElementReactionLabels.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/SampleDetails.js
- Move info tag to ElementDetails header 
- Add Reaction tag to SampleDetails header
- Resolves #633 #634
> Info tag in ElemenDetails header

- app/assets/javascripts/components/CollectionSubtree.js
- app/assets/javascripts/components/CollectionTree.js
- app/serializers/collection_serializer.rb
- spec/api/collection_api_spec.rb
- Save expanded collection
- Fix a bug while colelction and synchronized collection with the same id are clicked
- Resolves #631, #632
> CollectionTree enhanced

- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/MaterialGroup.js
- app/assets/javascripts/components/MaterialGroupContainer.js
- app/assets/javascripts/components/NumeralInputWithUnitsCompo.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
- app/assets/javascripts/components/models/Reaction.js
concentration = mol / solvents volume
show ```n.d.``` for NaN or infinity.
> concentration = mol/solventsVolume. resolve #640 #641

- app/assets/javascripts/components/ElementsTableSampleEntries.js
- app/assets/javascripts/components/models/Sample.js
- app/assets/stylesheets/common.scss
- app/assets/stylesheets/sample.scss
make sample list with labels:
1. sample name: bold, black
2. external label: bold, gray
> sample list extLabel/name style resolve #627

- app/assets/javascripts/components/SampleDetailsAnalyses.js
- app/assets/javascripts/components/staticDropdownOptions/options.js
- app/assets/stylesheets/sample.scss
1. add 'extraction' to reaction purification
2. no analyses CSS
> reaction purification add extraction / no analyses CSS. resolve #639 #644

- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- Fix full screen when resize
- Resolves #648
> Full Screen when resize

- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/MaterialGroup.js
- Remove "Ref" column in Product part of Reaction Schema
- Resolves #653
> Remove "Ref" column

- app/assets/javascripts/components/SampleForm.js
- Disabled polymer density and melting-point
- Resolves #638
> Disabled polymer density and melting-point

- app/assets/javascripts/components/actions/ElementActions.js
- Display notification while loading for search results
- Resolves #620
> Search notification

- app/assets/javascripts/components/SampleForm.js
set values to n.d instead 0.000 for disabled input boiling pt, melting pt, density of SP supported samples
> set values to nd for polym samp (density , bl pt, ml pt) reresolve #638

- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/MaterialGroup.js
- app/assets/javascripts/components/NumeralInputWithUnitsCompo.js
- app/assets/stylesheets/reaction.scss
1. adjust style for reaction scheme table
2. input padding smaller
3. align T/R of starting materials, reactants, products
4. no space between number and ```%``` in equiv/yield
> adjust reaction scheme table

- lib/svg/reaction_composer.rb
- spec/fixtures/images/compose_reaction_svg.svg
- spec/fixtures/images/reaction.svg
1.  increase font-size for report
2. refine syntax
> refine SVG::ReactionComposer & increase report font-size

- lib/chemotion/open_babel_service.rb
- lib/import/import_samples.rb
Fix the SVG problem when the import field only has ```smiles```.
> fix only-smiles-import no svg problem

- app/api/chemotion/reaction_api.rb
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/ReactionDetailsMainProperties.js
- app/assets/javascripts/components/ReactionDetailsShare.js
- app/assets/javascripts/components/lineChart/EditableCell.js
- app/assets/javascripts/components/lineChart/EditableTable.js
- app/assets/javascripts/components/lineChart/LineChart.js
- app/assets/javascripts/components/lineChart/LineChartContainer.js
- app/assets/javascripts/components/models/Reaction.js
- app/assets/stylesheets/elements_details.css
- app/models/reaction.rb
- db/migrate/20160926113940_update_reaction_temperature.rb
- db/schema.rb
- lib/report/docx/image.rb
- Change Reaction temperature field to a Hash
- Add a temperature chart based on temperature field
- User still can input a static temperature field
- Add a temperature table to edit new temperature field
- Add a button to hide/display temperature chart
- Add a button to change temperature unit.
- User are able to convert between Celcius, Fahrenheit, and Kelvin degree
- Limit temperature table length
- Resolves #550, #551
> Make Reaction temperature a time series

- Gemfile
- Gemfile.lock
- app/api/chemotion/sample_api.rb
- app/assets/javascripts/components/contextActions/ExportImportButton.js
- app/assets/javascripts/components/stores/NotificationStore.js
- app/models/molecule.rb
- lib/chemotion/open_babel_service.rb
- lib/chemotion/pubchem_service.rb
- lib/import/import_samples.rb
- lib/import/import_sdf.rb
- lib/pub_chem.rb
- spec/fixtures/body_two_compounds.json
- spec/fixtures/two_compound.sdf
- spec/lib/import/import_sdf_spec.rb
- spec/search/all_element_search_spec.rb
- spec/spec_helper.rb
w notification
fetch pubchem info  for inchikey array
create multiple molecules by inchikey if not exist
create multiple samples for successfully created molecules
notify molecule/sample counts
spec fix: mock up response
clean smiles from obabel
skip sanitize molfile
> create molecules & sample from sdf/sd file w batch req to Pubchem

- app/assets/javascripts/components/actions/ReportActions.js
- app/assets/javascripts/components/constant/ItemTypes.js
- app/assets/javascripts/components/report/Orders.js
- app/assets/javascripts/components/report/OrdersDnD.js
- app/assets/javascripts/components/report/ReportContainer.js
- app/assets/javascripts/components/report/Reports.js
- app/assets/javascripts/components/stores/ReportStore.js
- spec/javascripts/fixture/report.js
- spec/javascripts/report/ReportContainer.spec.js
- spec/javascripts/report/Reports.spec.js
- spec/javascripts/stores/ReportStore.spec.js
1. refactor report local state to store
2. add Report-Order tab which let you drag-n-drop
> Report order dnd

- Gemfile
- Gemfile.lock
- INSTALL.md
- app/models/reaction.rb
- lib/report/docx/image.rb
- lib/report/docx/reaction_detail.rb
- lib/svg/products_composer.rb
- lib/svg/reaction_composer.rb
- spec/api/reaction_svg_api_spec.rb
- spec/fixtures/images/compose_reaction_svg.svg
- spec/fixtures/images/reaction.svg
- spec/lib/report/docx/image_spec.rb
- spec/lib/report/docx/reaction_detail_spec.rb
1. report image format: png -> eps(vector)
2. refactor reaction_composer for vector graph
3. DRY: inherit products_composer from reaction_composer
> Report eps format

- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
In reaction-scheme, solvents should show the external label.
> fix reaction solvents titile

- app/assets/javascripts/components/models/Reaction.js
- app/assets/javascripts/pages.js.erb
- app/controllers/pages_controller.rb
- app/models/sample.rb
- app/serializers/user_serializer.rb
- app/views/pages/settings.haml
- config/routes.rb
- db/migrate/20161109141353_add_reaction_name_prefix_to_user.rb
- db/schema.rb
- spec/api/user_api_spec.rb
* store reaction letter prefix, default: R as before
* user is able to change the counter
* add edit user settings page
> Store reaction letter prefix

- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/ReactionDetailsScheme.js
- app/assets/javascripts/components/SampleDetails.js
* recalculate amount when amount type is target
* recalculate equivalent when amount type is real
* fix bug for target/real switch for reaction product
> Fix for update reaction material purity: recalculate amount_mmol

- app/assets/javascripts/components/ElementDetails.js
- app/assets/javascripts/components/Elements.js
- app/assets/javascripts/components/Material.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/SampleDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/WellplateDetails.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/common/ConfirmModal.js
- app/assets/javascripts/components/models/Element.js
- app/assets/javascripts/components/models/Reaction.js
- app/assets/javascripts/components/models/Screen.js
- app/assets/javascripts/components/models/Wellplate.js
- app/assets/javascripts/components/report/ReportContainer.js
- app/assets/javascripts/components/stores/ElementStore.js
- app/assets/javascripts/components/utils/ElementUtils.js
- app/assets/stylesheets/application.scss.erb
Since this is a big modification, I separate it to make things clear(hope so?).
> Multi details

- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/models/Reaction.js
Now the reaction SVG is not blinking when switching the collections.
Deployed to test server
> Fix ReactionDetails mutiple render

- app/api/api.rb
- app/api/chemotion/sample_api.rb
- app/api/chemotion/search_api.rb
- app/assets/javascripts/components/ElementAllCheckbox.js
- app/assets/javascripts/components/ElementsTable.js
- app/assets/javascripts/components/ElementsTableSampleEntries.js
- app/assets/javascripts/components/actions/ElementActions.js
- app/assets/javascripts/components/fetchers/SamplesFetcher.js
- app/assets/javascripts/components/fetchers/SearchFetcher.js
- app/assets/javascripts/components/stores/ElementStore.js
- Molecules are sorted by sum_formular
+ Alphabetical sort of the first character (mostly C - Carbon)
+ Natural sorting (normally: C1 -> C11 -> C2, natural sort: C1 -> C2 -> C11)
+ Add button to display samples belong to molecule (order by updated_at)
- Sorting also works with search feature
> Sort samples by molecule

- app/models/molecule.rb
- lib/pub_chem.rb
set pubchem connection to https
> import sdf: create mol even if unknown to Pubchem

- app/assets/javascripts/components/ElementsTable.js
- app/assets/javascripts/components/ElementsTableSampleEntries.js
Update CSS for molecule sort button
> Update CSS for Molecule Sort button

- app/api/api.rb
- app/api/chemotion/search_api.rb
- app/assets/javascripts/components/stores/ElementStore.js
- Fix paging bug while searching in both sort mode
> Paging with search

- app/api/chemotion/user_api.rb
- app/assets/javascripts/components/DragDropItemTypes.js
- app/assets/javascripts/components/ElementDetails.js
- app/assets/javascripts/components/List.js
- app/assets/javascripts/components/TabLayoutCell.js
- app/assets/javascripts/components/TabLayoutContainer.js
- app/assets/javascripts/components/actions/UIActions.js
- app/assets/javascripts/components/actions/UserActions.js
- app/assets/javascripts/components/contextActions/CreateButton.js
- app/assets/javascripts/components/contextActions/ModalExport.js
- app/assets/javascripts/components/fetchers/UsersFetcher.js
- app/assets/javascripts/components/routes.js
- app/assets/javascripts/components/stores/ElementStore.js
- app/assets/javascripts/components/stores/UIStore.js
- app/assets/javascripts/components/stores/UserStore.js
- app/assets/stylesheets/tab_layout_container.scss
- app/serializers/user_serializer.rb
- db/migrate/20161215133014_add_layout_to_users.rb
- db/schema.rb
- spec/api/user_api_spec.rb
- Add a button next to final tab to open tab layout
- Drag and drop to change tab order 
- Drag tab to "hidden area" to hide tab
- Change will be applied when exiting layout editor
- Tab layout is saved in user table
> User can now change tab layout

- app/assets/javascripts/components/List.js
- app/assets/javascripts/components/TabLayoutCell.js
- app/assets/javascripts/components/TabLayoutContainer.js
- app/assets/javascripts/components/stores/UserStore.js
- app/assets/javascripts/components/utils/ArrayUtils.js
- app/assets/stylesheets/tab_layout_container.scss
- Fix CSS error
- Current tab stay active after layout changing
> Tab dragging enhancement

- app/api/chemotion/research_plan_api.rb
- app/api/chemotion/screen_api.rb
- app/api/chemotion/wellplate_api.rb
- app/assets/javascripts/components/QuillEditor.js
- app/assets/javascripts/components/ReactionDetails.js
- app/assets/javascripts/components/ResearchPlanDetails.js
- app/assets/javascripts/components/ScreenDetails.js
- app/assets/javascripts/components/ScreenWellplates.js
- app/assets/javascripts/components/WellplateProperties.js
- app/assets/javascripts/components/models/ResearchPlan.js
- app/assets/javascripts/components/models/Screen.js
- app/assets/javascripts/components/models/Wellplate.js
- app/models/research_plan.rb
- app/models/screen.rb
- app/models/wellplate.rb
- db/migrate/20170103155405_update_screen_description_to_hash.rb
- db/migrate/20170103155423_update_research_plan_description_to_hash.rb
- db/migrate/20170104085233_update_wellplate_description_to_hash.rb
- db/schema.rb
- spec/api/research_plan_api_spec.rb
- spec/factories/research_plans.rb
- spec/factories/screens.rb
- spec/factories/wellplates.rb
- Add QuillEditor parameter: height, theme, and readOnly.
- Apply Quilljs formatting to Screen, Wellplate, and Research Plan description
- Adjust ScreenWellplate UI to fit with new description formatting
> Apply QuillJS to Screen, Wellplate, and Research Plan description

- app/assets/javascripts/components/contextActions/ReportButton.js
- app/assets/javascripts/components/report/ReportContainer.js
- app/assets/javascripts/components/stores/ElementStore.js
- app/assets/javascripts/components/stores/ReportStore.js
* keep selection of elements and collection when opening generate report container
* deselect elements on close reports generation view
* keep collection on close reports generation view
> User interface change for reports

- app/assets/stylesheets/common.scss
some suggestion of how to fix #502
> some fixes for #502

- app/api/chemotion/report_api.rb
- app/packs/src/components/actions/ReportActions.js
- app/packs/src/components/report/Paramize.js
Fixes 517 and linted touched files. Relevant changes:
`app/api/chemotion/report_api.rb` : only linting
`app/packs/src/components/report/Paramize.js` : actual fix, line 41
`app/packs/src/components/actions/ReportActions.js` needed some changes: class methods without `this` should be avoided, imports fixed.
> fixed #517

- scripts/install_development.sh
Reflect the migration to Rails 5 and the change of the default development branch in the `install_development.sh` script.
> adapt install_development.sh to Rails 5 environment

- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature.md
The already available "feature" template was improves and a new template for "enhancement" was introduced.
> New templates for issues

- CITATION.cff
Added a CITATION.cff file, see #522 for context.
> Added CITATION.cff file.

- spec/features/user_management_spec.rb
Adapted expected acceptance test output to changes introduced to `user.rb` in commit 0e5a0491573076b34b79ca88c34f6dadcdbf4552.
> Fixed failing acceptance test in `user_management_spec.rb`.

- spec/features/copy_reaction_spec.rb
- spec/features/sync_collection_spec.rb
- spec/features/user_management_spec.rb
> Attempt to fix flaky acceptance tests.

- app/api/chemotion/attachment_api.rb
- [] rather 1-story 1-commit than sub-atomic commits
- [] commit title is meaningful =>  git history search
- [] commit description is helpful => helps the reviewer to understand the changes
- [] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured
- [] added code is linted
- [] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited
- [] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing
- [] testing coverage improvement is more than welcome.
- [] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )
- [] …
> fix the bug for hyperlink export

- CHANGELOG.md
- app/packs/src/components/ViewSpectra.js
comment
1. add dataset selection, this is part of the metadata-converter-dataset project
2. linting
video
https://user-images.githubusercontent.com/42910431/169275881-e624a41b-243c-4f2b-86e1-6a54c7bd0e69.mp4
> 715-dataset-selection-in-chemspectra-viewer

- app/packs/src/components/GeneralProcedureDnD.js
CHANGELOG: Closes #646 - Link to open general procedure from parts of GP functionality added - see video for a demonstration.
https://user-images.githubusercontent.com/67055123/168545628-026ee9f1-830d-4b4e-8af5-6ba3403a384b.mp4
> Link functionality to open general procedure from parts of GP rxns

- app/packs/src/components/GroupElement.js
Changelog: Closes #720 - 'In "My Groups" tab, hover help is missing'
https://user-images.githubusercontent.com/67055123/170273263-94e7993b-6acd-486a-96f3-7974366e9bfe.mp4
> added tooltip to buttons in 'My Groups'

- .gitignore
- app/jobs/pubchem_single_lcss_job.rb
- app/models/molecule.rb
> Execute LCSS job when have new molecule

- CHANGELOG.md
- app/assets/stylesheets/overlay.scss
- app/packs/src/components/WellOverlay.js
- app/packs/src/components/fetchers/WellplatesFetcher.js
Issue 
https://user-images.githubusercontent.com/26220177/169071134-2f9d6e72-8823-47d3-9f58-7b9456a9bd8f.mp4
link:  https://github.com/ComPlat/chemotion_ELN/issues/669.
> Issue 669 wellplate scroll

- app/assets/stylesheets/overlay.scss
- app/packs/src/components/WellOverlay.js
https://github.com/ComPlat/chemotion_ELN/issues/797
> issue/  well details dropdown list behind readout entries

- app/packs/src/components/actions/InboxActions.js
- app/packs/src/components/inbox/AttachmentContainer.js
- app/packs/src/components/inbox/UnsortedBox.js
- app/packs/src/components/stores/InboxStore.js
- app/packs/src/components/utils/ArrayUtils.js
- [] testing coverage improvement is more than welcome.
- [] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )
- [] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release
> delete multiple inbox attachments at once

- app/models/concerns/attachment_jcamp_aasm.rb
> fixed generates duplicate images

- app/assets/stylesheets/format-container.scss
> not set max height in list class in modal

- app/packs/src/components/staticDropdownOptions/options.js
CHANGELOG: Closes #826 
Addition of dialysis and change of crystallisation -> recrystallisation in purification methods drop down. EDIT: Crystallisation re-
added as a separate option
> added recrystallisation and dialysis methods

- app/models/concerns/attachment_jcamp_aasm.rb
> refactoring create and edit jcamp data code

- app/packs/src/components/scifinder/ScifinderSearch.js
> replace logo with text

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/greater-code.md
- .github/ISSUE_TEMPLATE/installation-issue.md
- .github/workflows/testacceptance.yml
- .github/workflows/testjs.yml
- .github/workflows/testrb.yml
- .gitlab-ci.yml
- app/packs/src/models/Attachment.js
update CI image:
- node 14.20
- ruby 2.6.8 (default) 2.7.5 (use .tool-versions)
- built  from 98160166c 
also removed checkboxes from issue templates
> Ci image update

- app/api/chemotion/element_api.rb
- app/models/sample.rb
https://github.com/ComPlat/chemotion_ELN/issues/875
https://user-images.githubusercontent.com/26220177/184322140-bcd603dd-21ca-4ce9-8795-08e80fa42ffd.mp4
> fixes in UI element selection

- app/api/chemotion/element_api.rb
- app/api/chemotion/molecule_api.rb
- app/api/chemotion/sample_api.rb
- app/api/entities/container_entity.rb
- app/api/entities/molecule_entity.rb
- app/packs/src/components/report/SectionReaction.js
- app/packs/src/components/report/SectionSample.js
- app/packs/src/components/report/SectionSiSynthesis.js
- app/packs/src/components/report/SectionSiSynthesisStdRxn.js
- app/packs/src/fetchers/SamplesFetcher.js
- lib/reporter/docx/detail.rb
- lib/reporter/docx/detail_reaction.rb
- spec/api/chemotion/screen_api_spec.rb
- spec/features/copy_reaction_spec.rb
- spec/features/copy_sample_spec.rb
- spec/features/create_sample_spec.rb
- spec/features/share_collection_spec.rb
fix failed test case, using id from json result
skip tests that relate with level details
remove present by entity
> remove unnecessary json parse

- app/api/entities/container_entity.rb
The bug was introduced when refactoring the ContainerEntity.
Originally one instantiation of the container entity was used to display the whole container tree.
I considered this code to be really hard to understand, so I refactored it the way that every container
is serialized invididually.
This does not work for the preview image though, as the image file is attached to the dataset container,
while the frontend assumes it to be present on the parent analysis container.
This PR checks if a given container is of type 'analysis' and if so, fetches all eligible images
from the dataset children.
> Fix missing preview images for analyses

- README.md
Fixed link to installation instructions that has been added with #616.
> README: fixed link to installation instructions. Also, some minor style changes.

- .github/workflows/testrb.yml
- spec/api/delayed_job_api_spec.rb
- Increase timeout
- Fix the blinking delayed job api spec
> Fix github action timeout issue

- app/packs/src/apps/mydb/collections/CollectionTree.js
- app/packs/src/apps/mydb/collections/MyCollections.js
- spec/features/collection_management_spec.rb
- spec/features/copy_reaction_spec.rb
- spec/features/sync_collection_spec.rb
When working on the copy_reaction_spec we discovered some code that was better suited to be a proper test case for the collection management spec. This PR adds the test case in the right place and refactors some React components to make JS testing better readable
> Add collection update spec

- .gitignore
- app/api/chemotion/molecule_api.rb
- app/models/molecule.rb
- app/models/reaction.rb
- config/initializers/ketcher_service.rb
- config/ketcher_service.yml.example
- lib/ketcher_service/render_svg.rb
- lib/svg/processor.rb
Stuff to render molfiles on a [ketcher backend service](https://github.com/ptrxyz/chemotion-ketchersvc) as here.
> Ketcher service

- app/assets/stylesheets/common.scss
- app/packs/src/components/CollectionTree.js
- app/packs/src/components/inbox/AttachmentContainer.js
- app/packs/src/components/inbox/DatasetContainer.js
- app/packs/src/components/inbox/DeviceBox.js
- app/packs/src/components/inbox/InboxModal.js
- app/packs/src/components/inbox/UnsortedBox.js
CHANGELOG :  Closes https://github.com/ComPlat/chemotion_ELN/issues/498
> Font mismatch issue of the Inbox section is fixed

- lib/import/import_collections.rb
[894](https://github.com/ComPlat/chemotion_ELN/issues/894)
The following missing wellplate data issues solved for import collection for:
1. user abbreviation
2. description
3. sample/molecule data
4. color in well
5. readout values
> missing data for wellplate in import collection

- app/serializers/detail_levels/sample.rb
[896](https://github.com/ComPlat/chemotion_ELN/issues/896)
https://user-images.githubusercontent.com/26220177/189946390-0e83d745-2687-44e6-976e-cb13f98d48f6.mp4
> Adding a wellplate to a screen - missing description

- app/api/chemotion/profile_api.rb
- app/controllers/pages_controller.rb
- app/models/profile.rb
- app/packs/src/components/ElementsTableSampleEntries.js
- app/packs/src/components/ElementsTableSettings.js
- app/packs/src/components/models/Sample.js
- db/migrate/20220908132540_add_show_label_columns_in_profiles.rb
- db/schema.rb
[884](https://github.com/ComPlat/chemotion_ELN/issues/884)
- fix show external label issue
- add new checkboxes
> show external label issue

- .github/workflows/ci.yml
See https://github.com/actions/runner/issues/491.
> Run testing job if linting job was skipped

- app/packs/src/components/ContainerComponent.js
- app/packs/src/components/common/HyperLinksSection.js
> convert list hyperlinks to json

- lib/ketcher_service/render_svg.rb
> HTTPs support for render_svc (v1.4 backport)

- app/packs/src/apps/admin/UserManagement.js
CHANGELOG : Closes https://github.com/ComPlat/chemotion_ELN/issues/936
> [936] Wrong tooltip issue is fixed for deactivated users in admin panel in user management section

- app/packs/src/components/models/Reaction.js
- app/packs/src/components/models/ResearchPlan.js
> fix chemspectra cannot open in reaction and research plan for v1.4

- app/assets/stylesheets/common.scss
- app/packs/src/apps/mydb/collections/CollectionTree.js
- app/packs/src/apps/mydb/inbox/AttachmentContainer.js
- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- app/packs/src/apps/mydb/inbox/DeviceBox.js
- app/packs/src/apps/mydb/inbox/InboxModal.js
- app/packs/src/apps/mydb/inbox/UnsortedBox.js
CHANGELOG : Closes https://github.com/ComPlat/chemotion_ELN/issues/498
> [498] Font mismatch issue of the Inbox section is fixed

- app/packs/src/models/Element.js
- app/packs/src/models/Reaction.js
- app/packs/src/models/ResearchPlan.js
- app/packs/src/models/Sample.js
> fix cannot open chemspectra in research plan and reaction

- .service-dependencies
- CHANGELOG.md
> Update chemspectra backend version in CHANGELOG.md

- yarn.lock
Please make sure `yarn install` has been run and commit the changed yarn.lock file!
> Fix for outdated yarn.lock

- .gitignore
- app/api/chemotion/molecule_api.rb
- app/models/molecule.rb
- app/models/reaction.rb
- config/initializers/ketcher_service.rb
- config/ketcher_service.yml.example
- lib/ketcher_service/render_svg.rb
- lib/svg/processor.rb
Integration of ketcher backend service to generate ketcher1-styled sample SVG for sample created by smiles input
- fallback to openbabel if service not available
> Ketcher1 generated sample svg service

- app/api/chemotion/attachment_api.rb
- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersAux.js
- app/packs/src/fetchers/AttachmentFetcher.js
- app/packs/src/stores/alt/actions/SpectraActions.js
- app/packs/src/stores/alt/stores/SpectraStore.js
- app/packs/src/utilities/SpectraHelper.js
- lib/chemotion/jcamp.rb
> 811 make regerenate edit jdx file button for chem spectra

- app/models/concerns/reactable.rb
- app/models/reactions_sample.rb
- app/models/sample.rb
- app/packs/src/apps/mydb/elements/details/NumeralInputWithUnitsCompo.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
- app/packs/src/models/Reaction.js
- spec/features/reaction_coefficiency_spec.rb
replace PR https://github.com/ComPlat/chemotion_ELN/pull/685
port of the feature integrated in v1.4 with 14dd648cb and 798b80e07
resolved:
https://github.com/ComPlat/chemotion_ELN/issues/544
more discussion :
https://github.com/ComPlat/chemotion_ELN/issues/387
https://github.com/ComPlat/chemotion_ELN/issues/368
> add reaction coefficiency - port 

- db/seeds/development/devices.seed.rb
- lib/datacollector/datacollector_folder.rb
- lib/datacollector/foldercollector.rb
- The folder collector is fixed to collect files from sub-folders over sftp connection
- Code is refactored to properly delete the target folder
> Fixed the folder collector

- .service-dependencies
> update information of chemspectra to fix critical issue

- app/packs/src/components/Material.js
- app/packs/src/components/ReactionDetailsScheme.js
> fix bug for reaction coefficient feature

- .devcontainer/devcontainer.json
- .devcontainer/post_create.sh
- .devcontainer/pre_create.sh
These changes remove the necessity to carry our manual steps before starting the devcontainer.
> Initialize repository before running devcontainer

- config/webpack/custom.js
- config/webpack/development.js
- package.json
- yarn.lock
html2pdf.js@0.9.3 requires jspdf@1.4.1
> dependabot html2pdf version issue

- lib/export/export_excel.rb
- lib/import/import_samples.rb
- spec/lib/export/export_excel_spec.rb
- spec/lib/import/import_samples_spec.rb
> fix bugs for importing and exporting samples

- app/packs/src/apps/mydb/elements/details/samples/FastInput.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/utilities/CasValidation.js
- spec/javascripts/utils/CasValidation.spec.js
> fix cas bugs in sample field-enhance fast input

- app/models/concerns/attachment_jcamp_aasm.rb
- spec/factories/attachments.rb
> fix redundant files cannot be removed

- README.md
Updated some links to point to the new docu.
> Update README.MD to point to new docu

- lib/reporter/docx/detail.rb
- lib/reporter/docx/detail_reaction.rb
fix the issue with description and observation fields
> Modification in personalized units for generated reports

- app/api/helpers/report_helpers.rb
- app/packs/src/components/contextActions/ModalExport.js
> add cas number to export function

- .service-dependencies
> update version of chemspectra backend to handle Mass spectrum as BagIt

- package.json
- yarn.lock
> upgrade convert to 0.9

- app/assets/stylesheets/overlay.scss
- app/packs/src/apps/mydb/elements/details/wellplates/designerTab/WellOverlay.js
https://github.com/ComPlat/chemotion_ELN/issues/880
[Screencast from 23.02.2023 16:01:12.webm](https://user-images.githubusercontent.com/26220177/220946693-8bc6a09b-5f1b-4930-95e6-1e7d3561b223.webm)
> wellplate trash button issue

- app/api/entities/container_entity.rb
Fix for [937](https://github.com/ComPlat/chemotion_ELN/issues/937)
[Screencast from 24.02.2023 15:30:15.webm](https://user-images.githubusercontent.com/26220177/221204860-c94e2cc2-1d97-4bb7-9754-df3dde135c73.webm)
> Fix for missing sample analysis data

- app/packs/src/stores/alt/stores/SpectraStore.js
- yarn.lock
> fix the issue that chemspectra does not work at sometimes

- .github/workflows/ci.yml
- app/api/chemotion/ui_api.rb
- app/models/metadata.rb
- app/packs/src/components/contextActions/ExportImportButton.js
- app/packs/src/components/navigation/UserAuth.js
- spec/models/metadata_spec.rb
> converter config check

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
- app/packs/src/models/Reaction.js
- app/packs/src/stores/alt/actions/ElementActions.js
- app/packs/src/stores/alt/stores/ElementStore.js
> fix reaction coefficient bug

- app/packs/src/apps/mydb/elements/details/reports/SectionReaction.js
- app/packs/src/models/Element.js
Report function expecting  sample.analyses 
but this data is now only under sample.containers
> report: alias element.analyses

- app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
> researchplan fix missing import

- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleDetailsSolvents.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleDetailsSolventsDnd.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleSolventGroup.js
[1100](https://github.com/ComPlat/chemotion_ELN/issues/1100)
[Screencast from 06.03.2023 16:15:24.webm](https://user-images.githubusercontent.com/26220177/223151913-3fe571f5-c72f-4b8e-956e-bca9e7ad4baa.webm)
> issue solve for selection of a solvent in sample properties tab 

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/sample.scss
Checkbox is out of order [#953](https://github.com/ComPlat/chemotion_ELN/issues/953)
> checkbox out of order in menu bar

- app/packs/src/apps/mydb/elements/tabLayout/TabLayoutCell.js
- app/packs/src/apps/mydb/elements/tabLayout/TabLayoutContainer.js
> fix missing icons

- app/api/entities/attachment_entity.rb
- app/packs/src/components/container/ContainerDataset.js
- app/packs/src/models/Attachment.js
- app/packs/src/utilities/MathUtils.js
- db/schema.rb
- spec/api/chemotion/attachment_api_spec.rb
In analyses section, the file size is now being listed.
> List file size in dataset attachment upload modal in analyses section

- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldImage.js
remove listener from component that was triggering the  processing of  data unrelated to the component
( + some linting)
> Research plan image : remove listening  element store

- app/api/chemotion/ui_api.rb
> ui feature fix

- app/api/chemotion/public_api.rb
- app/assets/javascripts/affiliations.js
- app/controllers/pages_controller.rb
- app/views/devise/shared/_affiliations.html.haml
- config/initializers/assets.rb
fix missing autocomplete lib for signup/affiliations page
fix broken user affiliation page (rm remnants of gem swot calls )
TODO: use swot-node
> fix affiliation form 

- app/api/chemotion/research_plan_api.rb
- app/models/molecule.rb
- app/models/reaction.rb
- app/models/sample.rb
- app/uploaders/attachment_uploader.rb
- app/views/export/research_plan.haml
- lib/export/export_research_plan.rb
Fix of exporting a reasearch plan to docx sometimes not working [#902 ](https://github.com/ComPlat/chemotion_ELN/issues/902
[Screencast from 20.11.2022 12:56:42.webm](https://user-images.githubusercontent.com/26220177/203984625-47b01411-8b66-4960-9f14-5884715e9bf1.webm)
)
> export docx research plan error

- app/models/attachment.rb
- app/models/research_plan.rb
use Shrine  :exists?  to check if Thumbnail present
> Attachment: read thumbnail if it exists

- app/packs/src/apps/admin/textTemplates/TextTemplate.js
> pagination error in text template

- app/api/chemotion/public_api.rb
> provide entity fix

- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/models/Sample.js
> reset melting & boiling point for products on reaction copy

- app/packs/src/apps/home/Home.js
- app/packs/src/components/navigation/Navigation.js
- Hide the collection tree toggle button in the homepage
- Hide the navigation bar form in the homepage
CHANGELOG :  Closes https://github.com/ComPlat/chemotion_ELN/issues/926
> Refactor the homepage

- .service-dependencies
- app/api/chemotion/attachment_api.rb
- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
- app/packs/src/fetchers/AttachmentFetcher.js
- app/packs/src/stores/alt/actions/SpectraActions.js
- app/uploaders/attachment_uploader.rb
- lib/chemotion/jcamp.rb
> fix cannot save 2D data

- app/packs/src/apps/mydb/elements/details/reports/ReportContainer.js
> Add padding to report container

- app/packs/src/components/contextActions/InboxButton.js
> fix: fixed width of inbox icon #1207

- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
> fix cannot work with Bruker FID

- app/packs/src/stores/alt/stores/NotificationStore.js
CHANGELOG :  Closes https://github.com/ComPlat/chemotion_ELN/issues/1127
> Fix the issue of white screen on the homepage after login

- app/packs/src/components/navigation/search/SearchFilter.js
CHANGELOG: Fixes: #1200 
Adds exact search as the default search type for advanced searching.
https://user-images.githubusercontent.com/67055123/226898100-b01e414c-75c6-42b5-8005-b34d0fe0631a.mp4
> Set default search type value (EXACT)

- app/packs/src/apps/mydb/elements/details/reports/ReportContainer.js
Fixes #1205 
Added border with radius to report tabs, see https://github.com/ComPlat/chemotion_ELN/issues/1205#issuecomment-1481248918
> 1205 - add border

- public/welcome-message-sample.md
> Updated welcome message to point to new docs URL

- app/api/helpers/report_helpers.rb
> export wellplate samples error fix

- CHANGELOG.md
- VERSION
> prep v1.5.1

- app/models/concerns/attachment_jcamp_aasm.rb
- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersAux.js
- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
- spec/factories/attachments.rb
- spec/models/attachment_spec.rb
> fix cannot sync 1d data

- .service-dependencies
> update chem-spectra-app to version 0.11.2

- app/models/sample.rb
- spec/models/sample_spec.rb
- fix sample creation with invalid naming
- fix rubocop warnings
CHANGELOG :  Closes https://github.com/ComPlat/chemotion_ELN/issues/1204
> Fix the creation of sample with invalid label 'NEW SAMPLE'

- .service-dependencies
- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
> fix crash when open and save nmrium

- app/packs/src/components/staticDropdownOptions/options.js
add Precipitation as the new purification method in the Scheme tab for reactions
Closes https://github.com/ComPlat/chemotion_ELN/issues/1117
> New purification method of Precipitation

- app/packs/src/fetchers/BaseFetcher.js
- app/packs/src/fetchers/WellplatesFetcher.js
- app/packs/src/models/Wellplate.js
- re-fetch  element after image annotation update to return the correct object for action dispatch
> 1289 saving wellplate causes white screen

- app/api/entities/computed_prop_entity.rb
- app/api/entities/sample_entity.rb
- app/assets/stylesheets/application.scss.erb
- spec/api/entities/computed_prop_entity_spec.rb
- spec/api/entities/wellplate_entity_spec.rb
- spec/factories/computed_props.rb
> show results from calculations

- app/models/scan_result.rb
Fixes an issue with the chemobile app, where double scans could not be successfully completed.
> Fix scan result calculation bug

- app/api/chemotion/sample_api.rb
- lib/import/import_samples.rb
- lib/import/import_sdf.rb
> add cas as option in import samples to collection function

- app/api/chemotion/chem_spectra_api.rb
- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
> fixed cannot load the correct url of nmrium wrapper

- app/api/chemotion/share_collection_api.rb
- app/api/entities/collection_acl_entity.rb
- app/packs/src/apps/mydb/collections/CollectionSubtree.js
- app/packs/src/models/Collection.js
- app/policies/collection_acl_policy.rb
- app/usecases/sharing/take_ownership.rb
Description:
- Pass ownership of collection from User A to User B
- Pass ownership button visible to User B
- On accepting swap user rights
- On removing rights delete all collection info from user solving [1058](https://github.com/ComPlat/chemotion_ELN/issues/1058 )
> refactor transfer of ownership

- .service-dependencies
- app/models/concerns/attachment_jcamp_aasm.rb
- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- lib/chemotion/jcamp.rb
- yarn.lock
> add chemspectra with aif layout

- app/assets/stylesheets/spectra.scss
> fix zoom on firefox

- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
> fix crash when saving data from NMRium

- app/models/calendar_entry.rb
- spec/api/report_template_api_spec.rb
- spec/factories/admins.rb
- spec/factories/groups.rb
- spec/factories/persons.rb
- spec/factories/users.rb
- spec/jobs/send_calendar_entry_notification_job_spec.rb
- spec/usecases/calendar_entries/create_spec.rb
- spec/usecases/calendar_entries/update_spec.rb
fix calendar entry test:
the sharing event that have no event-able is not expected
> Calendar entry: fix flaky test

- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
> defer reload after saving data

- app/packs/src/models/ResearchPlan.js
> Text editor in researchPlan is now getting removed properly

- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsAddField.js
> added cypress complaint attributes

- app/api/chemotion/admin_api.rb
- app/packs/src/apps/admin/GroupsDevices.js
- spec/api/chemotion/admin_api_spec.rb
use UserSimpleEntity
fix autocomplete user selection not displaying the result when admin search for a user
resolve https://github.com/ComPlat/chemotion_ELN/issues/1360
> get user by name for AdminUI

- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
Two comment headers visible in uncharted branch.
> Remove duplicate component in ResearchPlanDetails.js

- app/packs/src/components/calendar/Calendar.js
- app/packs/src/components/calendar/CalendarEntryEditor.js
The dates formats for the different tabs in the calendar feature have been updated so they are consistent (i.e. ddd DD MMMM YYYY).
> Dates in calendar feature re-formatted 

- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersCom.js
- app/packs/src/components/contextActions/InboxButton.js
- app/packs/src/components/contextActions/NoticeButton.js
- formatted code and fixed some lint problems
- unified badge style
- removed double "add analysis"  button
Fixes https://github.com/ComPlat/chemotion/issues/14
> Analysis button bounds & badge styles

- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
Fixes https://github.com/ComPlat/chemotion/issues/22
- Setting molfile textbox minimum size.
- Locking resizing to vertical only
> molfile textbox fix

- app/api/entities/collection_sync_entity.rb
- app/assets/stylesheets/tab_layout_container.scss
- app/packs/src/apps/mydb/collections/CollectionTabs.js
- app/packs/src/apps/mydb/elements/details/ElementDetailSortTab.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/tabLayout/TabLayoutCell.js
- app/packs/src/apps/mydb/elements/tabLayout/TabLayoutContainer.js
- app/packs/src/utilities/selectHelper.js
- app/packs/src/utilities/textHelper.js
- spec/javascripts/utils/textHelper.spec.js
- Solve issue on sync collection tab selection
- UI Fix for
before:
after:
> Sync collection tab segments fix

- app/packs/src/apps/mydb/inbox/UnsortedBox.js
- app/packs/src/stores/alt/actions/InboxActions.js
- app/packs/src/stores/alt/stores/InboxStore.js
> Fix inbox (de)select boxes

- app/api/chemotion/private_note_api.rb
- app/packs/src/fetchers/PrivateNoteFetcher.js
- spec/api/private_note_api.spec.rb
refactor the private_note_api.rb
refactor the PrivateNoteFetcher.js
refactor the private_note_api.spec.rb
> Refactor the private note api

- app/api/chemotion/generic_element_api.rb
- app/api/chemotion/research_plan_api.rb
- app/api/chemotion/screen_api.rb
- app/api/chemotion/wellplate_api.rb
- app/api/entities/element_entity.rb
- app/api/entities/research_plan_entity.rb
- app/api/entities/screen_entity.rb
- app/api/entities/wellplate_entity.rb
- app/api/helpers/comment_helpers.rb
- app/packs/src/apps/mydb/collections/CollectionTabs.js
- app/packs/src/apps/mydb/collections/CollectionTree.js
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/screens/ScreenDetails.js
- app/packs/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
- app/packs/src/apps/mydb/elements/labels/ElementCollectionLabels.js
- app/packs/src/apps/mydb/elements/list/ElementsList.js
- app/packs/src/components/common/SharedByIcon.js
- app/packs/src/components/generic/GenericElDetails.js
- app/packs/src/models/Screen.js
- app/packs/src/models/Wellplate.js
Added/solved:
- remove sync collection from wellplate_api
- remove sync collection from screen_api
- modify readOnly collection research plan (solves [1369](https://github.com/ComPlat/chemotion_ELN/issues/1369))
- modify readOnly collection Generic Elements (solves [1401](https://github.com/ComPlat/chemotion_ELN/issues/1401))
- onClick error page on Shared Icon
- remove sync collection logic for comment functionality (authorized_users method)
To-Do:
- add collection seed
- remove sync collection logic for comment functionality (notification methods)
- navigation issues
- attachment API error on research plan shared collection
> Refactor shared elements

- app/assets/stylesheets/collection_management.scss
- app/packs/src/apps/mydb/collections/CollectionTabs.js
> Edit icon in collection tabs

- app/packs/src/apps/mydb/elements/details/ElementDetailSortTab.js
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/utilities/CollectionTabsHelper.js
- filter null values in hidden tab list
> Fix for tab options

- app/assets/stylesheets/components/CommentButton/CommentButton.scss
- app/models/comment.rb
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/list/ElementsTable.js
- app/packs/src/apps/mydb/elements/list/ElementsTableGroupedEntries.js
- app/packs/src/components/comments/HeaderCommentSection.js
* Fix the CSS for header comment buttons to keep them together on smaller screens
* Fix the display of the comment count in the reactions' list
> Comment functionality fixes

- .service-dependencies
> upgrade converter 1.0.0

- config/initializers/delayed_job_config.rb
> disable_chemrepoidjob

- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersCom.js
Fixes https://github.com/ComPlat/chemotion_ELN/issues/1459
- Top row is now with fixed position.
- No double buttons, but add analysis button will be always visible
> Enhance: Add analysis button

- .service-dependencies
- app/packs/src/utilities/quillToolbarSymbol.js
> add fluorescence (emission), DLS ACF, DLS Intensity layouts

- app/packs/src/apps/mydb/elements/details/PrivateNoteElement.js
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldReaction.js
- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldSample.js
- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsName.js
- app/packs/src/apps/mydb/elements/list/ElementsTableEntries.js
Fixes https://github.com/ComPlat/chemotion_ELN/issues/1382
- Added UI error message to appear when backend fetching fails
- Modified UI (Added Edit button to be part of the research plan instead of own line, and other small things)
Before:
After:
> White screen research plan

- app/packs/src/apps/mydb/elements/details/wellplates/designerTab/WellOverlay.js
Fixes https://github.com/ComPlat/chemotion_ELN/issues/1473
- eslint fixes
- adding scroll bar for the popover content to prevent it getting out of bounds
> fix: wellplates multiple readouts design tab

- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersAux.js
- app/packs/src/utilities/SpectraHelper.js
- spec/javascripts/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersAux.spec.js
- spec/javascripts/packs/src/utilities/SpectraHelper.spec.js
> fixed: nmrium button

- .service-dependencies
> chore: update information of chem-spectra-app

- app/api/chemotion/inbox_api.rb
- app/assets/stylesheets/components/inbox/inbox.scss
- app/packs/src/apps/mydb/collections/CollectionTree.js
- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- app/packs/src/apps/mydb/inbox/InboxModal.js
- app/packs/src/apps/mydb/inbox/UnsortedBox.js
- app/packs/src/apps/mydb/inbox/UnsortedDataset.js
- app/packs/src/fetchers/InboxFetcher.js
- app/packs/src/stores/alt/actions/InboxActions.js
- app/packs/src/stores/alt/stores/InboxStore.js
- app/packs/src/stores/alt/stores/LoadingStore.js
- app/services/inbox_service.rb
* fix the issue with attachment deletion in UnsortedBox.js
* fix the UnsortedBox section closing on file upload
* Add "Show more" button in the inbox in collection tree
* Add draggable cursor icon for the inbox header
> fix: inbox UnsortedBox issues

- app/api/chemotion/literature_api.rb
- app/packs/src/apps/mydb/elements/details/literature/DetailsTabLiteratures.js
- app/packs/src/fetchers/LiteraturesFetcher.js
- spec/api/literature_api_spec.rb
This PR solves issue https://github.com/ComPlat/chemotion_ELN/issues/1497. 
The problem was an empty response body which was tried to transform to JSON format. I changed the literature API, so it will return now an status code and fixed the Fetcher that it reacts to the status code and only tries to convert the body to JSON if there is another status code than 200.
I also added a UI feedback in form of a pop up if the literal was successfully removed.
There was one accidentally commit https://github.com/ComPlat/chemotion_ELN/pull/1502/commits/9e390a982441a5aa4b198ff4ef5c3114404e04b1, but i reverted it with https://github.com/ComPlat/chemotion_ELN/pull/1502/commits/4002688acd786fe5dada15f38925209c9ecd03a5, so just ignore it.
> 1497 delete of literature not working

- app/packs/src/stores/alt/stores/SpectraStore.js
> fix: ignore predictions when it is null

- .service-dependencies
- app/models/concerns/attachment_jcamp_aasm.rb
> Update Chemspectra to dandle 'FL Spectrum' datatype and fix cannot read processed Bruker data NMR

- app/packs/src/apps/mydb/inbox/AttachmentContainer.js
- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- app/packs/src/apps/mydb/inbox/DeviceBox.js
- app/packs/src/stores/alt/actions/InboxActions.js
- app/packs/src/stores/alt/stores/InboxStore.js
- Fixed the attachments checkboxes not updating when clicked issue. 
[device_checkbox_not_working.webm](https://github.com/ComPlat/chemotion_ELN/assets/112618970/1d03c95a-c8df-4167-bc05-83f5d33d7ab0)
- Added a select all datasets checkbox. 
[checkboxes_fixed_and_select_all_feat.webm](https://github.com/ComPlat/chemotion_ELN/assets/112618970/c3cf42f0-dde5-40cc-b483-acd795c70334)
> Add select all option for device inbox folder

- Dockerfile.chemotion-dev
- Dockerfile.github-ci
@PiTrem, as discussed, I added the Cypress dependencies to the Dev and CI Dockerfiles.
I've also updated the CI's base image to the current production image.
> Add Cypress dependencies to Dockerfiles

- app/packs/src/apps/admin/AdminNavigation.js
- app/packs/src/apps/commandAndControl/Navigation.js
- app/packs/src/components/navigation/NavHead.js
- update links (added docu, removed kit/complat)
- DRY
- also added external-link icon to make clear the link is leaving the current domain.
> feat: update ext links in the Navbar menu dropdown

- app/packs/src/apps/admin/UserManagement.js
Closes https://github.com/ComPlat/chemotion_ELN/issues/1492
- Eslint fixes (in a separate commit)
- Users in the Admin UI under User Management can now be filtered (name-abbreviation-type-active?-locked?)
> Feat: filter options for admin user management

- app/packs/src/fetchers/BaseFetcher.js
see [#1523](https://github.com/ComPlat/chemotion_ELN/pull/1523/files#diff-638dffcf82730485c30433cdb41b41966ec25084823f9524df840622945657a6L49)
> fix: wrong conflict resolution

- .service-dependencies
> chore: update chemspectra backend version to display label cv layout

- app/models/molecule.rb
- lib/pub_chem.rb
> Fix load cas for molecules

- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- app/packs/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.js
- app/packs/src/apps/mydb/elements/details/researchPlans/analysesTab/ResearchPlanDetailsContainers.js
- spec/javascripts/packs/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.spec.js
- spec/javascripts/packs/src/apps/mydb/elements/details/researchPlans/analysesTab/ResearchPlanDetailsContainers.spec.js
- spec/javascripts/packs/src/utilities/SpectraHelper.spec.js
> feat: add-nmrium-button-for-reaction-and-researchplan

- README.md
- db/seeds/shared/admin.seed.rb
fix: README links to docs (trailing '/' routing)
> fix: Admin seed: ensure exisiting Admins have a profile

- lib/import/import_samples.rb
> fix: assign only boolean values for decoupled column in import samples

- app/packs/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.js
- app/packs/src/apps/mydb/elements/details/researchPlans/analysesTab/ResearchPlanDetailsContainers.js
- app/packs/src/components/generic/EditorAnalysisBtn.js
- app/packs/src/components/generic/GenericContainer.js
> fix: disable spectra button when just uploading an image

- Gemfile
- Gemfile.lock
- app/packs/src/apps/converter/ConverterAdmin.js
- package.json
- yarn.lock
> converter doc and fix

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
> Fix: reaction calculation when no reference material present

- app/packs/src/apps/mydb/elements/list/ElementsTableEntries.js
fix shared collection display issue
> fix: reaction list display break when reaction status not standard

- .github/workflows/ci.yml
- .gitignore
- .tool-versions
- CHANGELOG.md
- Dockerfile.github-ci
- VERSION
- package.json
> Prep v1.8.0

- app/packs/src/apps/mydb/collections/CollectionTree.js
Remove the inbox section from the side panel of collection tree to eliminate redundant occurrence of the section
> feat(UI): remove the inbox section from the side panel

- app/packs/src/components/container/ContainerDataset.js
bring back the changes from https://github.com/ComPlat/chemotion_ELN/pull/1085 to list the file size in the analyses tab
> feat(UI): file size is listed in the analyses tab

- app/api/chemotion/reaction_api.rb
- app/packs/src/apps/mydb/elements/list/ElementsTable.js
- app/packs/src/fetchers/BaseFetcher.js
- app/packs/src/stores/alt/stores/ElementStore.js
- add the option to sort reaction list by updated time
- add the option to toggle the sort direction
> feat: add the option to sort reaction list by updated time

- app/packs/src/components/common/SvgWithPopover.js
- package.json
- yarn.lock
> fix: bead not visible in preview and reaction details

- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- app/packs/src/utilities/quillToolbarSymbol.js
- package.json
Upgrade react-spectra-editor from v1.0.0-rc18 to v1.0.0-rc19.
Peaks from XRD are reported in the following format:
> feat: report peaks from XRD

- .service-dependencies
> fix: update nmrglue to read some bruker file issue

- app/api/chemotion/ui_api.rb
- app/packs/src/apps/mydb/inbox/InboxModal.js
> feat: display mail collector address

- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- Solves the deletion issue reported in https://github.com/ComPlat/chemotion_ELN/issues/1606
> fix: the attachment does not get deleted from the inbox when it is assigned to sample

- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- yarn.lock
> fix: remove blank line when saving peak

- app/models/molecule.rb
- lib/import/import_samples.rb
- spec/lib/import/import_samples_spec.rb
- spec/spec_helper.rb
> fix: allow import of molecule_name on sample import for xslx format

- app/assets/stylesheets/chemical-tab.scss
- app/packs/src/apps/mydb/elements/details/NumericInputUnit.js
- app/packs/src/components/ChemicalTab.js
- lib/chemotion/chemicals_service.rb
- spec/javascripts/utils/NumericInputUnit.spec.js
> add volume field in inventory tab

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/elements_details.css
- app/packs/src/apps/mydb/inbox/AttachmentContainer.js
- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- app/packs/src/apps/mydb/inbox/InboxModal.js
- app/packs/src/stores/alt/actions/InboxActions.js
- app/packs/src/stores/alt/stores/InboxStore.js
- The inbox can be resized by the user in three sizes, Small, Medium, Large
- The default is the 'Medium'
- When inbox size is selected as 'Small', the DateTime is hidden
Closes https://github.com/ComPlat/chemotion_ELN/issues/1606
> feat: add the option to change the inbox sizing

- app/api/entities/attachment_entity.rb
- app/packs/src/apps/mydb/elements/details/reports/SectionSpectrum.js
- lib/reporter/spectrum/detail.rb
- lib/reporter/worker_spectrum.rb
- spec/api/chemotion/attachment_api_spec.rb
- fix for [1642](https://github.com/ComPlat/chemotion_ELN/issues/1642)
- fix thumbnail image not displaying in Preview tab
> spectra report generation error fix

- app/assets/stylesheets/elements_table.scss
- app/assets/stylesheets/sample.scss
- app/packs/src/apps/mydb/elements/details/ElementDetails.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/list/ElementsList.js
- app/packs/src/apps/mydb/elements/list/ElementsTable.js
- app/packs/src/models/Sample.js
Fixes: #1646 
- Eslint fixes
- Molecule title spacing
- Element header responsiveness (See attached)
> Fix: molecule title layout and element table header responsiveness

- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
- app/packs/src/utilities/SpectraHelper.js
- spec/javascripts/packs/src/utilities/SpectraHelper.spec.js
> fix: remove original data in nmrium file

- lib/export/export_collections.rb
- lib/import/import_collections.rb
Closes https://github.com/ComPlat/chemotion_ELN/issues/1662
- attached research_plans in screens not being imported from collection
- wellplates not being imported from collection
> fix: attached research_plans in screens not being imported from collection

- spec/api/chemotion/search_api_spec.rb
Fixed tests of cell line search after the merge between advanced search feature branch and the cell line branch.
> fix tests for searching cell lines

- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
In sample details header removed duplicate user label and centering share button
> fix: remove duplicate user label and centering share button

- .github/workflows/ci.yml
- .gitignore
- CHANGELOG.md
- db/schema.rb
- spec/api/chemotion/ui_api_spec.rb
- spec/lib/chemotion/jcamp_spec.rb
- yarn.lock
> chore: update runner - fix text

- app/assets/stylesheets/attachment-list.scss
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
- app/packs/src/apps/mydb/elements/details/wellplates/attachmentsTab/WellplateDetailsAttachments.js
- app/packs/src/apps/mydb/elements/list/AttachmentList.js
- app/packs/src/components/common/HyperLinksSection.js
- app/packs/src/components/common/ImageModal.js
- app/packs/src/components/container/ContainerDatasetField.js
- app/packs/src/components/container/ContainerDatasetModal.js
- app/packs/src/components/container/ContainerDatasetModalContent.js
- app/packs/src/components/container/ContainerDatasets.js
- app/packs/src/models/Attachment.js
> Feat: analysis attachment groups

- app/packs/src/apps/mydb/elements/labels/ElementCollectionLabels.js
- app/packs/src/apps/mydb/elements/list/ElementsTableSampleEntries.js
- app/packs/src/components/UserLabels.js
- Eslint fixes
- Alignment
Before:
After:
> fix: sample entry label alignment

- app/api/chemotion/user_api.rb
- app/packs/src/apps/commandAndControl/CnC.js
Closes https://github.com/ComPlat/chemotion/issues/106
> feat: sort the device list by name in command_n_control

- app/api/helpers/container_helpers.rb
- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainers.js
- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersCom.js
> feat: analysis comment button and box for analysis tab

- Gemfile
- Gemfile.lock
- app/models/concerns/attachment_jcamp_aasm.rb
> feat: jdx reader

- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/TextRangeWithAddon.js
> fix: focus lost on input bug for melting & boiling points fields

- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
fixed missing 'close with save' button.
> fix: nmrium button in research plan

- app/packs/src/components/navigation/NavHead.js
PR for [1112](https://github.com/ComPlat/chemotion_ELN/issues/1112)
> feat: add helpdesk link in header

- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
Three minor UI changes (one change per commit) based on user feedback.
> fix(UI): cosmetic update of reaction-variations table

- app/models/concerns/attachment_jcamp_aasm.rb
Closes https://github.com/ComPlat/chemotion/issues/126
> fix: nmr prediction freezes

- app/api/chemotion/screen_api.rb
- app/models/reaction.rb
- app/models/research_plan.rb
- app/models/wellplate.rb
- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/screens/ScreenDetails.js
- app/packs/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
fix: avoid loading the comments if the user does not have UI permission for comments
fix bullet eager loading warnings
> fix: avoid loading the comments if the user does not have UI permission for comments

- lib/reporter/worker_spectrum.rb
Fix for [1735](https://github.com/ComPlat/chemotion_ELN/issues/1735)
[Screencast from 26.02.2024 11:30:47.webm](https://github.com/ComPlat/chemotion_ELN/assets/26220177/de39280a-c949-466d-a7fc-40d35bef0010)
> fix: si spectra report generation for reaction with multiple products

- app/api/entities/attachment_entity.rb
- app/api/entities/attachment_report_entity.rb
- app/api/entities/container_report_entity.rb
- app/api/entities/report_template_entity.rb
- app/api/entities/sample_report_entity.rb
- app/packs/src/apps/mydb/elements/details/reports/ReportContainer.js
- app/packs/src/apps/mydb/elements/details/reports/SectionSpectrum.js
- app/packs/src/stores/alt/actions/ReportActions.js
- app/packs/src/stores/alt/stores/LoadingStore.js
- app/packs/src/stores/alt/stores/ReportStore.js
- spec/api/chemotion/attachment_api_spec.rb
- fix thumbnail load issue in Preview page
- fix typos
> fix: thumbnail load issue in Preview page

- app/api/helpers/report_helpers.rb
- app/packs/src/components/ChemicalTab.js
- lib/import/import_samples.rb
> allow import of sample external label on sample import

- .service-dependencies
- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
> Fix wrong combined image for CV layout and missing predicted file for MS layout

- app/packs/src/stores/alt/stores/SpectraStore.js
> refactor: display the latest edited file on chemspectra

- .service-dependencies
- app/packs/src/components/common/SpectraEditorButton.js
> fix: display jcamp in nmrium

- app/assets/stylesheets/sample.scss
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/labels/ElementAnalysesLabels.js
- app/packs/src/apps/mydb/elements/labels/ElementReactionLabels.js
- app/packs/src/components/ChemicalTab.js
- app/packs/src/components/common/CopyElementModal.js
- app/packs/src/models/Chemical.js
- app/packs/src/models/Element.js
- spec/javascripts/factories/ChemicalFactory.js
- spec/javascripts/packs/src/components/ChemicalTab.spec.js
- spec/javascripts/packs/src/models/Chemical.spec.js
> Save button for chemical inventory in sample header

- app/packs/src/components/ChemicalTab.js
- lib/chemotion/chemicals_service.rb
- lib/import/import_chemicals.rb
- spec/lib/chemotion/chemicals_service_spec.rb
- [] rather 1-story 1-commit than sub-atomic commits
> fix: safety sheets are not imported and significantly slow down the import

- app/api/chemotion/research_plan_api.rb
- app/api/entities/application_entity.rb
- app/api/entities/reaction_entity.rb
- app/api/entities/research_plan_entity.rb
- app/api/entities/sample_entity.rb
- app/models/attachment.rb
- app/models/research_plan.rb
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsName.js
- app/packs/src/components/common/CopyElementModal.js
- app/packs/src/models/Attachment.js
- app/packs/src/models/ResearchPlan.js
- app/packs/src/stores/alt/actions/ElementActions.js
- app/packs/src/stores/alt/stores/ElementStore.js
- app/packs/src/utilities/routesUtils.js
- app/usecases/attachments/annotation/annotation_loader.rb
- app/usecases/attachments/annotation/annotation_updater.rb
- app/usecases/attachments/copy.rb
- lib/import/import_collections.rb
- spec/features/copy_research_plan_spec.rb
Feature for [1615](https://github.com/ComPlat/chemotion_ELN/issues/1615)
> feat: Copy research plan 

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/packs/src/components/staticDropdownOptions/options.js
- app/packs/src/models/Reaction.js
- lib/chemotion/sample_const.rb
Fix for [1825](https://github.com/ComPlat/chemotion_ELN/issues/1825)
> fix: incorrect calculation of volume ratio for purification solvents of reactions

- app/packs/src/components/container/ContainerComponent.js
Fix for [1758](https://github.com/ComPlat/chemotion_ELN/issues/1758)
> fix: analysis name issue

- app/packs/src/components/common/SpectraEditorButton.js
> fix: NMRium button disabled on 2D NMR

- app/assets/stylesheets/attachment-list.scss
- app/packs/src/apps/mydb/elements/list/AttachmentList.js
- app/packs/src/components/common/ImageModal.js
- app/packs/src/components/container/ContainerDatasetModal.js
- app/packs/src/components/container/ContainerDatasetModalContent.js
~~https://github.com/ComPlat/chemotion/issues/141~~
- Feature to show a warning when instrument is not added
- Thumbnails do not overlap anymore
> fix(UI): Attachment list

- app/packs/src/apps/admin/DataCollector.js
- lib/datacollector/fcollector.rb
- option to set the sftp port on the host input field eg: remote.adresse:2222
- update place-holder on inputfield
> feat: datacollector device config sftp port

- app/assets/stylesheets/search_results.scss
- app/packs/src/components/searchModal/forms/KetcherRailsForm.js
- app/packs/src/components/searchModal/forms/SearchResult.js
- app/packs/src/components/searchModal/forms/SearchResultTabContent.js
- app/packs/src/components/searchModal/forms/TextSearch.js
- app/packs/src/stores/mobx/SearchStore.jsx
* Fix for loading structure in search modal
* Add more information of sample in search result
* Add linked element in search result
> Fixes for search

- app/packs/src/components/common/ImageModal.js
- package_postinstall.sh
(introduced in v1.9.0)
also src pdfworker locally
> fix: viewing of pdf in analysis preview

- Gemfile
- Gemfile.lock
update rinchi gem due to broken installation (https://github.com/ComPlat/rinchi-gem/pull/1)
> fix: broken gem rinchi

- app/api/chemotion/profile_api.rb
issue introduced thru overzealous-late-last-minute rubocoping in #1702 - 
https://github.com/ComPlat/chemotion_ELN/pull/1702/commits/d3def7ff16343e5e92df0cbb8a07c4e486542787
> fixup: profile_api

- app/models/concerns/attachment_jcamp_aasm.rb
> fix: remove redundant json file in CV layout

- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.js
- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.js
- app/packs/src/apps/mydb/elements/list/ElementsTableEntries.js
- app/packs/src/models/Reaction.js
- spec/javascripts/factories/SampleFactory.js
- spec/javascripts/helper/reactionVariationsHelpers.js
- spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.spec.js
- spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.spec.js
> Reaction variations refactoring

- db/migrate/20240625105013_update_reaction_variations.rb
- db/schema.rb
This PR addresses https://github.com/ComPlat/chemotion/issues/173.
> refactor: reaction variations table db migration

- app/assets/stylesheets/chemotion_bootstrap.scss
- app/packs/src/apps/generic/GenericAdminNav.js
- app/packs/src/apps/generic/GenericDatasetsAdmin.js
- app/packs/src/apps/generic/GenericElementsAdmin.js
- app/packs/src/apps/generic/GenericSegmentsAdmin.js
- app/packs/src/apps/generic/SyncButton.js
- app/packs/src/apps/generic/Utils.js
Fix navigation of generic designer
> Fix generic designer

- app/api/api.rb
- app/api/chemotion/third_party_app_api.rb
- spec/api/chemotion/third_party_app_api_spec.rb
- spec/factories/third_party_apps.rb
- spec/models/label_info_spec.rb
In this PR the issue that no **thumbnail** was generated after the third party app uploads the new attachment is fixed. Also all the tests in the third_party_app file were repaired and refactored.
> 3PA - Fixed thumbnail and tests

- app/models/admin.rb
- app/models/attachment.rb
- app/models/collection.rb
- app/models/collections_cellline.rb
- app/models/collections_research_plan.rb
- app/models/container.rb
- app/models/device.rb
- app/models/group.rb
- app/models/inventory.rb
- app/models/person.rb
- app/models/reaction.rb
- app/models/report.rb
- app/models/research_plans_screen.rb
- app/models/research_plans_wellplate.rb
- app/models/scan_result.rb
- app/models/screen.rb
- app/models/vessel.rb
- app/models/vessel_template.rb
- app/models/wellplate.rb
- db/migrate/20240709095242_rm_dup_collections_cellline.rb
- db/migrate/20240709095243_add_index_to_collections_cellline.rb
- db/schema.rb
- spec/db/migrate/20240709095242_rm_dup_collections_cellline_spec.rb
- db schema on postgres 14
- rake annotate_models
- added indices on collections_cellines
> chore: update db schema - model annotations

- app/api/api.rb
- app/api/chemotion/admin_api.rb
- app/api/chemotion/text_template_api.rb
- app/jobs/admin_job.rb
- app/models/collection.rb
- app/models/profile.rb
- app/models/text_template.rb
- app/models/user.rb
- db/seeds/shared/admin.seed.rb
- db/seeds/shared/collections.seed.rb
- prevent altering locked collection
- introduce an API-endpoint for admin to restore locked collections
also 
- refactor: user.profile so that profile always exist
- refactor: user.text_templates so that text templates always
> fix: restore missing locked collection

- app/packs/src/apps/mydb/elements/details/NumeralInputWithUnitsCompo.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialCalculations.js
> fix: Restrict enabling disabled fields on double click

- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- app/packs/src/utilities/SpectraHelper.js
- spec/javascripts/packs/src/utilities/SpectraHelper.spec.js
> feat: generate inline anotation for cyclic voltammetry layout

- .github/workflows/asset-precompilation.yml
- .github/workflows/ci.yml
- config/database.yml.ci
- config/database.yml.travis
- package_postinstall.sh
- sed lines with undefined operation: wrap * operation within min() in calc()
- sed lines transform any min() to Min()
- provide github-action workflow with manual trigger to test production assets compilation
- also update github-action checkout to v4
> fix: sassc undefined operation on compiling ag-grid scss

- app/api/chemotion/admin_device_api.rb
- app/api/chemotion/admin_device_metadata_api.rb
- app/api/helpers/admin_helpers.rb
- db/migrate/20240115163018_migrate_datacollector_and_novnc_fields.rb
- spec/api/chemotion/admin_device_api_spec.rb
allow testing sftp connection when port is given after #1885
resolve #2048
> fix(admin): datacollector connection sftp check when port given

- .service-dependencies
> fix(spectra): update chemspectra with fixed version of nmrglue

- app/assets/stylesheets/collection_tree.scss
- app/assets/stylesheets/elements_table.scss
- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
- app/packs/src/apps/mydb/elements/labels/ElementCollectionLabels.js
- app/packs/src/apps/mydb/elements/labels/ElementResearchPlanLabels.js
- app/packs/src/apps/mydb/inbox/AttachmentContainer.js
- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- app/packs/src/apps/mydb/inbox/DeviceBox.js
- app/packs/src/apps/mydb/inbox/InboxModal.js
- app/packs/src/apps/mydb/inbox/MoveToAnalysisButton.js
- app/packs/src/apps/mydb/inbox/UnsortedBox.js
- app/packs/src/apps/mydb/inbox/UnsortedDataset.js
- app/packs/src/apps/mydb/inbox/UnsortedDatasetModal.js
- app/packs/src/components/comments/CommentButton.js
- app/packs/src/components/comments/CommentList.js
- app/packs/src/components/comments/HeaderCommentSection.js
This PR includes refactoring of the following components:
-  all mydb/inbox components to latest react-bootstrap.
- refactoring CommentList and CommentButton to latest react bootstrap.
(Other comments-components are either already done/ nothing to be changed)
- mydb/elements/labels/ElementCollectionLabels.js
- mydb/elements/labels/ElementResearchPlanLabels.js
> Update bootstrap inbox

- app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
- app/packs/src/apps/mydb/elements/details/wellplates/attachmentsTab/WellplateDetailsAttachments.js
- app/packs/src/apps/mydb/elements/list/AttachmentList.js
- app/packs/src/components/container/ContainerDatasetModalContent.js
- package.json
- yarn.lock
Feat filters out devices that do not match the file type of the attachment. If none are available returns "None Available"
> 3PA: Apply ext mime type filter

- db/migrate/20210303140000_text_template_init.rb
- db/seeds/shared/text_templates.seed.rb
> fix: use of obsolete method for text_templates

- app/api/chemotion/chem_spectra_api.rb
- app/packs/src/fetchers/AttachmentFetcher.js
- lib/chemotion/jcamp.rb
- spec/lib/chemotion/jcamp_spec.rb
Demo video for shifting function
https://github.com/ComPlat/chemotion_ELN/assets/9006482/b5382af0-6146-4825-ba58-21ca8135d692
Demo video for the new style of NMR preview image
https://github.com/ComPlat/chemotion_ELN/assets/9006482/195fd2c7-e470-4fb1-8e94-d81e7084cbd8
> feat: add shift function for CV layout and new preview image for NMR

- Gemfile
- Gemfile.lock
- app/api/chemotion/molecule_api.rb
- app/api/helpers/sample_helpers.rb
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/packs/src/fetchers/MoleculesFetcher.js
- lib/chemotion/calculations.rb
- spec/lib/chemotion/calculations_spec.rb
feat: for decoupled samples, calculate the molecular mass automatically from the sum formula
modify the sum formula input field to mark it as an undefined structure
Closes https://github.com/ComPlat/chemotion_ELN/issues/1673
> feat: decoupled samples molecular mass determined from sum formula

- .gitignore
- app/packs/src/components/searchModal/forms/AnalysesFieldData.js
- app/packs/src/components/searchModal/forms/DetailSearch.js
- app/usecases/search/advanced_search.rb
- app/usecases/search/conditions_for_advanced_search.rb
Add analyses datasets to detail search
> feat: add analyses datasets to search

- app/assets/stylesheets/cellLines.scss
- app/packs/src/apps/mydb/collections/CollectionTabs.js
- app/packs/src/apps/mydb/elements/details/computeTasks/ComputeTask.js
- app/packs/src/apps/mydb/elements/details/computeTasks/ComputeTaskContainer.js
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/packs/src/apps/mydb/elements/details/screens/researchPlansTab/EmbeddedResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/list/ElementsTableSettings.js
- app/packs/src/apps/mydb/elements/tabLayout/TabLayoutCell.js
- app/packs/src/apps/mydb/elements/tabLayout/TabLayoutContainer.js
- app/packs/src/apps/mydb/inbox/AttachmentContainer.js
- app/packs/src/apps/mydb/inbox/DatasetContainer.js
- app/packs/src/apps/mydb/inbox/InboxModal.js
- app/packs/src/components/common/ClipboardCopyText.js
- app/packs/src/components/common/ConfirmModal.js
- app/packs/src/components/computedProps/ComputedPropsContainer.js
- app/packs/src/components/computedProps/ComputedPropsGraph.js
- app/packs/src/components/computedProps/ComputedPropsGraphContainer.js
- app/packs/src/components/computedProps/CustomAxisLabel.js
- app/packs/src/components/computedProps/GraphReferenceTable.js
- app/packs/src/components/computedProps/NoComputedProps.js
This PR refactors the following components to latest react-bootstrap:
Also contains bugfix for the error when 'copy to metadata' button is clicked in research plans
> Update bootstrap computed props

- .gitignore
- app/packs/src/components/viewer/MolViewerBtn.js
- app/packs/src/components/viewer/MolViewerListModal.js
- app/packs/src/components/viewer/MolViewerModal.js
- app/packs/src/components/viewer/MolViewerSet.js
- db/migrate/20230323160712_matrice_molecule_viewer.rb
- package.json
- yarn.lock
* handle empty input for viewer
* linting
> handle empty input for viewer

- app/packs/src/utilities/SpectraHelper.js
- spec/javascripts/packs/src/utilities/SpectraHelper.spec.js
> fix: fixed missing other internal ref

- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
- app/packs/src/components/ChemicalTab.js
- app/packs/src/models/Sample.js
- app/packs/src/utilities/CollectionTabsHelper.js
- lib/export/export_chemicals.rb
- lib/reporter/docx/detail_reaction.rb
> UI enhancements

- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
Fix related to Sample layout UI rework:
-  Reorder Chemical Identifiers, User labels, Elemental composition.
-  Restore solvents in sample properties
> fix - Sample layout UI

- app/packs/src/components/viewer/MolViewerBtn.js
- app/packs/src/components/viewer/MolViewerListBtn.js
- app/packs/src/components/viewer/MolViewerListModal.js
- package.json
- yarn.lock
* handle binary response for viewer
* linting
> handle binary response for viewer

- app/packs/src/fetchers/BaseFetcher.js
Restore user label accidentally removed by commit a1d1101441a6d067a55321b904da92782646ad81
> fix: restore user label

- app/packs/src/utilities/SpectraHelper.js
- spec/javascripts/packs/src/utilities/SpectraHelper.spec.js
> fix: fix cannot get scan rate from metadata

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
> fix: truncate name when empty

- app/assets/stylesheets/ketcher.scss
- app/packs/src/components/ketcher-templates/CommonTemplatesList.js
Purpose of this PR is to add search feature for common template list in ketcher 2 Editor:
https://github.com/user-attachments/assets/480228b8-e26e-439d-a3e4-0cfe0202b61c
----------------------
> feat: Search common templates In Ketcher2

- app/packs/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
- app/packs/src/components/container/ContainerDatasetModalContent.js
- app/packs/src/stores/mobx/AttachmentNotificationStore.jsx
This PR provides bug fixes for the below issues:
- fix duplicate attachments in Container Datasets
- Clear messages on save for wellplates and container datasets
> bugfix-duplicate attachments in analyses

- app/api/helpers/container_helpers.rb
> fix: upload attachment error

- app/packs/src/apps/userSettings/Affiliations.js
Minor UI enhancements to the new affiliations UI based on user feedback during testing:
> affiliations-change color of the save button and add required placeholder

- Gemfile
- Gemfile.lock
> Labimotion 142

- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
> display toggle button for default/gaseous scheme only in reaction scheme tab

- app/api/entities/reaction_variation_entity.rb
- app/packs/src/components/contextActions/ScanCodeButton.js
- yarn.lock
> fix: add yarn.lock

- CHANGELOG.md
> CHANGE_LOG_1.10.1

- app/api/chemotion/wellplate_api.rb
- app/models/well_position.rb
- app/packs/src/apps/mydb/elements/details/wellplates/attachmentsTab/WellplateDetailsAttachments.js
This PR will solve the problem that the template.xlsx for importing samples into wellplate could not be downloaded. Also it fixes a problem, if the user wants to import samples from the wellplate.
> fix: wellplate template download

- app/assets/stylesheets/global-styles/bootstrap-config.scss
> Redefine theme colors

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/AttachmentList.scss
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
- app/packs/src/apps/mydb/elements/list/AttachmentList.js
> improve design of research plan attachments

- app/packs/src/apps/admin/AdminNavigation.js
- app/packs/src/apps/mydb/elements/details/NumeralInputWithUnitsCompo.js
- app/packs/src/apps/mydb/elements/details/PrivateNoteElement.js
- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetailsMainProperties.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsPurification.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
- app/packs/src/apps/mydb/elements/list/ElementsTableEntries.js
- app/packs/src/components/navigation/NavNewSession.js
- app/packs/src/components/navigation/UserAuth.js
Contains minor bugfixes and styling improvements for bootstrap upgrade
> Bootstrap upgrade bugs and styling fixes

- app/assets/stylesheets/components/AttachmentList.scss
- app/assets/stylesheets/global-styles/utilities.scss
- app/assets/stylesheets/global-styles/utilities/detail-card.scss
- app/assets/stylesheets/global-styles/utilities/dnd.scss
- app/assets/stylesheets/legacy/cellLines.scss
- app/assets/stylesheets/legacy/elements_details.css
- app/assets/stylesheets/legacy/generic_element.scss
- app/assets/stylesheets/legacy/report.scss
- app/packs/src/apps/admin/OlsTerms.js
- app/packs/src/apps/admin/TemplateManagement.js
- app/packs/src/apps/mydb/elements/details/cellLines/CellLineDetails.js
- app/packs/src/apps/mydb/elements/details/computeTasks/ComputeTaskContainer.js
- app/packs/src/apps/mydb/elements/details/formats/FormatComponent.js
- app/packs/src/apps/mydb/elements/details/formats/FormatContainer.js
- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
- app/packs/src/apps/mydb/elements/details/reports/ReportContainer.js
- app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsDropTarget.js
- app/packs/src/apps/mydb/elements/details/researchPlans/wellplatesTab/EmbeddedWellplate.js
- app/packs/src/apps/mydb/elements/details/researchPlans/wellplatesTab/ResearchPlanWellplates.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersCom.js
- app/packs/src/apps/mydb/elements/details/screens/ScreenDetails.js
- app/packs/src/apps/mydb/elements/details/screens/researchPlansTab/EmbeddedResearchPlanDetails.js
- app/packs/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
- app/packs/src/apps/mydb/elements/list/ElementsTableSampleEntries.js
- app/packs/src/apps/mydb/elements/list/cellLine/CellLineItemEntry.js
- app/packs/src/apps/mydb/inbox/InboxModal.js
- app/packs/src/components/metadata/MetadataContainer.js
> improve styling for drop zones and detail cards

- .github/workflows/ci.yml
> ci:  set postgres to latest 16 for testing

- app/assets/stylesheets/legacy/reaction.scss
- app/assets/stylesheets/legacy/spectra.scss
- app/packs/src/apps/mydb/elements/details/ViewSpectra.js
- app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
- app/packs/src/apps/mydb/elements/details/reactions/greenChemistryTab/GreenChemistry.js
- app/packs/src/apps/mydb/elements/details/reactions/greenChemistryTab/GreenMaterialGroup.js
- app/packs/src/apps/mydb/elements/details/reactions/greenChemistryTab/GreenMetrics.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.js
- app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/packs/src/components/common/ImageModal.js
- app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js
- Fix for sum formular buttons and sample labels
- Fix missing label at reaction products table
- Fix modal size spectra editor, nmrim editor and image modal
- Fix overlay for reaction variations
> Fixes for samples, reactions and analyses

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
remove name truncation  (460542b241e7)
compensate for div nesting by moving up the css class (8ea073484)
> fix(UI): reaction scheme - sample names style

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/MydbApp.scss
- app/assets/stylesheets/global-styles/package-mods/react-select.scss
- app/assets/stylesheets/global-styles/utilities.scss
- app/assets/stylesheets/global-styles/utilities/white-space.scss
- app/packs/src/apps/admin/AdminDashboard.js
- app/packs/src/apps/admin/AdminGroupElement.js
- app/packs/src/apps/admin/AdminHome.js
- app/packs/src/apps/admin/OlsTerms.js
- app/packs/src/apps/admin/UserManagement.js
- app/packs/src/apps/mydb/App.js
> Update bootstrap css cleanup

- app/packs/src/apps/mydb/elements/details/reactions/propertiesTab/ReactionDetailsProperties.js
- app/packs/src/components/ChemicalTab.js
Fixes unable to select options in inventory tab
> Fixes inventory tab

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
- app/packs/src/apps/mydb/elements/details/wellplates/designerTab/WellDetails.js
- app/packs/src/apps/mydb/elements/details/wellplates/designerTab/Wellplate.js
- app/packs/src/apps/userSettings/Affiliations.js
- app/packs/src/components/container/ContainerDatasetField.js
- app/packs/src/components/managingActions/ManagingModalRemove.js
- app/packs/src/models/Well.js
> fix in bootstrap: color and label not saved on submit in wellplates

- app/assets/stylesheets/global-styles/package-mods/react-select.scss
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/packs/src/components/reactQuill/ToolbarDropdown.js
- Fix position of select options
- Fix delete rule for style sheets at quill editor
- Fix breaking molecule name
> Fix position of select options div

- app/assets/stylesheets/global-styles/bootstrap-config.scss
- app/assets/stylesheets/global-styles/bootstrap-mods.scss
- app/packs/src/apps/mydb/App.js
- app/packs/src/apps/mydb/elements/details/reactions/propertiesTab/ReactionDetailsProperties.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/packs/src/apps/userSettings/Affiliations.js
- app/packs/src/fetchers/UserSettingsFetcher.js
This PR contains Bootstrap fixes for:
> Bootstrap fixes for broken selects and overlapping dropdown

- app/packs/src/apps/mydb/collections/CollectionSubtree.js
- app/packs/src/apps/mydb/elements/details/NumeralInputWithUnitsCompo.js
- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
- app/packs/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
- app/packs/src/apps/mydb/elements/list/ElementsTableSampleEntries.js
- app/packs/src/components/ChemicalTab.js
This PR fixes minor bugs/ issues based on the feedback received after bootstrap upgrade.
Bootstrap related issues are documented here:
https://docs.google.com/document/d/1BuMr3nycc0ZAvia8rT6QVnQ-YS14hivRazIlzBxceCw/edit?tab=t.0#heading=h.12fbp2kablsg
> fix: bootstrap styles

- app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
> fix: allow header for yield/equiv. column in reaction scheme for shared collections with read only rights

- .github/workflows/asset-precompilation.yml
- config/database.yml.ci
- package.json
- fix asset precompilation workflow
- add browserslist update db check
> ci: fix asset compilation testing workflow

- app/api/chemotion/cell_line_api.rb
- app/api/helpers/cell_line_api_params_helpers.rb
- app/models/cellline_sample.rb
- app/packs/src/components/contextActions/CreateButton.js
- app/packs/src/components/contextActions/SplitElementBtn.js
- app/packs/src/fetchers/CellLinesFetcher.js
- app/packs/src/stores/alt/actions/ElementActions.js
- app/packs/src/stores/alt/stores/ElementStore.js
- app/packs/src/utilities/CellLineUtils.js
- app/usecases/cell_lines/copy.rb
- app/usecases/cell_lines/split.rb
- db/migrate/20240531112321_add_ancestry_to_cellline_sample.rb
- spec/api/chemotion/cell_line_api_spec.rb
- spec/factories/cell_line_sample.rb
- spec/usecases/cell_lines/copy_spec.rb
>   feat: split cell lines

- app/assets/stylesheets/global-styles/package-mods/ag-grid.scss
- app/assets/stylesheets/global-styles/vendor.scss
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsCellComponents.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.js
This PR addresses #2283 and #2284.
> fix(UI): reaction variations table style and appearance 

- app/models/sample.rb
> style: rubocop app/models/sample.rb

- app/javascript/src/components/navigation/UserAuth.js
- app/javascript/src/components/navigation/search/AutoCompleteInput.js
This PR fixes minor UI bugs:
1. Adjust the position of user name to avoid scrolling horizontally
2. Fixed transparent dropdowns in Autocomplete search
> fix(UI): adjust css for scrollbar and hidden dropdown

- app/javascript/src/apps/admin/devices/DeviceModal.js
Password double encryption issue on every update request resolved.
> fix: retain novnc password during device update

- app/javascript/src/components/computedProps/ComputedPropsContainer.js
- app/javascript/src/components/computedProps/SampleComputedProps.js
- db/seeds/development/04_computed_props.seed.rb
- spec/factories/computed_props.rb
- Fixed table display UI of Computed Props py setting a css flex class (since 91417f6b2b)
- reposition accordingly the submit button
- also fixed wrong props (since c85856e3936)
- added detailed rb factory and development seeds for computed_props
> fix(UI):  sample computed-prop to display the result table

- .service-dependencies
bump ketcher2 from 2.21.0 to 2.28.0
bump chemotion-converter-app from 1.3.0 to 1.4.0
> chore: update service dependencie

- app/javascript/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/javascript/src/stores/alt/stores/ReportStore.js
pass or use the proper object from or to the value property of the Select component refactored in 91417f6b2
Refs: #1930
> fix(UI): value of Select input from Sample molecule name and report template

- app/assets/stylesheets/legacy/chemical-tab.scss
- app/javascript/src/components/ChemicalTab.js
- lib/chemotion/chemicals_service.rb
- spec/lib/chemotion/chemicals_service_spec.rb
Description: 
- Fix: Fetching Chemical Properties from Merck Vendor
- Refactor: Adjusting Button Widths for Safety Sheet & Fetch Properties
______________________________________________________________
> chore: update chemical inventory msds mapper

- package.json
- yarn.lock
https://github.com/ComPlat/chemotion-converter-client/releases/tag/v0.13.0 https://github.com/ComPlat/chemotion-converter-client/compare/v0.12.0...v0.13.0
> chore: bump @complat/chemotion-converter-app from 0.12.0 to 0.13.0

- app/javascript/src/utilities/CollectionTabsHelper.js
app/javascript/src/utilities/CollectionTabsHelper.js getArrayFromLayout:
Null check was missing and function was unnecessary complex.
Simplified  function.
> fix: tab layout setting per collection

- lib/reporter/docx/detail_reaction.rb
Description:
- bug for generating report for gas scheme reaction
- fix: handle null mole value for gas products in reaction scheme
_________________________________________________________________________________________________
> fix: generating report for gas scheme reaction

- db/migrate/20240207121720_init_device_description_to_element_klasses.rb
DRY migration that provides the generic device-description klass and revision 
as most attributes are automatically handled by the library
> refactor: generic device description klass migration

- app/api/chemotion/affiliation_api.rb
- app/javascript/src/apps/userSettings/Affiliations.js
This PR contains:
1. Fix for the error on deleting an affiliation
2. Enhances deleting affiliation by asking for user confirmation
> fix: silent network error on affiliation deletion api call

- .service-dependencies
- from v1.2.4 to v1.2.5 in service-dependencies
> chore: bump chemspectra-app requirement

- app/javascript/src/apps/mydb/elements/Elements.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/DeviceDescriptionDetails.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/FormFields.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/OntologiesList.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/OntologySegmentsList.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/OntologySelect.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/analysesTab/AnalysesContainer.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/detailsTab/DetailsForm.js
- app/javascript/src/apps/mydb/elements/details/deviceDescriptions/propertiesTab/PropertiesForm.js
- app/javascript/src/apps/mydb/elements/list/ElementsTable.js
- app/javascript/src/apps/mydb/elements/list/deviceDescriptions/DeviceDescriptionList.js
- app/javascript/src/apps/mydb/elements/list/deviceDescriptions/DeviceDescriptionListHeader.js
- app/javascript/src/components/common/ConfirmClose.js
- app/javascript/src/stores/mobx/DeviceDescriptionsStore.jsx
- app/usecases/device_descriptions/update.rb
- spec/api/chemotion/device_description_api_spec.rb
- Fix label for components / setups
- Add new groups (grouped by ontologies, grouped by combined ontologies) to device description list
- Add selection for segment forms when selecting new ontology
- Edit selection for segment forms at ontology classification 
- Fixes for device description store and labimotion toolbar buttons
- Fix init device description at Labimotion::ElementKlass migration
> feat: device description adjustments

- app/api/entities/reaction_variation_entity.rb
- app/assets/stylesheets/global-styles/package-mods/ag-grid.scss
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.js
- db/migrate/20250328123030_add_density_to_reaction_variations.rb
- spec/factories/reactions.rb
- spec/javascripts/helper/reactionVariationsHelpers.js
- spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.spec.js
- spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.spec.js
This PR addresses #2402.
Note that the firsts two commits (46b481ebd6783baffdcbcc838cb8f1a9b3c4cbf2, d903feb3718b4c0b02c0c6431f3d5ea9523eee19) contain minor fixes that are not related to the feature.
> feat: add volume to editable entries of reaction variation materials

- db/seeds/shared/rdkit.seed.rb
> fix(db): rdkit seed - drop trigger if feature disabled but rdkit schema present

- app/javascript/src/apps/mydb/elements/details/samples/SampleDetails.js
- lib/pub_chem.rb
- backend: better validation of cid arg to ensure a valid uri is built (lib/pubchem)
- frontend: ensure the cas options array for the cas <CreatableSelect/> input is valid
> fix: selecting cas for a sample breaks when sample has multiple cids

- .service-dependencies
- package.json
- yarn.lock
- chem-spectra-app to 1.2.6 https://github.com/ComPlat/chem-spectra-app/releases/tag/v1.2.7
- https://github.com/ComPlat/chem-spectra-app/pull/231
- https://github.com/ComPlat/chem-spectra-app/pull/229
- chemotion-converter-app to 1.5.0 https://github.com/ComPlat/chemotion-converter-app/releases/tag/v1.5.0
- https://github.com/ComPlat/chemotion-converter-app/pull/153
- Ketcher 3 to v3.1.0
- chemotion-converter-client to v0.13.2 
- https://github.com/ComPlat/chemotion-converter-client/pull/85
> chore: update service dependencies

- app/javascript/src/apps/mydb/elements/details/reactions/ReactionDetails.js
- app/javascript/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
- app/javascript/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
- app/javascript/src/stores/alt/actions/DetailActions.js
- rm unused function in samples/propertiesTab/SampleForm.js
- fix style and function of  `<Form.Label>Molecule name</Form.Label>` of SampleForm.js
- rm `&nbsp;`
> fix(UI): regression introduced by #2068

- app/models/attachment.rb
- db/migrate/20250422115436_add_created_by_type_to_attachment.rb
- db/schema.rb
- lib/datacollector/correspondence.rb
since it can be generated by devices and users
TODO implement full polymorphism or define multiple association
refs: #1736, #2240
> feat: add created_by_type to attachments

- lib/reporter/delta.rb
- spec/lib/reporter/delta_spec.rb
ensure any blank input is handled
> fix: reporter quill delta to html to handle blank inputs

- .dockerenv.example
- .tool-versions
- app/models/admin.rb
- app/models/attachment.rb
- app/models/cellline_material.rb
- app/models/cellline_sample.rb
- app/models/collections_sample.rb
- app/models/container.rb
- app/models/container_hierarchy.rb
- app/models/group.rb
- app/models/inventory.rb
- app/models/matrice.rb
- app/models/molecule.rb
- app/models/notify_message.rb
- app/models/person.rb
- app/models/reactions_product_sample.rb
- app/models/reactions_purification_solvent_sample.rb
- app/models/reactions_reactant_sample.rb
- app/models/reactions_sample.rb
- app/models/reactions_solvent_sample.rb
- app/models/reactions_starting_material_sample.rb
- app/models/research_plans_wellplate.rb
- app/models/user.rb
- config/initializers/content_security_policy.rb
- db/schema.rb
- package.json
* build(dev): update db/schema.rb
update dev image
* chore: bump node js 22.15
* docs: update model annotation
* fix: csp report endpoint (ref: #2399)
> chore: miscellaneous db/schema - annotation - bump minor node

- .tool-versions
- app/javascript/src/apps/mydb/elements/details/VersionsTable.js
- app/javascript/src/apps/mydb/elements/details/VersionsTableChanges.js
- app/javascript/src/apps/mydb/elements/details/VersionsTableFields.js
- app/models/attachment.rb
- app/services/versioning/fetchers/reaction_fetcher.rb
- app/services/versioning/serializers/reaction_serializer.rb
- app/services/versioning/serializers/sample_serializer.rb
- app/services/versioning/serializers/screen_serializer.rb
- app/services/versioning/serializers/wellplate_serializer.rb
> feat(UI): history tracker update

- config/initializers/cors.rb
simple cors config to allow access to public endpoint
refs: #1832
> feat: add simple cors config for public TPA interaction

- app/javascript/src/apps/mydb/elements/details/samples/SampleDetails.js
> fix(UI): molfile info in sample card - chemical identifiers

- app/api/chemotion/molecule_api.rb
- app/models/molecule.rb
- app/models/sum_formula.rb
- lib/chemotion/calculations.rb
- spec/lib/chemotion/calculations_spec.rb
- spec/models/sum_formula_spec.rb
- add sum_formula model
- deprecate some functions / move logic from Chemotion:Calculations to SumFormula
- make clearer the modification to sum_formula when the molecule is_partial on creating molecule
this also fix the issue for creating partial molecule due to the new index on sum_formula (#2244)
> refactor: sum formula handling for molecule creation

- CHANGELOG.md
- VERSION
> chore: prepare v2.0.0

- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsReducers.js
- spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.spec.js
> feat: propagate material edits from scheme-tab to variations-tab

- db/schema.rb
These were unintentionally committed in https://github.com/ComPlat/chemotion_ELN/pull/2211.
> build(db): revert accidental schema changes

- app/javascript/src/components/container/ContainerDatasetModalContent.js
simplify logic by using  a standard Select component from app/javascript/src/components/common/Select.js
solve style issues with the dropdown list
refs: #2537
> refactor: instrument field to use standard select component

- app/javascript/src/components/common/GatePushButton.js
Fixes https://github.com/ComPlat/chemotion_ELN/issues/2546
> fix: tooltip issue while transmitting data to repository

- app/javascript/src/apps/mydb/elements/details/VersionsTable.js
- app/javascript/src/apps/mydb/elements/details/VersionsTableFields.js
- app/services/versioning/serializers/base_serializer.rb
- app/services/versioning/serializers/sample_serializer.rb
Fixed mass percentage bug in tracking
Changed molfile formating
Added loading spinner for History Tab
> fix: history formaters

- app/javascript/src/components/common/Select.js
> fix(UI): Fix select menus in modals

- app/api/chemotion/search_api.rb
- app/api/chemotion/suggestion_api.rb
- app/javascript/src/components/navigation/search/AutoCompleteInput.js
- app/models/sample.rb
- spec/api/chemotion/suggestion_api_spec.rb
You can now search samples by molecule name.
- Added pg_search_scope & scope for molecule name
- Added molecule name to search and suggestion API
> feat(search): search sample by custom molecule name

- app/javascript/src/apps/mydb/elements/list/deviceDescriptions/DeviceDescriptionList.js
- db/schema.rb
If the serial number is missing the group name was changed from [empty] to [missing serial no]
> style: change group name in device description list

- app/api/api.rb
- app/api/chemotion/collection_api.rb
- app/api/chemotion/element_api.rb
- app/api/chemotion/profile_api.rb
- app/api/chemotion/vessel_api.rb
- app/api/entities/user_entity.rb
- app/api/entities/vessel_instance_entity.rb
- app/api/entities/vessel_template_basic_entity.rb
- app/api/entities/vessel_template_entity.rb
- app/models/concerns/element_codes.rb
- app/models/concerns/tagging.rb
- app/models/profile.rb
- app/models/vessel.rb
- app/models/vessel_template.rb
- app/proxies/element_permission_proxy.rb
- config/profile_default.yml.example
- db/migrate/20250211171435_add_weight_to_vessels.rb
- db/migrate/20250508104326_add_unique_index_to_vessel_templates_name.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/vessel_spec.rb
- spec/models/vessel_template_spec.rb
This pull request consists of backend changes to add a new element to the eln: vessel
Basic vessel and vessel_template models were already in place.
Below are the main channges to intregrate the vessel models into ELN:
- Vessel api with CRUD endpoints and few other endpoints based on requirements
- Includes changes to integrate vessel element to the eln
- Adds two entities: vessel_instance_entity and vessel_template_entity
- Contains changes to element_codes to enable auto barcode generation on creation of a vessel instance
Also, contains a migration to add weight amount and weight unit columns to vessel model
> feat(vessel): implement api for vessel and vessel template

- Gemfile.lock
- app/javascript/src/components/searchModal/forms/SearchResultTabContent.js
skip using SampleName component for displaying name of non Sample Elements 
since #2311
> fix: search result for missing isMixture

- app/javascript/src/components/searchModal/forms/KetcherRailsForm.js
- app/javascript/src/components/searchModal/forms/SearchModalFunctions.js
- app/javascript/src/components/searchModal/forms/SearchResult.js
Changing tabs in search result not always working.
You can't change back to the first active tab
> fix: tabs navigation in advanced search result

- app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
- app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
- app/javascript/src/components/common/ToggleButton.js
- spec/javascripts/packs/src/components/common/ToggleButton.spec.js
**Problem:**
1.  Inconsistent UI styling - Toggle buttons used custom color properties instead of standard Bootstrap variants
2. Poor user experience - Missing explanatory tooltips for yield field calculations 
**Solution:**
1. Standardized styling system - Replaced custom onColor/offColor props with Bootstrap variant prop
2. Enhanced user guidance - Added informative tooltip explaining yield calculation basis
3. Improved component consistency - Updated ToggleButton to use buttonClass and buttonTitleClass props
4. Better text formatting - Implemented JSX elements for cleaner tooltip presentation
__________________________________________________________________________________________________________________
> style: improve yield/conversion rate toggle button implementation

- .service-dependencies
- app/api/chemotion/third_party_app_api.rb
- app/api/helpers/third_party_app_helpers.rb
- spec/api/chemotion/third_party_app_api_spec.rb
for compatibility with ChemLocalLink v2
diff:  https://github.com/Chemotion/ChemLocalLink/compare/v1.0.4...v2.0.0
README https://github.com/Chemotion/ChemLocalLink?tab=readme-ov-file#chemlocallink
> feat: add metadata to attachment url for ChemLocalLink

- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsReducers.js
- app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.js
A few minor refactorings on the heels of #2528.
> refactor: reaction variations
