ComPlat/chemotion_ELN

app/assets/stylesheets/molecules.css

Regarding to reaction SVG, we need to display it on RTF Report & Web.
For rendering in RTF Report, we need to convert SVG to PNG, which is less flexible.
Therefore, I decide to make SVG size fit to RTF report generation(~12in), and control the size of it by css on the webtsite.

fix reaction svg size

---

app/assets/javascripts/components/ReactionDetailsScheme.js

Under reaction edit mode, we use a sample copy, not split, for __product__.

reaction-product is a sample copy

---

app/assets/javascripts/components/ReactionDetails.js
app/assets/javascripts/components/ReactionDetailsAnalyses.js
app/assets/javascripts/components/ReactionDetailsLiteratures.js
app/assets/javascripts/components/ReactionDetailsMainProperties.js
app/assets/javascripts/components/ReactionDetailsProperties.js
app/assets/javascripts/components/ReactionDetailsScheme.js
app/assets/javascripts/components/ReactionDetailsShare.js

1. make ```ReactionDetailsMainProperties.js``` as a stateless component. 
2. refactor reaction edit input arrangement.
3. DRY: move a shared function to ```ReactionDetailsShare.js```
4. finish #336 time capture button for start stop input.

re-arrange reaction input & time capture button resolve #314 #336

---

app/assets/javascripts/components/App.js
app/assets/javascripts/components/CollectionSubtree.js
app/assets/javascripts/components/CollectionTree.js
app/assets/javascripts/components/Elements.js
app/assets/javascripts/components/ElementsTable.js
app/assets/javascripts/components/List.js
app/assets/javascripts/components/SampleDetails.js
app/assets/javascripts/components/UserAuth.js
app/assets/javascripts/components/collection_management/MyCollections.js
app/assets/javascripts/components/collection_management/MySharedCollections.js

solve:
1. ```setState``` warning
2. When coming back from collection-managements, __List__ will no longer be empty.

fix warning setState & empty-list when back from collection-managements

---

app/assets/javascripts/components/ElementsTable.js

OnSelect is changed since react-bootstrap v0.29.0: https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md

Fix pagination bug

---

app/api/chemotion/search_api.rb
app/assets/javascripts/components/SampleForm.js
app/models/molecule.rb
db/migrate/20160721141337_update_molecule_fingerprint.rb
lib/chemotion/open_babel_service.rb

- Fix the warning when 'input' controller has null value
- Change the fingerprint generation to use original molfile from samples table
- Since OpenBabel doen't use the last 3 bits, we will enable those bits for polymer search. We have 3 bits, so we can have total 8 "special groups"
- Resolved for #353

Fix the bug while searching the polymer

---

app/api/chemotion/sample_api.rb
app/assets/javascripts/components/ElementCollectionLabels.js
app/assets/javascripts/components/ElementReactionLabels.js
app/assets/javascripts/components/ElementsTableSampleEntries.js
app/serializers/sample_serializer.rb

+ The new icon can only be rendered in sample that participate to reaction (as product or starting material)
+ Add hover effect to the new 'link-to-reaction' icon and the collection icon
+ ReactionDetails will be open when click on this new icon

Add an icon link to reaction in Sample table

---

config/application.rb

Make React debug easier.
The same error warning...
__Before__: warning at line 21179??, and code is not the same as the original code.
__Now__: you can see the problem is at ReportContainer line 37.

enable source-map for js

---

app/assets/javascripts/components/App.js
app/assets/javascripts/components/ElementsTableEntries.js
app/assets/javascripts/components/ElementsTableSampleEntries.js
app/assets/javascripts/components/List.js
app/assets/javascripts/components/actions/KeyboardActions.js
app/assets/javascripts/components/search/AutoCompleteInput.js
app/assets/javascripts/components/stores/KeyboardStore.js

- From this commit we can move element (samples, reactions, wellplates, screens) using the arrow key. Press "Enter" or "right arrow" to open element.
- "Keydown" will be manipulate through added KeyboardStore

Moving element using keyboard

---

app/assets/javascripts/components/ElementsTableSampleEntries.js
app/assets/javascripts/components/List.js
app/assets/javascripts/components/ReactionDetails.js
app/assets/javascripts/components/structure_editor/StructureEditorModal.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/elements_details.css
app/assets/stylesheets/molecules.css
app/assets/stylesheets/structur_editor.css
lib/svg/reaction_composer.rb

- Make old "GenerateReport" button smaller and move to title, next to close button
- Reaction title now will take 1 line space above reaction svg
- Stretch reaction svg to 100% width
- Svg Generating: Add a small space between starting materials
- Use JS to auto update StructureEditorModal. 
- Fix CSS bugs when Sample or Element content is too big, lead to the breaking of ElementsTable
- Fix FF bug in Ketcher and ElementsDetail
- Redmine: #448 #450 #462 #465

Update ReactionDetails UI

---

app/assets/javascripts/components/App.js

From now, we only process arrow key from BODY. All `onKeyDown` event from other elements will be ignored

Re-enable keyboard navigation

---

Gemfile.lock
app/assets/javascripts/components/structure_editor/StructureEditorModal.js
app/assets/stylesheets/structur_editor.css

The solution was to calculate the editor height that will suit the following:
- must be 590px (basic menu table size) + N*36px. N is integer so that we avoid situation when we hide a part of the bottom menu line.
- it must be close to 75% of screen height
Then it is sent as a parameter to Ketcher and it adds table lines and adjusts 'rowspan' attribute of working area.
Refer to Ketcherails changeset:
https://github.com/ComPlat/ketcher-rails/commit/a39798ebbd78c7d8c2eaead085f9f1524d23b128

Fix structure editor height resolve #515

---

app/api/chemotion/report_api.rb
lib/report/excel_export.rb

- Export all the Sample table
- Change reaction and wellplates export.
- Create blank xls report file if no sample or element created
- Exclude some fields from samples
- Include sum_formula and cano_smiles from molecule
- "generate_file" function include using: {Associated_model}.{field}
- Resolve #496

Update export features

---

app/assets/javascripts/components/ReactionDetails.js
app/assets/javascripts/components/SampleDetails.js
app/assets/javascripts/components/ScreenDetails.js
app/assets/javascripts/components/WellplateDetails.js
app/assets/stylesheets/application.scss.erb

- Add a saveButton to every ElementDetails header
- StickyDiv follows scrolling
- Fix a warning "<div> cannot be <p> descendant..." in ScreenDetail
- ReactionDetails header color only change if reacion is changed
- Resolve #492

ElementDetails header UI update

---

app/api/chemotion/reaction_api.rb
app/assets/javascripts/components/Material.js
app/assets/javascripts/components/ReactionDetailsScheme.js
app/assets/javascripts/components/models/Reaction.js
app/assets/javascripts/components/models/Sample.js
app/models/sample.rb

- Reactant and Solvents sample will not increase the counter any more.
- Reactant and Solvents short_label will now be 'reactants' or 'solvents'
- In ReactionDetails, only reactant/solvents IUPAC name with the link to its details.
- Resolve #506

Remove Reactant/Solvents counter

---

app/assets/javascripts/components/ReactionDetailsScheme.js

- The automated string for reaction product will not be saved into product's external label
. Resolves #553

Save automated reaction product string into external label

---

app/assets/javascripts/components/models/Sample.js
app/models/sample.rb
spec/api/sample_api_spec.rb

- Split sample (using splitButton and split during creating Reaction) will inherit some properties from parent
- Name: {parent_name}-split (if parent_Name not empty)
- External_label: {parent_external_label}-split (if parent_external_label not empty)
- Short_label is updated (exclude reactants and solvents)
- Resolves #544

Split Sample

---

app/api/api.rb
app/assets/javascripts/components/ElementCollectionLabels.js
app/assets/javascripts/components/ElementReactionLabels.js
app/assets/stylesheets/elements_table.css
app/models/concerns/labeled.rb
app/models/sync_collections_user.rb
db/migrate/20161004121244_add_is_synchronized_to_collections.rb
db/schema.rb
spec/api/reaction_api_spec.rb
spec/api/sample_api_spec.rb

- Add new column `is_synchronized` to Collection table, which turn on to synchronized collection. This flag will be automatically update while synchronized collection is created.
- Remake ElementCollectionLabel with a counter for own collections and shared (include synchronized) collections.
- Fix a bug when non-owned collections are displayed inside the label
- Resolves #488 #489

Remake ElementCollectionLabel

---

app/assets/javascripts/components/stores/ElementStore.js

- Reaction will be considered as "changed" when creating a new material through create button
- Resolves #606

Reaction "Changed" with new material

---

app/api/chemotion/reaction_api.rb
app/assets/javascripts/components/Material.js
app/assets/javascripts/components/ReactionDetails.js
app/assets/javascripts/components/ReactionDetailsScheme.js
app/assets/javascripts/components/models/Sample.js
app/models/sample.rb
spec/api/reaction_api_spec.rb
spec/api/sample_api_spec.rb

- Split sample, copy sample: copy name, external_label and elemental_compositions
- Change "reactants"/"solvents" short_label to "reactant"/"solvent" (singular)
- Bug fixed: if a reactant/solvent have no IUPAC name, display a sum_fomular and "reactant/solvent"
- Resolves #619 #625

Split Sample - Reactant without IUPAC

---

app/assets/javascripts/components/managing_actions/ManagingModalCollectionActions.js

```move to collection``` & ```assign to collection``` have hierarchy dropdown.

move to collection dropdown

---

app/assets/javascripts/components/CollectionTree.js

- Display collection categories (shared with, shared by, synchroniyed) even there is no collection belong to this category
- Fix bug when collection category is hidden when user have fake collection  (fake root)
- Resolves #655

Fix CollectionTree

---

Gemfile.lock
app/api/chemotion/reaction_api.rb
app/assets/javascripts/components/ReactionDetailsScheme.js
app/assets/javascripts/components/models/Reaction.js
app/assets/javascripts/components/models/Sample.js
app/assets/javascripts/components/stores/ElementStore.js

- Re-factor Sample and Reaction js model
- When moving un-saved sample between groups:
+ FROM products: blank name, short-label changes
+ TO products: auto-naming, short-label for new sample
+ TO starting_materials: split short-label, keep name
+ TO reactans/solvents: change short-label, keep name
- Moving saved sample:
+ Can't split short-label, so that use new short-label
+ reactant/solvents short-label changes
- Resolves #649

Drag and Drop

---

app/assets/javascripts/components/ReactionDetails.js
app/assets/javascripts/components/lineChart/LineChart.js
app/assets/javascripts/components/models/Reaction.js
app/models/reaction.rb

- If user enter text, keep original. If user enter a number, treat it as temperature:
+ Display unit in SVG
+ Apply unit conversion on entered text
- Increase chart range: 10% of total variability. For example: if the temperature change from 1 to 100. We have: (100 - 1) * 0.1 = 9.9,  the chart range is from 8.9 to 109.9. With this way, the temperature line can fit within the chart
- Resolves #667 #668 #669

Apply temperature convert to user text

---

lib/svg/reaction_composer.rb

add filter to make eps images without irregular word size

---

app/assets/javascripts/components/ReactionDetails.js
app/assets/javascripts/components/models/Reaction.js
app/assets/javascripts/components/models/Sample.js
app/assets/javascripts/components/stores/ElementStore.js

The problem before was that we did not refresh counter so had to use variable `temporary_samples_counter` in reaction. Now when we create a sample we refresh current user so don't need to use this counter.
**Question:** do I have to change old sample `short_label`-s ?

Fix reaction samples naming

---

app/assets/javascripts/components/CollectionSubtree.js

- After clear search condition, selected collection CSS is not considered as "selected"

Selected collection is not "selected"

---

app/assets/javascripts/components/stores/ElementStore.js

- While in molecule sorting: Sample managements (create, delete, move, split ...) will no longer back to samples sorting

Samples action in Molecule Sort

---

app/api/chemotion/sample_api.rb
app/assets/javascripts/components/Navigation.js
app/assets/javascripts/components/NavigationModal.js
app/assets/javascripts/components/actions/ElementActions.js
app/assets/javascripts/components/actions/UIActions.js
app/assets/javascripts/components/contextActions/ModalImportConfirm.js
app/assets/javascripts/components/fetchers/SamplesFetcher.js
app/assets/javascripts/components/stores/ElementStore.js
app/assets/javascripts/components/stores/UIStore.js
app/assets/stylesheets/application.scss.erb
app/assets/stylesheets/fixed-data-table.min.css
app/assets/stylesheets/molecules.css
app/models/molecule.rb
lib/import/import_sdf.rb
package.json

- processed uploaded sdf and create molecule
- return ordered list of processed data
- client checklist to select which sample to create
(fixed-data-table)
- create samples after user confirmation/sample selection
api action and fetcher (ElementStore)
- navigation modal props through UIstore,
to control Modal thru Alt action
also allow custom modal style
- moved create by batch to import_sdf to min call to DB
- fix missing authorized sample import on user collection

two step import of sd file

---

.github/workflows/testacceptance.yml

Hard-coded repository name in github action auto-breaks cloned repositories as new branches/commits usually do not exist in the upstream (complat) repo.
I suggest to use the GITHUB_REPOSITORY environment variable to make test work in cloned repos.

Use GitHub variables to make tests work in cloned repos

---

app/api/entities/container_entity.rb
app/packs/src/components/stores/SpectraStore.js

fixed cannot display the latest image of updated jdx on preview chemspectra

---

app/packs/src/components/CitationPanel.js

Move onclick event to button element

---

app/packs/src/components/ElementalComposition.js
lib/chemotion/calculations.rb

CHANGELOG: Closes #721
Significant zeroes are added to elemental compositional values, to ensure that all values are 2 decimal places.
The initial example (2,2-bipyridine) is now:
Example 2 (C10H18MnO6):
Original
New

Elemental composition values now have 2 decimal places

---

app/packs/src/components/staticDropdownOptions/options.js

Changelog:
- Closes #472 - options for specifying pH values added to conditions drop down menu - can specify if pH is equal to, greater than, or less than a value that the user can manually change in the conditions text field.
Preview:
- pH value options in conditions menu:
- pH value options in conditions text area:
- pH values rendered on reaction image:

added pH value options (<, >, =) in condition drop down menu

---

app/packs/src/components/ReactionDetails.js

CHANGELOG: Closes #691
Image of reaction is only shown if there are materials present (Starting materials, Reagents, Products, & Solvents) in the reaction scheme.
Please see the video for a demo.
https://user-images.githubusercontent.com/67055123/168553170-56829a04-ea6f-4f26-a263-522bef3e358c.mp4

show rxn image only if samples are present in rxn

---

app/packs/src/components/research_plan/ResearchPlanDetailsFieldReaction.js
app/packs/src/components/research_plan/ResearchPlanDetailsFieldSample.js

CHANGELOG:
- Added links to reactions within research plan. (Closes #666)
- Added links to samples, and modified rendering to account for (decoupled) samples with no image. (Closes #727)
- clicking sample images now opens the sample page in Chemotion
- (Decoupled) samples with no image render ONLY the sample name
Video 1:
https://user-images.githubusercontent.com/67055123/163406494-ea481983-e107-4b24-ae22-6c699f272b8e.mp4
Video 2: Decoupled sample with no image
https://user-images.githubusercontent.com/67055123/169822122-3899b316-1db3-47c2-9640-bbd59149c533.mp4

links to open rxns and samples in research plans

---

app/api/entities/application_entity.rb
app/api/entities/scifinder_n_credential_entity.rb

Fix error when trying to expose timestamps on an empty object

---

app/models/measurement.rb

Remove data uniqueness validation to allow multiple measurement exports with same data (for example from different research plans or multiple tables within the same research plan)

Remove data uniqueness validation from measurement

---

app/models/molecule.rb
app/models/sample.rb

error due to scrubbed data having blank character in the first bytes
also enforce encoding of openbabel produced svg

fix scrubbed sample svg from imported collection

---

app/api/chemotion/reaction_api.rb
spec/api/helpers_spec.rb
spec/api/reaction_api_spec.rb

I came across two conditionals whose right-hand-side operator is specified incorrectly.
Specifically, I mean `material_group === 'solvent'` in 
https://github.com/ComPlat/chemotion_ELN/blob/fad0e8efd9535a01d3f2677f636fe515d4ec2caf/app/api/chemotion/reaction_api.rb#L65
and `material_group != 'products'` in
https://github.com/ComPlat/chemotion_ELN/blob/fad0e8efd9535a01d3f2677f636fe515d4ec2caf/app/api/chemotion/reaction_api.rb#L68
The problem is that `material_group` is not a string, but a hash-key from
https://github.com/ComPlat/chemotion_ELN/blob/fad0e8efd9535a01d3f2677f636fe515d4ec2caf/app/api/chemotion/reaction_api.rb#L51-L57
This means that `material_group === 'solvent'` will never evaluate to `true` ,
and `material_group != 'products'` will never evaluate to `false`.
Regarding …

Fixed conditionals that involve `material_group` in reaction API

---

app/models/sample.rb
app/usecases/reactions/update_materials.rb
spec/usecases/reactions/update_materials_spec.rb

Calling `save` on a sample triggers an `after_save` callback in the sample-model that updates the reaction-SVGs that are associated with that sample.
https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/models/sample.rb#L167
https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/models/sample.rb#L511
When a sample is saved in the context of the reaction-API it is not necessary for the sample-model to update the reaction-SVG, since the reaction-model itself updates the reaction-svg.
https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/usecases/reactions/update_materials.rb#L82
https://github.com/ComPlat/chemotion_ELN/blob/dd3e2c4852ed953b4a89a36dcc1593094e64397a/app/models/reactio …

Prevent sample-model from unnecessarily updating reaction-SVG

---

app/api/chemotion/measurements_api.rb
app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTableMeasurementExportModal.js
app/packs/src/fetchers/MeasurementsFetcher.js
app/usecases/research_plans/import_wellplate_as_table.rb
spec/api/chemotion/measurements_api_spec.rb
spec/factories/wellplates.rb

This PR fixes a little bug in the measurements API, which caused the Javascript to fail as it expected a different structure returned from the server.
Measurements-Workflow
---------------------
- The Attachments tab within a wellplate contains a downloadable Excel Template. This templates allows importing a whole wellplate and has preset Columns that allow importing a wellplate into a research plan table.
- You can either create a wellplate manually or use the import template.
- Required fields for the measurement export are: 
- Sample (contains the sample short label)
- at least one pair of columns that represent a readout: READOUT Value, READOUT Unit (The columns must contain value and unit respectively, either as a separate word or with underscore READOUT_Value, READOUT_Unit)
- Open …

Bugfix wellplate import in research plan

---

CHANGELOG.md
app/packs/src/components/scifinder/ScifinderSearch.js

Use 'Search CAS' instead of 'CAS content' based on final feedback from CAS

change-cas-wording

---

.github/workflows/testacceptance.yml
.github/workflows/testjs.yml
.github/workflows/testrb.yml
Gemfile
Gemfile.lock
spec/rails_helper.rb

The PR changes our CI such that on each pull request, the code coverage for the Ruby unit tests is reported.
Coverage is reported using the [report-lcov](https://github.com/marketplace/actions/report-lcov) action. The action requires the additional dependency [simplecov-lcov](https://github.com/fortissimo1997/simplecov-lcov).
Also, the three workflow files (testacceptance.yml, testjs.yml, testrb.yml) have been cleaned up a bit.

Report Ruby unit test coverage on CI

---

.github/workflows/ci.yml

The linting action (https://github.com/HeRoMo/pronto-action) seems to crash with push triggers.
Run it only when the workflow was triggered by a PR.

Skip linting job on push triggers

---

.github/workflows/ci.yml

Our linting (https://github.com/HeRoMo/pronto-action ) and coverage (https://github.com/zgosalvez/github-actions-report-lcov) actions require write access to the base repository in order to comment on PRs. 
However, when these actions are run in the context of a PR from a fork, they fail since forks don't have write access.
This is why we're skipping these actions in case of PRs from forks.
See https://github.com/orgs/community/discussions/26829 and https://github.com/nyurik/auto_pr_comments_from_forks.

Skip linting and coverage on PRs from forks

---

app/api/chemotion/sample_api.rb

It seems the latest upgrade of grape gem results into failing ruby unit tests. This pull request fixes it.

Fix ruby unit tests

---

app/jobs/download_analyses_job.rb
app/jobs/export_collections_job.rb

This patch fixes a bug, where the delayed_job was referring to the wrong property.
This caused the delayed_job to fail, when the user requested to download all analysis files
or to recreate `.edit.jdx` files.

renamed app.root_url in delayed jobs (v1.4 backport)

---

.service-dependencies
CHANGELOG.md

Chemspectra should be version 0.10.16 in case of process jcamp files with multiple `LINK` valued

Update information for hot fix version of chemspectra

---

.devcontainer/devcontainer.json
.devcontainer/post_create.sh
.gitignore
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

This PR adds a development container for Visual Studio Code (in the following referred to as "devcontainer" for brevity):
https://code.visualstudio.com/docs/devcontainers/containers.
The PR is meant to unify our existing attempts at providing a devcontainer:
* https://github.com/JanCBrammer/Chemotion_ELN_devcontainer
* https://github.com/ptrxyz/chemotion/tree/v1.0.3D0.1/client-vscode-remote-container
Those attempts are fragmented and not as well maintained as they could be. By providing the devcontainer as part of the ELN repo, I'm hoping that it'll be more accessible and salient, and therefore easier to use and maintain.
The devcontainer uses the Dockerfile and compose configuration that are already in the repository:
* https://github.com/ComPlat/chemotion_ELN/blob/1709c2edcb9ecf7dd4471b2 …

Development container for Visual Studio Code

---

app/models/concerns/attachment_jcamp_aasm.rb
spec/models/concerns/attachment_jcamp_aasm_spec.rb

853 read fid data from processed data

---

.github/workflows/ci.yml

Currently, CI breaks on PRs that are triggered by Dependabot, since Dependabot doesn't have write permissions:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events

Skip actions triggered by Dependabot

---

db/seeds/shared/admin.seed.rb

Currently, the admin account isn't activated during seeding. Therefore, if I want to log into the account in the test or development environment, I have to manually activate the account first, which is tedious.
With the fix in this PR, the admin account is activated when seeding the database (e.g., with `bundle exec rake db:setup`).

Activate admin account during seeding

---

Dockerfile.chemotion-dev
config/environments/development.rb
run-ruby-dev.sh

M1 macs use an ARM-based processor architecture, which will be picked up by docker generating ARM linux images by default. So we specifically use the linux/amd64 image to create a non-ARM image to work with.  This way all compilation and package installations (google-chrome-stable does not have ARM packages for example) run the expected way.
Another issue is that docker for mac uses qemu as backend on M1 macs, which does not support inotify. Because of that, the EventedFileWatcher used in the development environment does not work and had to be replaced by a FileWatcher without usage of inotify

Improve Dev setup for M1 macs

---

app/packs/src/models/ResearchPlan.js
spec/javascripts/packs/src/models/ResearchPlan.spec.js

BugFix of #1106 - UI crash when editing table in researchplan

---

app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js

Equivalent information in reagent table can get lost with one misplaced click.
[760](https://github.com/ComPlat/chemotion_ELN/issues/760)

Issue on input of equivalent value 

---

app/assets/stylesheets/reaction.scss
app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
app/packs/src/fetchers/ReactionsFetcher.js
app/packs/src/models/Reaction.js
app/packs/src/models/Sample.js
spec/features/reaction_coefficiency_spec.rb
spec/javascripts/factories/ReactionFactory.js
spec/javascripts/factories/SampleFactory.js
spec/javascripts/packs/src/models/Reaction.spec.js
spec/javascripts/packs/src/models/Sample.spec.js

This pull request aims to fix the issue https://github.com/ComPlat/chemotion_ELN/issues/1076 . 
The theoretical mass of the products in a reaction was sometimes not shown anymore or a NaN value was printed out. 
If one switched the reference sample the values were not updated.
A second aim was to move the tooltip from the yield textbox to the amount textbox
Changes done:
- added the possibility to calculate the max theoretical amount in a reaction to the reaction and sample model
- fixed some typos
- added an initial calculation of the max amounts right after fetching a reaction from the server
- added an calculation of the max amount on a change of the reaction
- removed the tooltip from the yield textbox and added it on the amount textbox

1076 bug fix theoretical mass not shown

---

app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js

Fixes #1052.
The warning
`AG Grid: tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen? `
was displayed whenever `sizeColumnsToFit()` was called on components that were part of a tab that wasn't currently rendered:
https://github.com/ComPlat/chemotion_ELN/blob/02b6702a7ce21e5d4f40c048ea280cf0769d40a6/app/packs/src/apps/mydb/elements/details/reactions/greenChemistryTab/GreenMetrics.js#L43
https://github.com/ComPlat/chemotion_ELN/blob/02b6702a7ce21e5d4f40c048ea280cf0769d40a6/app/packs/src/apps/mydb/elements/details/reactions/greenChemistryTab/GreenMaterialGroup.js#L84
The problem is fixed by unmounting all tabs (and their associated components) that are currently not rendered.
Note that this has the nice side effect …

Only mount visible tab in reaction detail modal

---

app/usecases/attachments/annotation/annotation_updater.rb

Add opacity as styling element to svg allowlist. 
The original reason why i created the branch was the issue found by Silvia that free hand drawings without a filling got a filling after the save. But i can not reproduce it. 
@reviewer, please check if you can reproduce the problem.

Minor image annotation fixes

---

app/packs/src/apps/mydb/elements/details/ElementDetailSortTab.js
app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
app/packs/src/apps/mydb/elements/list/ElementsTableSettings.js
app/packs/src/apps/mydb/elements/tabLayout/TabLayoutCell.js

Fixes #1203
Issues with tab layout popups:
- Partially fixed - `shouldUpdatePosition` not working for
- `ElementsTableSettings`' popup
- `ElementDetailSortTab` when reaction details are open
**- 21/03 - This can be fixed by forcing the components to update when window is resized.**
- Minor UI fixes as of 22/03, popups now within their respective sections, and now move with button when windows are scrolled.

Fix tab layout popups

---

CHANGELOG.md
app/api/chemotion/attachment_api.rb
app/api/chemotion/public_api.rb

so that to avoid Err_Response_Headers_Multiple_Content_Disposition in chrome

AttachmentAPI: quote filename in content-dispostion header

---

app/usecases/attachments/annotation/annotation_loader.rb
app/usecases/attachments/annotation/annotation_updater.rb
app/usecases/attachments/load_image.rb
spec/usecases/attachments/annotation/annotation_updater_spec.rb
spec/usecases/attachments/load_image_spec.rb

Eased the access to derivatives in the shrine context. (https://shrinerb.com/docs/plugins/derivatives)
Also fixed a bug that prevents converting a annotated svg file into another svg file.

Ease shrine deriv access

---

app/api/chemotion/report_api.rb
app/models/report.rb
app/models/report_template.rb
app/packs/src/apps/admin/AdminHome.js
app/packs/src/apps/mydb/elements/details/reports/Paramize.js
app/packs/src/apps/mydb/elements/details/reports/ReportContainer.js
spec/models/report_spec.rb

- disabled Admin Report Template management  and set paths for report type (do not use the report_template.attachment (also due to #1259 ))
- save report type  in report (fix wrong assignment)
- fall back to standard report if the report-template does not exist anymore in the db

1260 report UI to not break if a report template cannot be found

---

app/api/entities/container_entity.rb
spec/api/entities/container_entity_spec.rb
spec/factories/containers.rb

[Screencast from 17.04.2023 11:26:03.webm](https://user-images.githubusercontent.com/26220177/232443475-2ae30bc3-661e-4e17-b1ce-e9fcd6c3ae82.webm)

missing index in container entity

---

lib/datacollector/mailcollector.rb

fix `undefined method `path' for #<Mail::Part:0x00005d945a53c310> `

Mail-collector: write tmp file to pass path

---

app/packs/src/apps/home/WelcomeMessage.js
app/views/pages/about.haml

- avoid caching the welcome message  on the **Home** page
- replace changelog content with external link from the **About** page

1285 do no cache the welcome message

---

.devcontainer/post_create.sh

The removed command is a duplicate of https://github.com/ComPlat/chemotion_ELN/blob/cd7cb6c597b155be0e6506e4e6137e429ad9f3be/package_postinstall.sh#L36

Remove redundant command from devcontainer configuration

---

app/models/sample.rb
lib/svg/reaction_composer.rb
lib/tasks/svg.rake

- fall back to another css selector in case the molecule SVG was created by ketchersrv
- added rake task to regenerate sample/molecule SVGs

1267 reactants from reagent list do not appear above reaction arrow

---

.env.development
app/api/chemotion/editor_api.rb

The editor api has been updated to use PUBLIC_URL

http callback for onlyoffice updated

---

app/packs/src/components/navigation/GroupElement.js
app/packs/src/components/navigation/UserAuth.js

- Updated ui admin rights
- All admins can now delete/add members from/to the group or delete the groups
- Normal users can only delete themselves
- The "admin by" field now have all the admins and not only the creator
- Creating change to admin button for admins is complicated and is like a new feature. Was not implemented at all? Should it be implemented?
Fixes ComPlat/chemotion#10

updating group admin ui

---

app/api/chemotion/attachment_api.rb
app/models/attachment.rb
spec/api/chemotion/attachment_api_spec.rb
spec/factories/attachments.rb
spec/factories/samples.rb
spec/models/attachment_spec.rb

This pull request will fix the bug https://github.com/ComPlat/chemotion_ELN/issues/1340 .
It will add annotated images into the zip folder if user downloads a container dataset.

1340 download of annotated image not working

---

app/packs/src/components/contextActions/ModalReactionExport.js

How to reproduce the bug:
* select a collection as well as one or multiple reactions from that collection
* click `Export reactions from selection` in the upper task bar / menu
* click `Smiles Export` in the  `Reaction Smiles Export` modal that's popping up
* the generated file is empty except for "{"error":"columns is invalid"}"
Once the bug is fixed (see diff in this PR), repeat the procedure above.
Now the generated file contains the expected Smiles output.

Fix bug in `Export reaction from selection`

---

app/packs/src/components/contextActions/InboxButton.js
app/packs/src/components/contextActions/NoticeButton.js
app/packs/src/utilities/timezoneHelper.js
config/locales/en.yml
spec/javascripts/utils/timezoneHelper.spec.js

Fixes https://github.com/ComPlat/chemotion/issues/12
Fixes https://github.com/ComPlat/chemotion/issues/20
- used "prettier" to reformat the code.
- solved eslint issues
- getting the timezone String from backend to correctly present the local time
- DidMount has now startActivityDetection to make the notification button always available
- Did some ui change on the notification button because its size and centering were off
What is new for users:
- the notification button is now a bell instead of the messaging icon and be always shown in the default status when notification = 0.
- it will change to yellow and notification counter will start counting whenever there are notifications
- the text "message" is now "notification"
- the button has now the right size comparable to the button next …

notification timestamps and formatting notification button

---

app/api/entities/sample_task_entity.rb

The target amount for the given sample should be displayed in the Chemobile app.
So we need to expose the field via api.

Expose target amount in sample task api

---

.vscode/tasks.json

Enabled starting the delayed job worker in the devcontainer; doesn't require a separate / additional container during development.

Add delayed job worker to tasks.json

---

app/views/users/registrations/new.html.haml

- adding asterisks for the Password and Password confirmation fields-
Before:
After:

adding missing asterisks while signing up

---

app/api/chemotion/message_api.rb
app/api/entities/application_entity.rb
app/api/entities/channel_entity.rb
app/api/entities/comment_entity.rb
app/api/entities/device_metadata_entity.rb
app/api/entities/inbox_entity.rb
app/api/entities/matrice_entity.rb
app/api/entities/message_entity.rb
app/api/entities/private_note_entity.rb
app/packs/src/apps/admin/GroupsDevices.js
app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
app/packs/src/apps/mydb/elements/details/researchPlans/wellplatesTab/EmbeddedWellplate.js
app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
app/packs/src/apps/mydb/elements/details/screens/ScreenDetails.js
app/packs/src/apps/mydb/elements/details/screens/researchPlansTab/EmbeddedResearchPlanDetails.js
app/packs/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
app/packs/src/apps/mydb/inbox/AttachmentContainer.js
app/packs/src/apps/mydb/inbox/DatasetContainer.js
app/packs/src/components/comments/CommentDetails.js
app/packs/src/components/comments/CommentList.js
app/packs/src/components/common/CommentModal.js
app/packs/src/components/contextActions/NoticeButton.js
app/packs/src/components/generic/GenericElDetails.js
app/packs/src/components/navigation/UserAuth.js
app/packs/src/utilities/timezoneHelper.js
config/locales/en.yml
spec/javascripts/utils/timezoneHelper.spec.js

- use formatDate utility to format displayed timestamps
(reduce the number of  'import  moment.js' )
- Entity: return time zone in timestamp
- more entities are now using  the same exposure (expose_timestamp) for timestamps
- shoudl resolve timezone diff in comment-feature  and notification-feature

Unify datetime format

---

app/packs/src/components/calendar/Calendar.js

In the agenda tab of the calendar feature, all-day events were not consistently displaying 'all day' (see https://github.com/ComPlat/chemotion/issues/26). For example, a two day event displayed '12:00 am' for day 1 and 'all day' for day 2. For clarity, this has been corrected. 
An alert for the user to enter a title (mandatory field) when creating events has also been added.

Calendar allday events not shown consistently

---

app/api/chemotion/user_api.rb
app/models/user.rb
app/packs/src/components/navigation/GroupElement.js
app/packs/src/components/navigation/UserAuth.js
app/packs/src/fetchers/UsersFetcher.js

- New endpoint to allow UsersFetcher to change group admins
- New set/unset button
- Users have more friendly groups.
- Window is set now to 80%
Possible user errors that are handled:
- Unsetting yourself as admin if you are the only admin -> Not allowed and shows info popup
- Deleting a user if he is admin -> Allowed, but will also remove his admin status -> Instead of unsetting admin and then deleting, this can be done just by deleting
- Adding user where, when no user is selected to add. -> Add button is turned off, until a user is selected.
Images:
Old UI:
New UI:
Popup when removing yourself as admin, if you are the only admin:

Groups ui revamp and making group admins set/unset admins 

---

app/packs/src/utilities/routesUtils.js

When selecting an already open sample in the sample list, the server reloads and thus the user loses any unsaved changes without a warning (see https://github.com/ComPlat/chemotion/issues/19).
Solution: when the user selects an element in the list, if it is already opened, the server simply switches to the tab without reloading. In this way, the current unsaved changes are retained.

Unsaved sample changes retained when reselected from list

---

.eslintrc

add one new eslint rule:
max line length max 120 signs, ignoring comments

add max line length eslint rule

---

app/jobs/send_calendar_entry_notification_job.rb

also set Job's `max_attempts` to 1
when email sending fails (eg wrong configuration), avoid client notification to be repeated.

Calendar Notification: rescue SMTP error to avoid repeat notif

---

app/packs/src/components/container/ContainerDataset.js

Fix for https://github.com/ComPlat/chemotion/issues/18.
Solution: the attachment preview for each dataset is created just once so that it doesn't incorrectly trigger the 'unsaved data will be lost' warning.

opening a dataset without making changes

---

app/api/chemotion/sample_task_api.rb
app/packs/src/apps/mydb/collections/sampleTaskInbox/SampleTaskCard.js
app/packs/src/apps/mydb/collections/sampleTaskInbox/SampleTaskInbox.js
app/packs/src/fetchers/SampleTasksFetcher.js
app/packs/src/stores/mobx/SampleTasksStore.jsx
app/usecases/sample_tasks/create.rb
spec/api/chemotion/sample_task_api_spec.rb

While reviewing the current state of the Chemobile App, the wish came up to be able to delete open sample tasks.
This PR implements the ELN-side of this feature request.
It adds a delete button on sample tasks in the inbox, which in turn deletes the sample task and any associated scan results.
Please take note, that this only applies to open (i.e. not yet applied) sample tasks and scan results. Once a sample task is completed (meaning that the resulting value has been written into the real_amount fields within the sample), the sample task is no longer available for deletion (otherwise we would lose the ability to check if the real_amount_value was set by a sample task).
Additionally, this pull request includes some cosmetic changes to the sample task inbox, that came up within review. …

Allow deletion of SampleTasks and fix SampleTask Inbox scroll issues

---

app/api/chemotion/sample_task_api.rb
app/packs/src/apps/mydb/collections/sampleTaskInbox/SampleTaskInbox.js

Small convenience feature: newly created sample tasks will appear on top of the sample task list within the sample task inbox

Always sort new sample tasks on top of list

---

app/api/chemotion/reaction_api.rb
app/api/chemotion/sample_api.rb
app/packs/src/models/Sample.js

* fix navigation to existing sample without permission:
when a query to  fetch sample by id returns 401, the _not accessible_ panel should be rendered
* now also render the info panel for record (sample/reaction) not found (404)

fix: display the not-accessible panel for 401 status on sample fetched by id

---

app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
spec/javascripts/factories/AttachmentFactory.js
spec/javascripts/factories/ResearchPlanFactory.js
spec/javascripts/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.spec.js

This PR solves the issue #1398. 
After saving a researchplan the preview images were not visible anymore. That came from an asynchronous reloading of the preview image by changing the property "preview" of an attachment. But then the frontend was not refreshed by a setState (..). 
I fixed the problem by forcing a rerendering after the property was changed.
I also fixed several eslint errors but one, because i could not check the functionality ( openOffice editing) on my local machine.

1398 image annotation tool image preview does not work as expected

---

app/packs/src/apps/mydb/collections/sampleTaskInbox/SampleTaskInbox.js
app/packs/src/stores/mobx/SampleTasksStore.jsx

toSorted is only available in really new browsers, which is unfortunately not a given within academia.
Therefore the function call was replaced with another sorting routine that uses basic JS array sort()

Bugfix: replace toSorted with manual sorting in SampleTaskInbox

---

app/api/chemotion/attachment_api.rb
app/models/concerns/attachment_jcamp_aasm.rb
spec/api/chemotion/attachment_api_spec.rb
spec/factories/attachments.rb

Fix: When the user saves a sample, only send POST requests to chemspectra if the bagit.jdx and bagit.peak.jdx hasn't already been generated.

Fix - duplicate jdx files

---

app/packs/src/apps/mydb/App.js
package.json
package_postinstall.sh
yarn.lock

This PR updates the citation-js library to version 0.6.8. With that update they now fixed the problem with names imports and we can get rid of the post install library manipulation.
As explained in the corresponding issue https://github.com/ComPlat/chemotion_ELN/issues/1417 there is now another patch of the library that it would now not only accept DOIs but also SICIs.

1417 doi not accepted

---

app/packs/src/apps/mydb/elements/details/literature/DetailsTabLiteratures.js

This PR fixes #1505.
It fix the wrong mapping of fetched literature to the component state.

fix: fixed wrong literatures mapping

---

app/api/chemotion/reaction_api.rb
app/packs/src/fetchers/BaseFetcher.js

prevent unexpected sorting in case when the user profile.data.filter is missing and incorrect params sort_column is sent by the client (update_at instead of created_at)
more thorough resolution should come with #1461

fix: reaction sort column default to created_at

---

app/api/chemotion/sample_api.rb
app/jobs/import_samples_job.rb
app/packs/src/fetchers/SamplesFetcher.js
lib/export/export_excel.rb
lib/export/export_sdf.rb
lib/export/export_table.rb
lib/import/import_samples.rb
lib/import/import_sdf.rb
spec/api/chemotion/sample_api_spec.rb
spec/jobs/import_samples_job_spec.rb

Enhance import samples for sdf

---

package_postinstall.sh

SassC::SyntaxError: Error: "var(--ag-internal-calculated-line-height)" is not a number for `min'
on line 2381:11 of stdin, in function `min`
from line 2381:11 of stdin
>>   height: min(var(--ag-internal-calculated-line-height), var(--ag-internal-p

fix: assets precompilation css issue

---

app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
app/packs/src/components/ChemicalTab.js
app/packs/src/fetchers/BaseFetcher.js
app/packs/src/fetchers/ChemicalFetcher.js
spec/javascripts/factories/AttachmentFactory.js
spec/javascripts/helper/setup.js
spec/javascripts/packs/src/apps/mydb/elements/details/researchPlans/ImageAnnotationEditButton.spec.js
spec/javascripts/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.spec.js
spec/javascripts/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetailsFieldImage.spec.js
spec/javascripts/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.spec.js
spec/javascripts/packs/src/components/ChemicalTab.spec.js
spec/javascripts/packs/src/fetchers/BaseFetcher.spec.js
spec/javascripts/packs/src/fetchers/ChemicalFetcher.spec.js

- I noticed, there are mulitple warnings when running `npm test` 
This PR solves these warnings:
075aa5a8dfb2046fdecb9a972e4c1a4597fe5309 solves 
```
Warning: Failed prop type: Invalid prop `bsSize` of value `middle` supplied to `Button`, expected one of ["lg","large","sm","small","xs","xsmall"].
at Button (/home/chemotion-dev/node_modules/react-bootstrap/lib/Button.js:56:29)
```
7c0c90ac6e3eb0db14e471ea63588c2c8385b363 solves
```
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
```
2bdfdbe5cab5f758bbea357f2ecebc6f439d8e6b and …

Refactor: "yarn test" errors & warnings

---

app/views/pages/settings.haml

Fix show example label for reaction

---

app/api/chemotion/attachable_api.rb
app/packs/src/fetchers/AttachmentFetcher.js
app/packs/src/fetchers/GenericElsFetcher.js
app/packs/src/fetchers/ResearchPlansFetcher.js
app/packs/src/fetchers/WellplatesFetcher.js
app/packs/src/models/ResearchPlan.js
spec/javascripts/packs/src/models/ResearchPlan.spec.js

This PR fixes https://github.com/ComPlat/chemotion_ELN/issues/1558 which came from https://github.com/ComPlat/chemotion/discussions/70 and https://github.com/ComPlat/chemotion_ELN/issues/1549 .
The problem was a wrong tablename in the ` attachable_type` column in table **attachments**. Instead of 'ResearchPlan ' the entry was 'Labimotion::ResearchPlan' . By that rails could not resolve the polymorphic association and could not fetch the saved attachments of a researchplan. 
The wrong entry was set in the method `element_helper.rb:162` inside the new rails gem of labimotion.
The current solution is:
- Do not use the labimotion endpoint for uploading attachments `/api/v1/generic_elements/upload_generics_files`
- Use instead the already used (in wellplates) endpoint  ` …

1558 no attachments after research plan save

---

app/packs/src/components/calendar/CalendarEntryEditor.js
app/packs/src/components/generic/GenericElDetails.js
app/packs/src/components/navigation/search/Search.js

feat: expand calendar function to generic element

---

bin/run_mail_collector
lib/datacollector/collector_helper.rb
lib/datacollector/collector_helper_set.rb
lib/datacollector/datacollector_file.rb
lib/datacollector/datacollector_folder.rb
lib/datacollector/dc_logger.rb
lib/datacollector/fcollector.rb
lib/datacollector/filecollector.rb
lib/datacollector/foldercollector.rb
lib/datacollector/mailcollector.rb

Changed Mail collector rules:
Attachment e-mails...
1) ... can be sent to multiple chemotion instances
2) ... can be sent to chemotion user in 'cc' or 'to'. The e-mail addresses in to and cc are treated equally
3) ... can be sent to different e-mails. All emails in "cc" or "to" belonging to a registered user will trigger the creation of an attachment. All non-registered e-mails are ignored.
Additionally, if an e-mail throws an error the collector keeps running. -> see mailcollector line 25
[Issue](https://github.com/ComPlat/chemotion_ELN/issues/1560)

Changed Mail collector rules

---

app/assets/stylesheets/collection_management.scss
app/packs/src/apps/mydb/collections/CollectionTabs.js
app/packs/src/apps/mydb/collections/MyCollections.js
app/packs/src/apps/mydb/collections/MySharedCollections.js
app/packs/src/apps/mydb/collections/SharedWithMeCollections.js
app/packs/src/apps/mydb/collections/SyncWithMeCollections.js

- It makes the root collection undraggable to mitigate the bug in the used library mentioned in the linked issue
- It makes the buttons undraggable as mentioned in the issue
- There are still some draggable areas in the tree component. I tried to minimize them but they are still there. In my opinion instead of fixing these remaining issues we should look for another tree library which is not as old and undocumented than the current one.
Because it is mainly frontiest frontend stuff and css i skipped js-unit testing as i would only test trivial attributes.

fix: collection management right click on the add button to not drag things around

---

app/api/chemotion/reaction_api.rb
app/api/chemotion/research_plan_api.rb
app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsField.js
app/packs/src/apps/mydb/elements/labels/ElementResearchPlanLabels.js
app/packs/src/fetchers/ReactionsFetcher.js
app/packs/src/fetchers/ResearchPlansFetcher.js
app/packs/src/models/Reaction.js
spec/api/research_plan_api_spec.rb
spec/factories/research_plans.rb

PR for [1001](https://github.com/ComPlat/chemotion_ELN/issues/1001)

feat: show research plan links in reaction

---

Dockerfile.chemotion-dev
run-js-dev.sh
run-ruby-dev.sh

We regularly face the situation that other developers update tool versions (nodejs for example) and forget to update the Docker files (especially if they don't use them anyway). 
I updated the Dockerfile.chemotion-dev, to no longer install a hardcoded Ruby and NodeJS version. Instead, the run-ruby-dev.sh script checks if ASDF is installed and then installs the tools to the versions defined in .tool-versions.
This way, developers using the Docker dev environment, don't have to rebuild their docker container all the time, when a new nodejs version is used.

Improve Dev Setup by autorecognizing the installed tool versions

---

app/models/molecule.rb
app/models/sample.rb
yarn.lock

due to the scrubber library lowercasing all attribute names some properties are not rendered in the browser.
In this case beads with a gradient  in molecule, sample and reaction were not displayed in browser and were also missing after conversion in png in doc report.
(successiv gsub benchmarked as faster than gsub with regex and a dict)

fix: camelcasing attributes for proper display of SVGs

---

app/packs/src/models/Reaction.js

Prior to this bug fix, if  `fromUnit` and `toUnit` are identical, `convertTemperature` throws:
```
TypeError
conversionTable[fromUnit][toUnit] is not a function
```

fix: temperature conversion

---

lib/chemotion/meta_schmooze/meta_schmooze.rb
lib/chemotion/quill_to_html.rb
lib/chemotion/quill_to_plain_text.rb
spec/lib/chemotion/quill_to_plain_text_spec.rb

common input parser for quill-to-html and quill-to-plain-text 
now handle empty delta to prevent (db/migration) errors
```
Schmooze::JavaScript::TypeError:
only `insert` operations can be transformed!
```

refactor: dry schmooze tools

---

spec/lib/chemotion/jcamp_spec.rb

Fix jcamp spec for CI runner

---

app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js

The `Tooltip` of the "+" button in the "Variations" tab did not appear anymore on hover over.
That was fixed by wrapping the button in a `<span>`.
@PiTrem, could you have a quick look (I feel like we won't need another reviewer for this)?

fix: show `Tooltip` on "+" button in "Variations" tab

---

app/packs/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.js
app/packs/src/apps/mydb/elements/details/researchPlans/analysesTab/ResearchPlanDetailsContainers.js
app/packs/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersAux.js
app/packs/src/components/common/SpectraEditorButton.js

I moved the `SpectraEditorButton` component to a dedicated file.
Before, the component was (re-)defined in three other component files (presumably copy-pasted):
`ReactionDetailsContainer`, `ResearchPlanDetailsContainer`, and `SampleDetailsContainer`.
FYI, the button looks like this (in the `Analyses` tab):

refactor: extract` SpectraEditorButton` to dedicated component

---

app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js

…roperties tab, does not render the change in the reaction scheme after saving sample change

fix: amount change of a reaction product from the sample properties tab

---

app/packs/src/components/common/SpectraEditorButton.js
app/packs/src/components/nmriumWrapper/NMRiumDisplayer.js

In read-only collections, NMRium and chemspectra are enabled while the 'close with save' buttons are hidden.
Closes https://github.com/ComPlat/chemotion/issues/114
[nmrium_enabled.webm](https://github.com/ComPlat/chemotion_ELN/assets/112618970/08990f97-d386-4ee0-995e-f93aeb24e532)

feat: enable nmrium in read only collection

---

app/api/chemotion/search_api.rb
app/packs/src/components/searchModal/forms/TextSearch.js

To avoid the crash at the advanced search, i added an empty search result for the cell line block at the advanced search endpoint.
In another feature we had to include the search for the cell lines into the advanced search analogue to other elements.
Also fixed the missing icons in the search frontend.

fix: advanced search not working - cell-line

---

Gemfile.lock
app/models/container.rb
app/models/reaction.rb
app/models/screen.rb
app/models/wellplate.rb
db/migrate/20230630140647_fill_new_plain_text_description_fields.rb
db/migrate/20230814121455_fill_new_plain_text_content_field_at_containers.rb
lib/chemotion/meta_schmooze/meta_schmooze.rb
lib/chemotion/quill_to_html.rb
lib/chemotion/quill_to_plain_text.rb
lib/export/export_research_plan.rb
lib/export/export_table.rb
lib/quill_utils.rb
spec/lib/chemotion/quill_to_html_spec.rb
spec/lib/chemotion/quill_to_plain_text_spec.rb

- prevent spawning node process if quill ops is blank
- filter empty insert to prevent the node conversion to throw error
- add option to filter image insert from ops before conversion
- pass input as file if input too large (also prevent `Errno::E2BIG (Argument list too long - node)`)
- quill convert as class method
- modularize common quill utilities
chore: revert noko upd

refactor: rb quill delta converter

---

.devcontainer/devcontainer.json
.devcontainer/post_create.sh
docker-compose.dev.yml
prepare-ruby-dev.sh
run-ruby-dev.sh

With https://github.com/ComPlat/chemotion_ELN/pull/1665 the node installation is moved from `Dockerfile.chemotion-dev` to `run-ruby-dev.sh`, which is not executed by the devcontainer. That's why the devcontainer would not start. Running `run-ruby-dev.sh` as part of the devcontainer startup would introduce a lifetime depdendency from the rails server (running in the `app` container) to the devcontainer. This is why we extracted the installation of node into a new script, which is now called from `prepare-ruby-dev.sh` as well as `postCreateCommand` command in devcontainer.

fix: devcontainer

---

app/packs/src/components/contextActions/ContextActions.js
app/packs/src/components/contextActions/CreateButton.js

Issues fixed: 
- Synchronized collections:
Even if I give the other person all rights, he/she is not able to import elements (neither samples nor reactions) into the collection.
- [1793](https://github.com/ComPlat/chemotion_ELN/issues/1793)

fix: disabled create button for synced collection

---

app/usecases/search/conditions_for_advanced_search.rb
spec/api/chemotion/search_api_spec.rb

This PR solves the problem with the **advanced search** for **durations** and **temperature** search for reactions.
In the DB in the table reactions in the column duration the duration is encoded as as string like "1 Day(s)" or  "4.5 Hour(s)" or other ways. In the search method the postgres sql function" [extract( )]( https://www.postgresql.org/docs/14/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) is used which requires a certain string content like above.
If the value of the column violates that containt this leads to a crash. 
To avoid this the sql part for generating that query is augmented with an CASE clause which checks if the content is valid and only then executes the extract function.
In the DB in the table reactions in the column temperature the information about different …

1815 user feedback advanced search for temperature or time

---

app/views/users/registrations/edit.html.haml

(cherry picked from commit ccb0989abe91bce99fa675e853bd9da37dafcd1f)
Bug fix:
- In Change Password, on clicking 'Delete Account' button, the user will now be asked for confirmation

fix: delete user account without confirmation

---

app/models/container.rb
app/models/reaction.rb

convert quill to plain text in background job to speed up saving containers or reactions

refactor: quill to plain text call-backs 

---

app/api/chemotion/attachment_api.rb
app/packs/src/apps/mydb/inbox/DeviceBox.js
app/packs/src/fetchers/AttachmentFetcher.js
app/packs/src/stores/alt/actions/InboxActions.js
app/packs/src/stores/alt/stores/InboxStore.js

fix: avoid multiple API calls to load the inbox when datasets/attachments are deleted
add the bulk delete API endpoint for attachments
Closes https://github.com/ComPlat/chemotion/issues/140

fix: avoid multiple API calls to load the inbox when datasets/attachments are deleted

---

app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js

fix: handle sample xref properties for when xref is null

---

config/structure_editors.yml.example
db/migrate/20240328150631_update_editor_feat.rb
db/schema.rb

- The default editor id for ketcher2 config is missing. Although the ELN Admin can set it, this migration set the default value.
NB: a missing or wrong `editor` value will prevent the option to show up in the Structure Editor Modal
- Also updated the yml example file on pair with the doc (https://github.com/ComPlat/chemotion_saurus/pull/321)

chore: default ketcher2 configs in UI Feature

---

.github/workflows/ci.yml

A `rubocop` error breaks the linting job in our CI since version 1.63.
An upcoming release is (hopefully) fixing the error: https://github.com/rubocop/rubocop/issues/12823.
This PR doesn't directly address the error. I just noticed and removed the (ineffective and obsolete) pinning of `rubocop` while I was investigating the CI failure.
Note that the removed comment refers to another, unrelated `rubocop` problem (with version 1.38).

chore(CI): unpin `rubocop` gem

---

app/packs/src/apps/mydb/elements/list/ElementsTableSampleEntries.js

Fixes: https://github.com/ComPlat/chemotion_ELN/issues/1847
I showed all the buttons and symbols that I saw for the aligment (see picture)
Some quick and dirty techniques were used because most of the components use css classes that are not universal and serve specific needs. Changing css would break other things
Before: 
After:

Fix: sample entry alignment and spacing

---

app/packs/src/apps/mydb/inbox/DeviceBox.js
app/packs/src/stores/alt/actions/InboxActions.js
app/packs/src/stores/alt/stores/InboxStore.js

Fixed issue where the container/dataset fetch API call was triggered multiple times for each click on deviceBox in the inbox

fix: the container/dataset fetch API redundant requests being made for each click on deviceBox in the inbox

---

app/usecases/search/structure_search.rb

This PR patches a crash that occurs if the user searches with the **structure search** and has in its **profile** the **cell line element** visible. The process requires in a search result an result part associated to all visible elements.
Cell lines were missing, so i put an empty result set to a result.

fix: add cell lines to structure search result

---

.gitignore
app/api/chemotion/admin_user_api.rb
app/packs/src/apps/admin/UserManagement.js
app/packs/src/fetchers/AdminFetcher.js

Restore deleted Account option in Admin UI:
- Restore deleted account if there is no existing name_abbreviation
- Restore and deactivate the account if name_abbreviation exists
- If multiple deleted users exist:
-  If user ID parameter is not provided :
- Display the existing deleted accounts to the admin
-with ID: restore the deleted account

feat: admin can restore deleted user account

---

app/api/chemotion/admin_api.rb
app/api/chemotion/admin_user_api.rb
app/packs/src/apps/admin/MatrixManagement.js
app/packs/src/apps/admin/UserManagement.js
app/packs/src/apps/admin/generic/GenericAdminModal.js
app/packs/src/fetchers/AdminFetcher.js
spec/api/chemotion/admin_api_spec.rb

refactor!: user managment
- better notification (no alert)
- clean api endpoints:
```
Find all users     GET  /api/v1/admin/users 
Find top (5) matched user by name and by type     GET  /api/v1/admin/users/byname 
restore deleted user account    POST  /api/v1/admin/users/restoreAccount 
create new user account    POST  /api/v1/admin/users 
Find user by ID     GET  /api/v1/admin/users/:user_id 
update user account     PUT  /api/v1/admin/users/:user_id 
delete user account  DELETE  /api/v1/admin/users/:user_id 
reset user password     PUT  /api/v1/admin/users/:user_id/resetPassword
get user profile     GET  /api/v1/admin/users/:user_id/profile
```

feat: admin can delete single user account

---

app/packs/src/fetchers/ReactionsFetcher.js

Fixed the bug that an image in a dataset in a reaction could not be **annotated** correctly. The problem was a missing update of the **container of the reaction**, only the samples were updated.

fix: add updating of annotations also in reaction container

---

.gitignore
Gemfile
Gemfile.lock
app/jobs/init_cron_jobs_job.rb
app/jobs/pubchem_cid_job.rb
app/jobs/pubchem_lcss_job.rb
config/initializers/delayed_job_config.rb
spec/config/initializers/delayed_job_spec.rb
spec/jobs/init_cron_jobs_job_spec.rb

- When the app is initializing and go through the delayed_job initializer
- so that job's run_at does not default to ~ created_at
Any action initializing the app (rake, bin/delayed_job, rails c...) will run the delayed job initializer and queue the recurring jobs.
Unfortunately at this stage the of the initialization, though the cron is set properly, the next run_at is not. Instead it defaults to ~Time.now every time. 
This PR:
- fix: the issue by calculating the next run_at and setting it
- refactor: move fetching, validation, and setting of the cron values for recurring jobs out of the delayed_job initializer
into an `init` job.  Use fugit to validate cron input
- test: unit test + testing on the initializer queueing
NB more cleaning needed but for another time:
- keep …

fix: ensure  wait_until is set for cron delayed jobs 

---

app/packs/src/apps/mydb/elements/details/literature/LiteratureCommon.js

This PR fixes an issue that there is a blank page when the reference manager is opened. The problem was a missing default value of the citationMap in the LiteralType component. The property is now optional and prefilled with the default values.

fix: add default value for citationMap

---

Dockerfile.chemotion-dev

`Chrome` was used to drive our end-to-end tests. Since we no longer run end-to-end tests (for now) this PR removes the `Chrome` installation to reduce bloat and speed up build time. Confirmed with @PiTrem.

chore: Remove `Chrome` from devcontainer

---

db/seeds/development/users.seed.rb

This PR addresses #1943.
How to test this PR?
1. Check out `main`.
2. Run `bundle exec rails db:setup`.
3. Open the app and click ![image](https://github.com/ComPlat/chemotion_ELN/assets/30125107/b43eb066-5468-4af6-a3f7-4f581c157dce) in one of the reactions detail modals.
The app should throw (in the browser's dev console):
```
TypeError: Cannot read properties of null (reading 'attachments')
at Function.getAttachments (BaseFetcher.js:127:1)
at Function.updateAnnotationsInContainer (BaseFetcher.js:137:1)
at Function.updateAnnotationsInReaction (ReactionsFetcher.js:97:1)
at ReactionsFetcher.js:81:1
ElementActions.js:620 TypeError: Cannot read properties of undefined (reading 'type')
at Store.handleUpdateElement (ElementStore.js:1327:1)
at Store.handleUpdateLinkedElement …
```

Add root container to seeded reactions

---

app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js

fix: coefficient display value defaults to 1

---

app/packs/src/apps/mydb/elements/list/ElementsTable.js

This pull request is a bug fix to scroll to the top of the elements table on change.

fix: element list scrollbar back to the top after page change

---

app/api/chemotion/attachment_api.rb
spec/api/chemotion/attachment_api_spec.rb

This PR will fix a problem if the user tries to **download** an **attachment** from e.g. a research plan if the plan is in a **synchronized** or shared **collection**.

fix: attachment permission validation to allow access on shared items

---

app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
app/packs/src/utilities/MathUtils.js
spec/javascripts/utils/MathUtils.spec.js

This PR addresses #1948.
The reaction variations table accepts only a period (i.e., ".") as decimal separator for numeric entries. The goal is to allow a comma and period as decimal separators. In the current codebase, there are at least two ways to achieve this.
The package is used in the `NumeralInput` component (which in turn is used in "Elemental composition" section of `SampleDetails` component via `ElementalCompositionCustom` and `ElementalCompositionGroup`components). I decided not to use `numeral`:
- The package is dead (last commit 7 years ago: https://github.com/adamwdraper/Numeral-js).
- We're limited to an outdated version (of the dead package).
I decided against using the custom logic:
- It's not re-usable outside of the component and its not trivial to extract since it's …

feat: Allow comma and period as decimal separators in reaction variations table

---

CHANGELOG.md
app/models/molecule.rb
config/default_missing.yml
config/initializers/ketcher_service.rb
config/initializers/structure_editors.rb
config/structure_editors.yml.example

Only the validation section is config dependentant.
ensure  Rails.application.{structure_editors,ketcher_service} is defined and an instance
of ActiveSupport::OrderedOptions, when config/{structure_editors,ketcher_service}.yml:
-- is missing or
-- is present but nothing defined for the current environment
- add minor validation when loading the config yml
- also resolve #1929: proper key in the yml example file

refactor: generalise initializers:  ketcher_service structure_editors

---

app/packs/src/apps/mydb/elements/details/cellLines/analysesTab/EditModeHeader.js
app/packs/src/apps/mydb/elements/list/AttachmentList.js
app/packs/src/components/common/ImageModal.js
app/packs/src/fetchers/AttachmentFetcher.js

This PR fixes the problem that in an container image preview the thumbnail image does not match the magnified image if the user clicks on it if there is an annotated version of the image (see #1927).
It also fixes that for cell lines the magnify function was not enabled.
As discussed with the reviewer the fix does not fully solve the problem. After annotating the image in the container the preview image is instantly updated but the magnified image still needs a reload of the element. It would need a relative big refactoring of the logic to achieve an instant updating. Since there is an issue that requires this modificationanyway, I would like to plead in favor of solving this remaining problem in issue https://github.com/ComPlat/chemotion_ELN/issues/1928

fix: dataset thumbnail image to match magnified preview when annotated

---

app/packs/src/apps/mydb/collections/CollectionSubtree.js

fix to resolve bug where collection sub tree collapses when a different sub tree is selected.

fix: collection tree not to collapse on select

---

app/api/api.rb
app/api/chemotion/collection_api.rb
app/api/chemotion/literature_api.rb
app/api/helpers/collection_helpers.rb
app/models/collections_cellline.rb
app/models/concerns/collectable.rb
app/models/concerns/collecting.rb
app/usecases/cell_lines/create.rb
spec/api/collection_api_spec.rb
spec/models/collections_cellline_spec.rb

- API: clearer mapping of param keys <-> element Models
- Models: robust method to get the associated Collection{Element} model from given element model without relying on naming assumptions  (avoid string operation with table, column, reflections names)
- CollectionsCell-line: reuse available concern logic

refactor: getting collection-element model for given model

---

app/packs/src/apps/commandAndControl/CnC.js
app/packs/src/apps/commandAndControl/FocusNovnc.js

Changes related to : https://github.com/ComPlat/chemotion_ELN/issues/2006
Add an option to force the resize of the remote display : 
- Fix the jumping viewport when first click on the remote device
- Automatically hide the device list on entering focus mode
- Automatically show the device list on entering blur mode
- Automatically enter the blur mode if on focus mode when unhidding the device list

feat: vnc page - add option to fit display width

---

app/packs/src/models/Wellplate.js
spec/javascripts/fixture/wellplates/wellplate_2_2_from_server.js
spec/javascripts/fixture/wellplates/wellplate_2_3_empty.js
spec/javascripts/fixture/wellplates/wellplate_8_12_empty.js
spec/javascripts/packs/src/models/Wellplate.spec.js

Fixed a bug : if wellplate was fetched from server its wells were initialised empty.

fix: skip empty well initialization on existing wellplate

---

app/api/chemotion/reaction_api.rb
app/api/entities/reaction_entity.rb
app/packs/src/apps/mydb/elements/details/reactions/ReactionDetails.js
app/packs/src/apps/mydb/elements/details/reactions/ReactionDetailsMainProperties.js
app/packs/src/apps/mydb/elements/details/reactions/ReactionDetailsShare.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
app/packs/src/components/OlsComponent.js
app/packs/src/models/Reaction.js
db/migrate/20240711120833_add_vessel_size_to_reaction.rb
db/schema.rb
lib/import/import_collections.rb
spec/api/entities/reaction_entity_spec.rb

…l size field in reaction scheme tab in frontend

feat: add vessel size property to reaction

---

app/packs/src/apps/mydb/elements/details/researchPlans/attachmentsTab/ResearchPlanDetailsAttachments.js
app/packs/src/apps/mydb/elements/details/wellplates/attachmentsTab/WellplateDetailsAttachments.js
app/packs/src/components/container/ContainerDatasetModalContent.js
app/packs/src/stores/mobx/AttachmentNotificationStore.jsx
spec/javascripts/factories/AttachmentFactory.js
spec/javascripts/factories/AttachmentNotificationFactory.js

This PR extends the refresh of Third party app attachments to wellplates and container datasets.

3PA: apply UI refresh to all areas

---

.gitignore
.service-dependencies
bin/chem-get-git-src.sh
bin/chem-ket2-install.sh
bin/chem-node-package-install.sh
bin/chem-utils.sh

(requires jq or yq, unzip, git)
- default version locked in `.service-dependencies`
- move assets to public/editors/ketcher2/{pre}built/{version}/{standalone|remote}
- symlink to `public/editors/default` and `public/editors/ketcher2/standalone` (unless real dir present)
Examples:
- install the recommended version from provider artifacts
```sh
bin/chem-ket2-install.sh
```
- build and install the latest version from source
```sh
bin/chem-ket2-install.sh -b -s epam/ketcher@master
```
Usage:
```
bin/chem-ket2-install.sh --package-src <user/repo:version> --artifact-type <type> --build-from-source
-s, --package-src <src>          Optional: specify the src and version(tag, branch, or commit) for KETCHER2 as defined in the .service-dependencies file.
Default from .service-dependencies file
-t, …
```

build(dev): fetch assets, or source code to build assets, of ketcher2

---

app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js
app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
app/packs/src/apps/mydb/elements/details/samples/propertiesTab/TextRangeWithAddon.js

This PR includes rearranging of fields within SampleProperties.
- Rename fields as requested
- Rearranging of fields within the tab
Changes not included as part of this PR:
- Adding new 'Decompose' field with checkbox
- Provide dropdown select options for Form and Color fields

Sample properties UI layout rework

---

spec/api/chemotion/chemical_api_spec.rb
spec/spec_helper.rb

test: fix flaky tests in chemical_api_spec (webmock)

---

app/assets/stylesheets/CustomHeader.scss
app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsCellComponents.js

I bundled four UI updates in this PR. The updates are small and atomic and I want to avoid the overhead of four separate PRs. There's one commit for each of the four updates, i.e., you best review this PR commit by commit.
1. cc008b321c69b22f6d42b7f9ebec9f882e9ffcdf: The first column didn't have a header name. It's now called "Tools".
2. 67f60e69344dfcf3bf88e7dd062bca1b2c70fa9b: The columns automatically fit their width to their content. Prior to this commit, this auto-sizing caused the entire table to "twitch" whenever there was a click on the header or a cell-edit. This commit removes the twitching.
3. bd0c2547aec7e31218ad5afb1972fdb472e77b83: This commit highlights two header elements. A) the column title on hover-over, and B) the currently active sort icon. A) is meant as an …

Reaction variations UI updates

---

app/api/chemotion/code_log_api.rb
app/packs/src/components/common/PrintCodeButton.js
app/packs/src/components/common/PrintCodeModal.js
app/packs/src/components/contextActions/ScanCodeButton.js
app/pdfs/code_pdf.rb
public/json/printingConfig/defaultConfig.json

feat: multiple print-code config

---

.service-dependencies
app/api/chemotion/admin_api.rb
app/jobs/admin_job.rb

allow admin to trigger the ket2 installation script by api call :
get  `/api/v1/admin/jobs/queue_task?task=install_ketcher2`

feat(dev): admin api to trigger recommended ket2 installation

---

app/assets/stylesheets/sample.scss
app/packs/src/components/generic/GenericElDetails.js

Align the style of the analysis section in both the linked view and the analysis tab.

fix: align style of the analysis section

---

app/api/chemotion/profile_api.rb
app/packs/src/components/contextActions/ScanCodeButton.js
app/packs/src/stores/alt/actions/UserActions.js
spec/api/chemotion/profile_api_spec.rb

Purpose of this PR is to fix ketcher-options response fail.
Error occured with new account or when user has not saved settings before.
------------------------------

fix: ketcher-options fetching on load

---

app/assets/stylesheets/sample.scss
app/packs/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js

This PR contains fix based on the feedback received on Sample Properties UI rework.
- Maintain even spacing between basic properties fields
- Enable fields to be responsive on smaller screens to avoid scrolling
- Resize StereoRel and StereoAbs to add more space to molecule name
- Align decoupled and anhydrous checkboxes appear underneath each other( responsive )
- Improve overall responsivenss
Related to:
https://github.com/ComPlat/chemotion_ELN/pull/2066

Fix-Sample properties UI changes

---

app/api/chemotion/profile_api.rb
app/packs/src/apps/mydb/App.js
app/packs/src/utilities/UserTemplatesHelpers.js

Purpose of this PR is resolve duplicate tab browser crash -> Reason UserTemplates:
https://github.com/user-attachments/assets/777e8784-aec8-4c3c-9566-398a80b662dc
-----------------------------

Fix user template duplicate tab crash

---

app/packs/src/fetchers/BaseFetcher.js
app/packs/src/models/ResearchPlan.js
spec/javascripts/packs/src/models/ResearchPlan.spec.js

This PR will fix the crash if a user wants so **edit** a **researchplan** inside a **screen**. In the current state there are no attachments linked as a property in a screen researchplan. This would lead to a null pointer access. 
By adding a **default empty array** and adding a **guard clause** at the annotation updater the bug should be gone.

fix: save research plan inside screen

---

app/packs/src/components/managingActions/ManagingModalSharing.js

filter  params from ui-state is missing the implementation of elementNames as async  (see 6294592248).
This  prevents selected element to be shared.
```
TypeError: elementNames(false).forEach is not a function
```

fix: element filter when selecting ui-state

---

app/packs/src/apps/mydb/elements/list/AttachmentList.js

url handler app expects:
`chemotion://?url=eln.adress...` instead of `chemotion://eln.adress...`

fix: proper link format for the url handler app

---

app/assets/stylesheets/application.scss

To prepare the app for the Bootstrap update in https://github.com/ComPlat/chemotion_ELN/pull/1930/files, the asset pipeline needed a small refactoring.
The `require_tree .` directive loads all files in the `app/assets/stylesheets/` directory (including subdirectories) and compiles every individual file and then concatenates the results (only in production, in development all files are added in the html <head>) into application.css.
Doing this, every file is treated as if it were the only CSS file in existence, which poses some issues when we want to use sass imports. In our bootstrap update branch, we defined a global override file with variable definitions that change or extend some bootstrap functionality. This import is done once in the application and afterwars, all files that are …

refactor: asset pipeline to prepare for bootstrap update

---

app/packs/src/apps/mydb/elements/details/samples/SampleDetails.js

```
Cannot read properties of undefined (reading 'filter')
```

fix: type error when sample has no collection tag data on saving sample

---

app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsCellComponents.js

Make edit function visible for reaction variation notes

---

app/assets/stylesheets/components/QuillEditor.css
app/assets/stylesheets/global-styles/package-mods/react-select.scss
app/packs/src/components/common/Select.js
app/packs/src/components/common/SpectraEditorButton.js
app/packs/src/components/container/ContainerDatasetField.js
app/packs/src/components/reactQuill/ToolbarDropdown.js
app/packs/src/components/textTemplateToolbar/ToolbarTemplateCreator.js

- Remove add and delete css at quill editor
- Remove required at ContainerDatasetField
- Remove pullRight and add margin for icons at SpectraEditorButton
- Remove refs at selects of quill editor custom toolbar
- Set key for quill editor custom toolbar

fix: quill editor and other warnings

---

app/packs/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsBody.js
app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsField.js
app/packs/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js
app/packs/src/apps/mydb/elements/details/samples/propertiesTab/ElementalCompositionCustom.js
app/packs/src/apps/mydb/elements/list/ElementsList.js
app/packs/src/apps/mydb/elements/list/ElementsTable.js
app/packs/src/apps/mydb/elements/list/ElementsTableSampleEntries.js
app/packs/src/apps/mydb/inbox/InboxModal.js
app/packs/src/components/UserLabels.js
app/packs/src/components/managingActions/ManagingActions.js
app/packs/src/components/navigation/Navigation.js
app/packs/src/components/navigation/search/AutoCompleteInput.js
app/packs/src/components/navigation/search/Search.js
app/packs/src/stores/alt/actions/UIActions.js
app/packs/src/stores/alt/stores/UIStore.js
app/packs/src/utilities/routesUtils.js

This PR fixes some minor issues that came up while implementing the [new navigation structure](https://github.com/ComPlat/chemotion_ELN/pull/2211) designed by shapefield. Extracting those issues into a PR so they can be reviewed separately without the navigation restructuring.

chore: Minor fixes & improvements

---

app/assets/stylesheets/legacy/chemical-tab.scss
app/packs/src/apps/mydb/elements/details/NumericInputUnit.js
app/packs/src/components/ChemicalTab.js
app/packs/src/components/contextActions/ModalExport.js
app/packs/src/components/searchModal/forms/SampleInventoryFieldData.js
lib/export/export_chemicals.rb
lib/import/import_chemicals.rb
spec/lib/export/export_chemicals_spec.rb

feat: expiration date and storage temperature fields in inventory

---

.service-dependencies

* fix: conditional header generation for NMR JCAMP export [#219](https://github.com/ComPlat/chem-spectra-app/pull/219)
* fix: data normalization and improve handling of runs in JcampMSConverter [#220](https://github.com/ComPlat/chem-spectra-app/pull/220)
* chore: Bump werkzeug from 3.0.3 to 3.0.6 [#217](https://github.com/ComPlat/chem-spectra-app/pull/217)

fix(spectra): bump service chem-spectra-app to v.1.2.4

---

app/packs/src/fetchers/AttachmentFetcher.js

When deleting attachments after adding them in a dataset and before saving, they are no longer uploaded and deleted afterwards.

fix: no more uploading of deleted attachments

---

lib/reporter/docx/detail_reaction.rb
spec/lib/reporter/docx/detail_reaction_spec.rb
spec/support/reaction_report_setup.rb
spec/usecases/reactions/update_materials_spec.rb

fix: reaction report generation for gas products when the vessel size is not given

---

app/models/concerns/sequence_utilities.rb
app/models/matrice.rb
db/migrate/20230323115540_matrice_user_provider.rb
db/migrate/20230323160712_matrice_molecule_viewer.rb
db/migrate/20230420121233_matrice_comment.rb
db/migrate/20240530000001_remove_user_labels_from_matrix.rb
spec/factories/matrices.rb
spec/models/matrice_spec.rb

try to manage matrice id on create so that new matrices does not increment the sequence over 32 as this leads error when recalculating the users.matrix.
on matrice create:
- reset the sequence to the latest  i used id (no unused id)
- force delete of matrices that are out of range
also ensure matrice migration are not trying to create duplicate entries, as that leads to increment the sequence while raising an error.
TODO: move matrice data  to a proper db/seed/

fix(db): matrice sequence

---

app/packs/src/stores/alt/stores/UIStore.js
db/schema.rb

this.state.currentSearchSelection is not set in detail / advanced search
therefore condition removed; the other condition is sufficient
closes https://github.com/ComPlat/chemotion/issues/217

fix: selecting all pages with advanced/detail search corrected

---

.env.production.example
bin/delayed_job

using ENV['DELAYED_JOB_ARGS']
- force starting the worker using 'start' instead of 'run' to allow named queues when DELAYED_JOB_ARGS is defined
- shutting down all remaining worker processes if one dies to trigger the container restart
- better log last job that might have silently killed the worker process.
example  for 3 process (2 with named queues):
DELAYED_JOB_ARGS="DELAYED_JOB_ARGS="--pool=transfer_to_repo --pool=collect_data  --pool=* "

fix(worker): allow multiple delayed_job named-queue pools in the worker container

---

app/api/chemotion/reaction_api.rb
app/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
app/usecases/reactions/update_variations.rb
spec/usecases/reactions/update_variations_spec.rb

This PR addresses #2264.
How to test this PR?
1. Copy a reaction with variations.
2. Create / Save the copied reaction.
3. Navigate to the reaction's "Variations" tab.
Pre-PR, 3. results in the crash described in #2264.
Post-PR, 3. does not crash and shows the copied variations table with updated material IDs.
Copying all variations when copying a reaction might be undesirable.
That's why I've added a "Remove all Variations" button (with confirmation modal):

fix: Reaction Variations: Update variations' sample IDs when reaction is copied

---

app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js

column headers can/should displayed independently of the permission level.

allow header for yield/equiv. column in reaction scheme for shared collections with read only rights

---

app/api/entities/reaction_material_entity.rb
app/api/helpers/report_helpers.rb
app/models/reactions_product_sample.rb
app/packs/src/apps/mydb/elements/details/NumeralInputWithUnitsCompo.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroupContainer.js
app/packs/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
app/packs/src/components/common/ToggleButton.js
app/packs/src/models/Sample.js
app/usecases/reactions/update_materials.rb
db/migrate/20240917085816_add_conversion_rate_to_reactions_samples.rb
db/schema.rb
lib/import/import_collections.rb
lib/import/import_json.rb
lib/reporter/docx/detail_reaction.rb
spec/javascripts/packs/src/components/common/ToggleButton.spec.js

feat: Conversion rate

---

app/api/entities/reaction_material_entity.rb
app/api/helpers/report_helpers.rb
app/javascript/src/apps/mydb/elements/details/NumeralInputWithUnitsCompo.js
app/javascript/src/apps/mydb/elements/details/reactions/ReactionDetails.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroupContainer.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
app/javascript/src/components/common/ToggleButton.js
app/javascript/src/models/Sample.js
app/models/reactions_product_sample.rb
app/models/reactions_purification_solvent_sample.rb
app/models/reactions_reactant_sample.rb
app/models/reactions_sample.rb
app/models/reactions_solvent_sample.rb
app/models/reactions_starting_material_sample.rb
app/usecases/reactions/update_materials.rb
db/migrate/20240917085816_add_conversion_rate_to_reactions_samples.rb
db/schema.rb
lib/import/import_collections.rb
lib/import/import_json.rb
lib/reporter/docx/detail_reaction.rb
spec/factories/reactions_samples.rb
spec/javascripts/packs/src/components/common/ToggleButton.spec.js

feat: sample conversion rate (%) in a reaction scheme

---

app/api/chemotion/cell_line_api.rb
app/api/helpers/cell_line_api_params_helpers.rb
app/javascript/src/components/contextActions/CreateButton.js
app/javascript/src/components/contextActions/SplitElementButton.js
app/javascript/src/fetchers/CellLinesFetcher.js
app/javascript/src/stores/alt/actions/ElementActions.js
app/javascript/src/stores/alt/stores/ElementStore.js
app/javascript/src/utilities/CellLineUtils.js
app/models/cellline_sample.rb
app/usecases/cell_lines/copy.rb
app/usecases/cell_lines/split.rb
db/migrate/20240531112321_add_ancestry_to_cellline_sample.rb
spec/api/chemotion/cell_line_api_spec.rb
spec/factories/cell_line_sample.rb
spec/usecases/cell_lines/copy_spec.rb

rebased
see #1971 for original PR review

feat: split cell line

---

config/shakapacker.yml
config/webpack/development.js

this PR resolve the following issues when starting the wepack-dev-server
- initialization error:
```
failed to load command: bin/shakapacker-dev-server (bin/shakapacker-dev-server)
...
lib/shakapacker/dev_server_runner.rb:57:in `initialize': getaddrinfo: Name or service not known (SocketError)
```
(to reproduce when using docker-compose.dev.yml comment out  the env SHAPACKER_DEV_SERVER_HOST )
- infinite error :
```
....
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '.......
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '.......
...
```
- rm erb from shakapacker.yml as it appears to not be interpreted when starting skakapacker dev server and leads to the initialization error.
also rm …

build(dev): fix shakpacker config for the webpack-dev-server 

---

app/javascript/src/apps/mydb/elements/details/reactions/ReactionDetails.js

The save status of a reaction is indicated by the blue bar at the top of the reaction detail card.
Dark-blue means "no unsaved changes" and light-blue indicates "unsaved changes".
Currently, the color does not change back from light-blue to dark-blue upon saving changes.
To reproduce, change a reaction's temperature in the "Scheme tab" and subsequently save the reaction. The bar should turn from light-blue to dark-blue, which it doesn't. See https://github.com/ComPlat/chemotion_ELN/issues/2000 for a visualization of the color changes.
The cause of the missing color-transition is the following refactoring of the `componentDidUpdate` hook in `ReactionDetails`:
https://github.com/ComPlat/chemotion_ELN/pull/2196/files#diff-7a0497f1fbd063dc74585549f8849c2f7323ed96769b82c44208b91b1464b64d
This …

fix(UI): color-coding of save-status in reaction detail card

---

app/javascript/src/apps/mydb/elements/details/samples/SampleDetails.js

Rearrange the order of Elemental Composition in Sample Properties as below:
Chemical Identifiers, Elemental composition, My Labels, Private Note

refactor(UI):Rearrange the order of elemental composition

---

app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/Material.js

correct the formatting of a sample molarity from a reaction scheme, when pushing the details of it into the reaction description.
For example  `pyridine (14.7 mg, 190 μL, 186 μmol, 0.980M, 0.163 equiv) `   becomes
`pyridine (14.7 mg, 190 μL, 186 μmol, 0.980 M, 0.163 equiv)`
----------------------------------------------------------

style(UI): correct formatting of a sample molarity added to the description of a reaction

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.vs.yml
.devcontainer/pre_create.sh
.dockerenv.example
.gitignore
.vscode/tasks.json
docker-compose.dev.yml
prepare-nodejs.sh
prepare-nodejspkg.sh
prepare-ruby-dev.sh
run-js-dev.sh

- set env variables in the docker-compose.dev.yml to allow using
- prebuild images for the app and skip the building process 
NB not applicable for devcontainer at this stage (see other PR that introduce build args)
.devcontainer/docker-compose.vs.yml reset the image tags
- distinct postgres images
- distinct named volume for the db and homedir(asdf, gems, etc)
- add .dockerenv.example file to help settings those variables 
example
```
docker compose -f docker-compose.dev.yml --env-file .dockerenv.example up
```
- prevent .devcontainer to overwrite .env 
separate var for docker environment  vs  services environments
- rework the preparation scripts to better separate node packages
installation from ruby env installation. so that `yarn install`
is only run by the js container
- add …

build(dev): option for setting service image and volume names

---

app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/Material.js

This PR fixes an issue where the sample short label was missing from the tooltip when hovering over elements in the reaction scheme. The tooltip now correctly displays the short label.
Before : 
After : 
Issue linked:
Fixes [#2295](https://github.com/ComPlat/chemotion_ELN/issues/2295)

fix(UI): Display short label on reaction scheme hover

---

yarn.lock

```
Module not found: Can't resolve 'react-date-picker/dist/DateInput/DayInput' in '/home/chemotion-dev/app/node_modules/react-datetime-picker/dist'
node_modules/react-datetime-picker/dist/DateTimeInput.js
```
introduced with 827e33a (#2329)
ref: #2329

fix: module not found -  revert bump for react-date-picker patch

---

app/javascript/src/apps/mydb/elements/details/cellLines/analysesTab/AnalysesContainer.js
app/javascript/src/apps/mydb/elements/details/reactions/analysesTab/ReactionDetailsContainers.js
app/javascript/src/apps/mydb/elements/details/researchPlans/analysesTab/ResearchPlanDetailsContainers.js
app/javascript/src/apps/mydb/elements/details/samples/analysesTab/SampleDetailsContainersCom.js
app/javascript/src/apps/mydb/elements/details/screens/analysesTab/ScreenDetailsContainers.js
app/javascript/src/apps/mydb/elements/details/wellplates/analysesTab/WellplateDetailsContainers.js
app/javascript/src/components/common/AnalysisCommentBoxComponent.js
app/javascript/src/components/common/CommentBoxComponent.js
spec/javascripts/packs/src/components/AnalysisCommentBoxComponent.spec.js

feat: allow user to add a general comment on the analyses section of any element (not related to  commenting function on shared elements)

feat: add general comment field to analysis section of any element

---

app/models/notify_message.rb

introduced by rubocop formating
since: #2322
- NotifyMessage is a view with no primary key
- [find_each](https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_each) automatically `order by ` primary key
ref: #2322

fix: find_each order by on view notify_message

---

db/migrate/20250218160000_add_timestamps_to_reactions_samples.rb
db/schema.rb
spec/db/migrate/20250218160000_add_timestamps_to_reactions_samples_spec.rb

to allow migration 20250218160000 on existing records
since: 94903f239
refs: #2068

fix: relax not null policy on reactions_samples timestamps

---

app/javascript/src/apps/mydb/elements/details/screens/researchPlansTab/EmbeddedResearchPlanDetails.js

**Description:**
When Research Plan is drop in screen attachment it goes blank and throws the error "Cannot access expanded before initalization.". This has been fixed in EmbeddedResearchPlanDetails.js. 
since c85856e3936f

fix(UI): blank page on dropping research plan into a screen

---

app/javascript/src/fetchers/SamplesFetcher.js

uninitialized variable in a Sample fetcher
this appears to be old issue that only surfaced with  moving from webpacker to shakapacker (9fb09656f0)
refs: #2236

fix: limit initialize when copy sample

---

.github/workflows/ci.yml
package.json
yarn.lock

- @babel/preset-react@7.10.4  to ^7.26.3
- @babel/eslint-parser@^7.15.0 to ^7.26.8
- @babel/register@^7.11.5 to  ^7.25.9
- @wojtekmaj/enzyme-adapter-react-17@^0.6.3 to ^0.8.0
- mocha@^10.2.0 to ^11

chore: bump packages for @babel and test 

---

Gemfile
Gemfile.lock
app/api/chemotion/attachment_api.rb
app/javascript/src/components/generic/GenericElDetails.js
app/javascript/src/components/generic/GenericSGDetails.js
package.json
yarn.lock

This PR updates labimotion v2-rc and fixes the issue with downloading single attachment.
* dependencies updates:
-- Bumps [Labimotion](https://github.com/labimotion/labimotion) from 2.0.0.rc2 to 2.0.0.rc8
https://my.diffend.io/gems/labimotion/2.0.0.rc2/2.0.0.rc8
-- Bumps [chem-generic-ui](https://github.com/LabIMotion/chem-generic-ui/) from 2.0.0-rc15 to 2.0.0-rc18
https://github.com/LabIMotion/chem-generic-ui/compare/v2.0.0-rc15...v2.0.0-rc18
https://www.npmjs.com/package/chem-generic-ui/v/2.0.0-rc18

chore: bump labimotion-2.0.0 rc

---

.github/workflows/ci.yml
config/application.rb
config/initializers/eln_features.rb
db/migrate/20240808125800_init_rdkit_schema.rb
db/migrate/20240808125801_init_rdkit_table.rb
db/migrate/20240808125802_init_rdkit_functions.rb
db/schema.rb
db/seeds/shared/rdkit.seed.rb

refactor the setting of the rails configuration pg_cartridge:
- initialize value to 'none' (feature disabled - empty migration)
- use default value rdkit@4.4.0 if ENV not set
- validate cartridge name/ version format -> disable if not
- check if pg extension is available -> disable if not
- check if pg extension is installed -> enable and warn if not / expect migration to
be run
refactor the db/seeds/shared/rdkit.seed.rb:
- check if pg_cartridge is not 'none' -> settings correct and extension
available
- (re)run migrations if schema or mol tables is not there OR extension
is not installed (restoring db)
- more verbose log message
This ensures
- Rails.configuration.pg_cartridge is defined in any cases
- the app can boot if the db is not created yet and pg_cartridge is not
'none'
- ensure …

fix: enabling rdkit

---

app/javascript/src/apps/mydb/elements/list/ElementsTable.js
app/javascript/src/apps/mydb/elements/list/ElementsTableSampleEntries.js
app/javascript/src/models/Sample.js
app/javascript/src/utilities/SampleUtils.js

This PR fixes the collapse/uncollapse bug in the Sample table.
**Explanation of the current collapse/uncollapse feature in Sample based on this bugfix:**
top chevron btn:
- the btn that toggles many samples at once
grouping chevron btn: 
- the btn that toggles samples individually
initial  state -> action -> resulting state
given a list of 10 samples grouped by xxx
_Initial state:_
top chevron btn  : {to the bottom}
grouping chevron btn : {all to the bottom}
_action-> resulting state:_
1. click top chevron btn->[bottom (uncollapsed) to right (collapsed) and viceversa]
current state: top and grouping chevron btn - all to the right
2. click on grouping chevron btn for sample x-> grouping btn for x to the bottom (x is uncollapsed)
current state:
grouping chevron btn for sample x: to the …

fix: element list (un)collapse of sample group

---

app/javascript/src/apps/mydb/elements/list/ElementsTableSampleEntries.js

try to get the currently opened element and its type from the element store,
in case the targetType has not be defined and passed to the component (due to race condition as when loading the whole page)

fix: disabled drag-and-drop handle for list samples and molecules to reaction scheme

---

app/api/chemotion/inventory_api.rb
app/javascript/src/apps/mydb/collections/CollectionSubtree.js
app/javascript/src/apps/settings/InventoryLabelSettings.js
db/migrate/20240319000000_allow_nullable_inventory_fields.rb
db/schema.rb

- Allow resetting inventory labels
- Handle null values appropriately
- Update UI to reflect reset state
refactor: Improve collection selection handling
- Fix group selection behavior
- Clean up selection logic

feat: inventory label reset

---

app/jobs/message_incoming_data_job.rb
lib/datacollector/correspondence.rb

when creating a notification on incoming datacollector file
handle sender type 
to ensure it is from a user
if sender is
- [User] -> user
- [Device] -> try to default to a device user group
else use the first [Admin]
refs: #1736

fix: messaging user for incoming files from datacollector device

---

app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/Material.js

Problem:
- Switching units for gas products input fields in the gaseous reaction scheme is not available with invalid values
- This was causing unnecessary UI clutter and potentially confusing users
Solution:
- Modified the `gaseousInputFields` function to only show tooltips when:
1. The value is not defined (null, undefined, or 'n.d')
2. The unit is not in the list of non-switchable units (ppm, TON): Some fields like 'ppm' and 'TON' should not show unit switch tooltips at all
- Added a clear message "Unit switch only active with valid values" to guide users
- Extracted the input component to avoid code duplication
Changes:
- Added `noSwitchUnits` array to identify units that don't support switching
- Updated tooltip display logic to check both value existence and unit type …

fix(ui): improve unit switch behavior for reaction scheme gase phase inputs

---

app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsPurification.js

Description:
When we deleted some selected purification items in reaction, it was crashing now it has been fixed. There was a typo error in handlePurificationChange function. 
---------------------------------

fix(UI):  purification selection in Reaction - function length typo

---

app/javascript/src/components/contextActions/NoticeButton.js

when too many notification items are there i.e. greater than the size of the window they render out of the modal. 
This UI issue has been fixed with this PR.

fix(UI): notifications rendered out of modal when too many.

---

app/assets/stylesheets/global-styles/utilities/sizing.scss
app/javascript/src/components/sampleTaskInbox/SampleTaskInbox.js

to keep draggable modal content in the viewport and prevent offscreen un-interactable content

fix: Limit maximum SampleTaskInbox height

---

app/javascript/src/components/contextActions/ExportImportButton.js
app/javascript/src/components/contextActions/ModalImport.js

**Problem Description**
- The import functionality for chemicals is malfunctioning, resulting in files designated as chemicals being incorrectly processed as samples. Additionally, there is a mismatch between the title parameter in `ExportImportButton.js` and its expected usage in `ModalImport.js`.
**Proposed Solution**
- Delete the Option of "import chemicals to collections" from the header bar in `ExportImportButton.js`.
- Introduce checkbox into the import module `ModalImport.js`  to allow selection between importing as a chemical or a sample.
--------------------------------------------------------------------------------------------------------------------------------

fix: import functionality for chemicals

---

app/javascript/src/components/container/ContainerDatasets.js

Description:
When dragging attachments from the inbox, we previously had to create a dataset and drop items on it. The field as a whole was disabled. Now, you can drop attachments on the dataset even if it's empty. 
---------------------------------

fix: drag inbox file item on analysis having no dataset

---

Gemfile
Gemfile.lock
package.json
yarn.lock

LabIMotion Version 2.0.0 Release (RC to Final Release)
- Upgraded LabIMotion from 2.0.0.rc8 to 2.0.0.
- Upgraded chem-generic-ui from 2.0.0-rc18 to 2.0.0.

feat: labimotion 2.0.0

---

app/api/entities/reaction_variation_entity.rb
app/assets/stylesheets/global-styles/package-mods/ag-grid.scss
app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js
app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.js
app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js
app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.js
app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsReducers.js
app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.js
db/migrate/20250304140809_add_metadata_to_reaction_variations.rb
db/schema.rb
spec/factories/reactions.rb
spec/javascripts/helper/reactionVariationsHelpers.js
spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.spec.js
spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsMaterials.spec.js
spec/javascripts/packs/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsUtils.spec.js

This PR addresses #2296.
Columns can be selected via the blue "Select columns" button
which opens a modal for column selection.
Note that the column selection gets reset once the reaction details tab is re-mounted.
This will be fixed with an upcoming PR, which aims to persist the table layout (addressing #2363).
The corresponding documentation is over at https://www.chemotion.net/docs/eln/ui/details#variations-tab.

feat: user-selectable columns for reaction variations table

---

.service-dependencies

- spectra-app to [1.2.6](https://github.com/ComPlat/chem-spectra-app/releases/tag/v1.2.6)
- ketcher2 to [3.0.3](https://github.com/epam/ketcher/releases/tag/v3.0.3)

chore(service): bump spectra-app and ketcher2 requirements

---

app/javascript/src/components/contextActions/ExportImportButton.js

**PR Description:**
**Problem:** The import samples to collection button in the ExportImportButton component did not reflect the state based on the current collection's permissions, leading to incorrect enabling/disabling behavior.
**Fix:** Updated the state management logic in the onUIStoreChange function to ensure the button is enabled or disabled based on the collection's label, is_locked, is_shared, and permission_level.
----------------------------------------------------------------------------------

update state for import samples to collection button

---

db/migrate/20250306120000_fix_molfiles.rb
db/seeds/shared/molecules.seed.rb
lib/pub_chem.rb
lib/tasks/data/mol_structure.rake
lib/tasks/support/molecule_structure_curation.rb
spec/lib/tasks/data/mol_structure_spec.rb
spec/lib/tasks/support/molecule_structure_curation_spec.rb

- pubchem info request: ensure success status to process the response 
- process to handle molecule with corrupted molfiles and associated
samples:
- try to regenerate according to sample molfile or molecule smiles
- add migration and rake task data:molefile:fix
refs: #2255

chore(db): fix molecules and sample with faulty molfiles

---

app/api/entities/attachment_entity.rb

so that navigation  (opening element is not impeded)

fix: prevent attachment serialization errors when thumbnail previews cannot be retrieved

---

app/api/chemotion/molecule_api.rb
app/javascript/src/fetchers/MoleculesFetcher.js
app/javascript/src/stores/alt/actions/DetailActions.js
spec/api/molecule_api_spec.rb

**Problem**:
- The molecule names API endpoint was using inchikey as the lookup parameter, which is not unique anymore
**Solution**:
- Changed API parameter in MoleculeAPI names endpoint from 'inchikey' to 'id'
- Updated client-side code in MoleculesFetcher and DetailActions to match this change
- Updated tests to use id parameter in API requests
refs: #2444 
_____________________________________________________________________________________________

fix: use molecule ID instead of inchikey for names molecule api endpoint

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/global-styles/package-mods/react-svg-file-zoom-pan.scss
app/javascript/src/apps/mydb/elements/details/VersionsTableFields.js
app/javascript/src/components/common/SvgWithPopover.js

- ensure min-width for popover svg in list (regres from #2443)
- fix missing image css import
- ensure css class is passed to SvgWithPopover preview <img>
- history image preview: check src filename ext to infer which css class to use in SvgWithPopover
Notes: SvgWithPopOver could handle the mime type of the src instead of
having to pass additional props like isSvg or conditional default css class
refs: #2068, #2443

fix: css for image and svg in history tracker

---

app/models/user.rb
db/migrate/20250422105404_detype_obsolet_users.rb

to avoid history serialization error since Device is not a User anymore
```
ActiveRecord::SubclassNotFound
Invalid single-table inheritance type: Device is not a subclass of User
```
refs: #1736, #2068

fix(db): de-type deleted user-device

---

lib/pub_chem.rb
spec/lib/pub_chem_spec.rb

#2447 introduce parsing of multiline cid  to build the proper url. However the cid, if coming from the db, is likely to be integer 
Allow parsing of cid as integer
refs: #2447

fix: arg parsing to query pubchem by cid

---

app/assets/stylesheets/components/QuillEditor.css
app/assets/stylesheets/global-styles/bootstrap-mods.scss
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/Material.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/MaterialCalculations.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/MaterialGroup.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsPurification.js
app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js
app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldRichText.js
app/javascript/src/apps/mydb/elements/details/samples/FastInput.js
app/javascript/src/apps/mydb/elements/details/samples/SampleDetails.js
app/javascript/src/apps/mydb/elements/details/samples/propertiesTab/SampleForm.js
app/javascript/src/components/QuillEditor.js
app/javascript/src/components/reactQuill/ReactQuill.js

**UI Issues and Solutions - Detailed Implementation**
-----------------------------------------------------------
**Issue 1: QuillEditor Styling Inconsistencies**
Files Modified:
[QuillEditor.js]
[ReactQuill.js]
[ReactionDetailsScheme.js]
[ReactionDetailsPurification.js]
[ResearchPlanDetailsFieldRichText.js]
**Problem:** The quill-resize class was inconsistently applied across different components—sometimes on parent divs, sometimes missing entirely. This caused unpredictable rendering behavior with the rich text editors' inconsistent sizes.
**Solution:**
1. Moved the quill-resize class directly to the inner component in ReactQuill.js
2. Added the class to the div in QuillEditor.js
3. Removed unnecessary wrapper divs in multiple files
4. This ensures consistent styling hierarchy across …

fix(UI): layout and event propagation in sample and reaction card

---

lib/export/export_collections.rb
spec/lib/export/export_collections_spec.rb
spec/spec_helper.rb

when an attachment image is referenced in the research plan body but has been removed from the attachment list
it is not exported. and the export file cannot be processed.
With this PR the missing images are fetch and the association to the research plan is rebuilt in the export.

fix: research plan export with image attachment

---

.gitignore
app/jobs/import_collections_job.rb
lib/import/import_collections.rb

- Added functionality to track and report discarded attachments from research_plans during the collection import process
- Introduced a new method to generate a report for discarded attachments
- Updated the import job to include details about discarded attachments in the notification message

feat: enhance import process with discarded attachments of research_plans

---

app/javascript/src/components/structureEditor/StructureEditorModal.js
app/javascript/src/utilities/SvgUtils.js
app/javascript/src/utilities/UserTemplatesHelpers.js
spec/fixtures/svg/defMutationAlreadyProcessed.svg
spec/fixtures/svg/defMutationEmptyDefs.svg
spec/fixtures/svg/defMutationNoIds.svg
spec/fixtures/svg/defMutationWithId.svg
spec/fixtures/svg/defMutationWithUse.svg
spec/javascripts/utils/svg.specs.js

PR resolves a part of Issue: [#2277 ]( https://github.com/ComPlat/chemotion_ELN/issues/2277)
On saving Ketcher2 svg content modify svg defined Glyph id and their references. 
Modify Id would help avoid conflict in glyph id used in other reactions/svgs, specially with reactions.
On saving a reaction while using Ket2. The svg should have modified defined glyph ids.
Before: glyph-0-0
After: glyph-0-3_e15e902f
---------------------------------

fix: Sanitize SVG glyph IDs and references on Ket2 svgs

---

lib/chemotion/sanitizer.rb

ket1 solid support bead use <defs><radialGradient> that are references with `fill="url(...)`
re-mapping of index from b52a14704 does not cover this and break the references
this PR changes the selector to only re-index <g> descendants of <defs>
refs: #2483

fix: sample SVG solid support bead not visible

---

app/javascript/src/components/container/ContainerDatasetModalContent.js

Description:
This PR fixes the missing instrument suggestion dropdown in the dataset metadata form. The dropdown now renders correctly and handles overflow with scroll for long lists.

fix: show instrument suggestions dropdown in dataset metadata

---

app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariations.js

This PR prevents rendering the variations of new reactions that have not been saved yet.
It is an amendment of the fix in #2265.
The amendment is merely moving up the guard to prevent any logic from executing that relies on the integrity of the sample IDs in the variations of new, unsaved reactions (see #2265 for details).

fix: don't render variations of new, unsaved reaction

---

app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsComponents.js

In case a variations row didn't include a reference material, some downstream computations (e.g., `computeEquivalent`) were throwing errors because they tried accessing attributes on an `undefined` reference material. Thanks for the report @headri.

fix: guard against undefined reference material in reaction variations

---

app/javascript/src/apps/mydb/elements/details/reactions/variationsTab/ReactionVariationsAnalyses.js
app/javascript/src/apps/mydb/elements/list/reaction/ReactionVariations.js

- avoid cluttering list items if no variations is available
- also fix navigating from an analysis linked to a reaction  in the analyses-tab to the variations-tab

style(variation): badge only visible if variations present

---

app/javascript/src/apps/mydb/elements/details/reactions/schemeTab/ReactionDetailsScheme.js

**Problem/Bug:**
- The yield field was not displaying correctly on new reactions when no conversion rate was assigned.
- The original implementation used a conditional operator ([shouldDisplayYield ?? !displayYieldField](vscode-file://vscode-app/c:/Users/49172/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)) that caused ambiguous state toggling.
The condition checking for conversion rates in products was incorrectly negated, resulting in an incorrect boolean value for yield display.
**Fix:**
- Refactored the [switchYield](vscode-file://vscode-app/c:/Users/49172/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) function to use explicit if...else statements so …

fix(UI): correctly display yield field when conversion rate is null

---

.github/workflows/asset-precompilation.yml
.tool-versions
Gemfile
Gemfile.lock
package.json
yarn.lock

- set .tool-versions to use nodejs 22.16.0
- bump shakapacker from 8.0.2 to  '~> 8.3.0' 
(this allows webpack-cli v6 (>= 8.1))  [Changelog](https://github.com/shakacode/shakapacker/blob/main/CHANGELOG.md#v830---april-25-2025)
-  bump webpack-cli from 4 to 5
-  bump webpack-cli from 5 to 6 (6.0.1)
- bump webpack-dev-server from 4.15.2 to 5.2.1
- bump babel dependencies
- @babel/core@7.27.4
- @babel/preset-env@7.27.4
- @babel/plugin-transform-runtime@7
- ...
- remove unused dependencies uglifyify uglify-js (webpack uses terser)
- update browserslist db

chore: bump nodejs engine to 22.16.0 - bump shakapacker webpack and babel dep

---

app/assets/stylesheets/global-styles/utilities/detail-card.scss
app/javascript/src/apps/mydb/elements/details/DetailCard.js
app/javascript/src/apps/mydb/elements/details/GraphContainer.js
app/javascript/src/apps/mydb/elements/details/LiteratureDetails.js
app/javascript/src/apps/mydb/elements/details/cellLines/CellLineDetails.js
app/javascript/src/apps/mydb/elements/details/computeTasks/ComputeTaskContainer.js
app/javascript/src/apps/mydb/elements/details/deviceDescriptions/DeviceDescriptionDetails.js
app/javascript/src/apps/mydb/elements/details/formats/FormatComponent.js
app/javascript/src/apps/mydb/elements/details/reactions/ReactionDetails.js
app/javascript/src/apps/mydb/elements/details/reports/ReportContainer.js
app/javascript/src/apps/mydb/elements/details/researchPlans/ResearchPlanDetails.js
app/javascript/src/apps/mydb/elements/details/samples/SampleDetails.js
app/javascript/src/apps/mydb/elements/details/screens/ScreenDetails.js
app/javascript/src/apps/mydb/elements/details/wellplates/WellplateDetails.js
app/javascript/src/components/generic/GenericElDetails.js
app/javascript/src/components/metadata/MetadataContainer.js

This patch introduces a common DetailCard component for shared styling.
Before this change the whole right-side detail view scrolled on
overflow, including tabs and headers. With this change the tab bar and
detail view headers stay fixed and only individual detail view contents
scroll on overflow.
Before
https://github.com/user-attachments/assets/ab57a3d3-3d2a-445a-ac9c-d4b938b4b8a8
After
https://github.com/user-attachments/assets/8db88aff-1079-423d-8590-b2364e4ccf3e

fix(UI): make element detail tabs and header sticky 

---

app/api/chemotion/collection_api.rb
app/api/chemotion/share_collection_api.rb
app/api/helpers/collection_helpers.rb
app/models/concerns/taggable.rb
app/models/concerns/tagging.rb
app/packs/src/apps/mydb/collections/SharedWithMeCollections.js
app/packs/src/apps/mydb/elements/labels/ElementCollectionLabels.js
app/packs/src/components/managingActions/ManagingModalSharing.js
app/policies/element_policy.rb
app/usecases/sharing/take_ownership.rb
db/migrate/20240119141814_migrate_element_tag_data.rb

Initial fixes for element tag
- it displays the element tag again
- minor text change
- fix the issue with accepting of ownership
- fix the deletion of a shared collection
- fix the creation of a shared collection with all the elements when no label is entered
-  fix collection-sharing with groups

Current shared collection refactoring changes

---

app/javascript/src/apps/mydb/elements/details/ViewSpectra.js

This PR extends the multi-spectra display functionality to support HPLC-UV-Vis, UV-Vis, and NMR (¹H and ¹³C) spectra.
Demo Videos:
HPLC:
https://github.com/user-attachments/assets/30b357c3-eee1-48c2-be7c-bfff69e905e7
NMR:
https://github.com/user-attachments/assets/e529801d-d37f-4672-934f-b5a74a37ff78
UV-Vis:
https://github.com/user-attachments/assets/2c80e0a0-c84d-4482-b436-b91fbebe4b8a

feat: display multi spectra for HPLC UV-VIS, NMR and UV

---

app/api/chemotion/collection_api.rb
app/api/chemotion/ols_terms_api.rb
app/api/entities/sample_entity.rb
app/models/attachment.rb
app/models/cellline_sample.rb
app/models/collection.rb
app/models/container.rb
app/models/device_description.rb
app/models/ols_term.rb
app/models/sample.rb
app/usecases/sharing/take_ownership.rb
config/initializers/ancestry.rb
db/migrate/20250616122740_add_index_on_ancestry_to_samples.rb
db/migrate/20250616123935_add_index_on_parent_id_to_containers.rb
db/migrate/20250701121906_remove_ancestry_indices.rb
db/migrate/20250701121907_migrate_ancestry_to_materialyzed_path2.rb
db/migrate/20250701121908_add_ancestry_indices.rb
db/schema.rb
db/seeds/development/00_persons.seed.rb
spec/api/collection_api_spec.rb
spec/models/attachment_spec.rb
spec/models/cellline_sample_spec.rb
spec/models/collection_spec.rb
spec/models/container_spec.rb
spec/models/device_description_spec.rb
spec/models/sample_spec.rb

- add index on samples.ancestry (SampleEntity => children_count)
- add index on containers.parent_id: this improve drastically the serialization of container as ContainerEntity is self recurring on object.children
- call sample parent_id from ancestry directly to avoid another query
- upgrade ancestry path to materialized_path2

perf: add indices to improve sample serialization

---

app/javascript/src/models/Reaction.js

**Description**
When updating a sample that is part of a reaction, the coefficient value was being lost due to it not being carried over from the original sample. This fix ensures the existing coefficient is retained by extracting it from the reaction's current material and reapplying it to the updated sample before refreshing the reaction state.
-------------------------------------------

fix: persist coefficient value on material change in reaction scheme

---

app/javascript/src/components/sampleTaskInbox/SampleTaskSidebarButton.js
app/javascript/src/stores/mobx/SampleTasksStore.jsx

Before this change, the weighing task sidebar button would only open the inbox. Now it toggles it.

fix(UI): Allow weighing task inbox to be toggled from sidebar

---

app/javascript/src/components/contextActions/ExportImportButton.js
app/javascript/src/components/contextActions/ReportUtilButton.js

solves the same issue for prep-v2.1 [ PR#2606 ](https://github.com/ComPlat/chemotion_ELN/pull/2606)
--------------

fix(UI): menu action buttons initialized before user data is available

---

app/api/helpers/report_helpers.rb

**Problem Description:**
-  [Issue #2577](https://github.com/ComPlat/chemotion_ELN/issues/2577)
- "Select all pages" export fails when inventory/chemicals fields are selected - works fine with default fields but crashes when any inventory field is included 
**Solution Implemented:**
- Refactored chemical query logic:
-  updated chemical_query method to handle collection-based exports similar to the working build_sql_sample_sample pattern 
- Fixed SQL join behavior - changed from JOIN to LEFT JOIN to include all samples even when they have no chemical/inventory data, preventing sample exclusion 
- Added proper collection boundaries - implemented consistent collection filtering logic for both "select all" and "select specific" scenarios to ensure all samples in the collection are processed …

fix: chemical export queries with select all samples

---

app/api/chemotion/search_api.rb
app/javascript/src/components/searchModal/forms/SearchModalFunctions.js
app/javascript/src/components/searchModal/forms/SearchResult.js
spec/api/chemotion/search_api_spec.rb

If you search with two or more conditions and the first is empty, it will result in an invalid SQL statement.
This is fixed here. Now the empty condition is ignored.

fix(search): invalid statement in advanced search

---

app/api/chemotion/third_party_app_api.rb
app/api/helpers/third_party_app_helpers.rb

- DRY building the attachment url for direct download
- add wildcard route to fetch the attachment with token (needed for NMRium wrapper #2512)
-> api/v1/public/third_party_app/{token}(/*)

refactor(api): attachment access url for third party apps

---

.github/workflows/asset-precompilation.yml
.github/workflows/ci.yml
.tool-versions
Dockerfile.github-ci
prepare-nodejs.sh

also:
- build(dev): prevent to automatically upgrade nodejs unless NODEJS_FORCE_INSTALL is set to 'true'

chore: bump nodejs engine from 22.16.0 to 22.17.1

---

Gemfile.lock
db/seeds/development/03_vessels.seed.rb

With this change we create only one vessel template per user vessel in seeds.
This way the seeds respect the uniqueness constraint introduced in https://github.com/ComPlat/chemotion_ELN/pull/2441.

fix(build): development vessel template seeds

---

app/api/chemotion/report_api.rb
app/javascript/src/fetchers/ReportsFetcher.js
spec/api/chemotion/report_api_spec.rb

When exporting as SDF: Forgetting to select samples and using export samples from selection as SDF you get a htm file which contains an error message.
Added nil check to avoid the error and return an empty txt file instead.

fix: handle report generation request with an empty selection of items

---

app/javascript/src/stores/alt/stores/SpectraStore.js

Keep original XUNITS/YUNITS/UNITS as UTF-8 and render them without stripping non-ASCII.
Symbols like "³" appeared as boxes or wrong characters in the UI.
Use the UTF-8 labels from the backend
Before the fix :
After the fix:
Loaded JCAMP files with Unicode labels and verified unit label show the correct characters

fix(spectra): Display Unicode unit labels correctly

---

app/javascript/src/components/structureEditor/KetcherEditor.js
app/javascript/src/utilities/ketcherSurfaceChemistry/AtomsAndMolManipulation.js
app/javascript/src/utilities/ketcherSurfaceChemistry/canvasOperations.js
app/javascript/src/utilities/ketcherSurfaceChemistry/eventHandler.js
lib/chemotion/sanitizer.rb
spec/javascripts/data/ketcher2_mockups.js
spec/javascripts/packs/src/components/Ketcher2.spec.js

PR Provides feature to allow user to attach text-nodes as labels with the solid surface templates:
- Add, remove textNodes with templates
- Label moves with the templates, as the shapes is moved.
Image:
Video:
https://github.com/user-attachments/assets/55ef6c69-d33a-45db-ba19-ab32e3cfab2e
---- 
PR enables addition of label with ketcher solid phase templates, which will be used to generate a processed string for the sample as molcule name. 
- Add Label: After user has added a template on the canvas, they can select any added template on the canvas and add a label to it, using text button on ketcher left tool bar.
- Remove Label: Label can be simply removed attached to a template by using Ketcher Editor features
- Update Label: User can always double click on the text to edit it inside the …

feat(Ket): add custom text to surface image nodes
